using System.Text.Json;
using LondonVIP.Infrastructure.Data;
using LondonVIP.Shared.Crm;
using LondonVIP.Shared.Models;
using LondonVIP.Shared.Tenancy;
using LondonVIP.Shared.Workflows;
using Microsoft.EntityFrameworkCore;

namespace LondonVIP.Infrastructure.Crm;

public sealed class CrmService(LondonVIPDbContext db, ICompanyContext company, IBusinessEventPublisher events) : ICrmService
{
    public async Task<IReadOnlyList<CrmLeadDto>> SearchLeadsAsync(string? query, CancellationToken token=default)
    {var q=db.CrmLeads.AsNoTracking().Where(x=>x.CompanyId==company.CompanyId);if(!string.IsNullOrWhiteSpace(query)){var term=query.Trim();q=q.Where(x=>x.Reference.Contains(term)||x.FirstName.Contains(term)||x.LastName.Contains(term)||(x.Email!=null&&x.Email.Contains(term))||(x.Phone!=null&&x.Phone.Contains(term)));}return await q.OrderByDescending(x=>x.UpdatedAt).Take(250).Select(x=>MapLead(x)).ToListAsync(token);}
    public async Task<CrmLeadDto?> GetLeadAsync(Guid id,CancellationToken token=default)=>await db.CrmLeads.AsNoTracking().Where(x=>x.CompanyId==company.CompanyId&&x.Id==id).Select(x=>MapLead(x)).SingleOrDefaultAsync(token);
    public async Task<CrmLeadDto> CreateLeadAsync(CrmLeadRequest r,CancellationToken token=default)
    {var now=DateTimeOffset.UtcNow;var x=new CrmLead{Id=Guid.NewGuid(),CompanyId=company.CompanyId,Reference=$"LEAD-{now:yyyyMMdd}-{Guid.NewGuid():N}"[..22].ToUpperInvariant(),CreatedAt=now,UpdatedAt=now};Apply(x,r);db.CrmLeads.Add(x);AddActivity(CrmActivityType.StatusChange,"Lead created",x.Id,null,x.Id);await db.SaveChangesAsync(token);await events.PublishAsync(new("CrmLeadCreated","CrmLead",x.Id,JsonSerializer.Serialize(new{x.Reference,x.Source})),token);return MapLead(x);}
    public async Task<CrmLeadDto?> UpdateLeadAsync(Guid id,CrmLeadRequest r,CancellationToken token=default)
    {var x=await db.CrmLeads.SingleOrDefaultAsync(x=>x.CompanyId==company.CompanyId&&x.Id==id,token);if(x is null)return null;var previous=x.Status;Apply(x,r);x.UpdatedAt=DateTimeOffset.UtcNow;if(previous!=x.Status)AddActivity(CrmActivityType.StatusChange,$"Lead changed from {previous} to {x.Status}",x.Id,null,x.Id);await db.SaveChangesAsync(token);return MapLead(x);}
    public async Task<Guid?> ConvertLeadAsync(Guid id,CancellationToken token=default)
    {var lead=await db.CrmLeads.SingleOrDefaultAsync(x=>x.CompanyId==company.CompanyId&&x.Id==id,token);if(lead is null)return null;if(lead.CustomerId.HasValue)return lead.CustomerId;var customer=await db.Customers.FirstOrDefaultAsync(x=>x.CompanyId==company.CompanyId&&lead.Email!=null&&x.Email.ToLower()==lead.Email.ToLower(),token);if(customer is null){var now=DateTimeOffset.UtcNow;customer=new(){Id=Guid.NewGuid(),CompanyId=company.CompanyId,FirstName=lead.FirstName,LastName=lead.LastName,Email=lead.Email??string.Empty,Phone=lead.Phone??string.Empty,IsActive=true,CreatedAt=now,UpdatedAt=now};db.Customers.Add(customer);}lead.CustomerId=customer.Id;lead.Status=CrmLeadStatus.Converted;lead.UpdatedAt=DateTimeOffset.UtcNow;AddActivity(CrmActivityType.StatusChange,"Lead converted to customer",lead.Id,customer.Id,lead.Id);await db.SaveChangesAsync(token);await events.PublishAsync(new("CrmLeadConverted","Customer",customer.Id,JsonSerializer.Serialize(new{LeadId=lead.Id})),token);return customer.Id;}
    public async Task<IReadOnlyList<OpportunityDto>> GetPipelineAsync(CancellationToken token=default)=>await db.CrmOpportunities.AsNoTracking().Where(x=>x.CompanyId==company.CompanyId).OrderBy(x=>x.PipelineStage.SortOrder).ThenByDescending(x=>x.Value).Select(x=>new OpportunityDto(x.Id,x.Name,x.PipelineStage.Name,x.Value,x.Probability,x.Value*x.Probability/100m,x.LeadId,x.CustomerId,x.CorporateAccountId,x.WinLossReason,x.UpdatedAt)).ToListAsync(token);
    public async Task<OpportunityDto?> CreateOpportunityAsync(OpportunityRequest r,CancellationToken token=default)
    {var stage=await db.CrmPipelineStages.AsNoTracking().SingleOrDefaultAsync(x=>x.CompanyId==company.CompanyId&&x.Id==r.PipelineStageId&&x.IsActive,token);if(stage is null||!await ReferencesValid(r,token))return null;var now=DateTimeOffset.UtcNow;var x=new CrmOpportunity{Id=Guid.NewGuid(),CompanyId=company.CompanyId,Name=r.Name.Trim(),PipelineStageId=stage.Id,LeadId=r.LeadId,CustomerId=r.CustomerId,CorporateAccountId=r.CorporateAccountId,Value=r.Value,Probability=r.Probability,ExpectedCloseAt=r.ExpectedCloseAt,OwnerUserId=r.OwnerUserId,WinLossReason=r.WinLossReason,CreatedAt=now,UpdatedAt=now};db.CrmOpportunities.Add(x);AddActivity(CrmActivityType.StatusChange,"Opportunity created",x.Id,r.CustomerId,r.LeadId);await db.SaveChangesAsync(token);return new(x.Id,x.Name,stage.Name,x.Value,x.Probability,x.Value*x.Probability/100m,x.LeadId,x.CustomerId,x.CorporateAccountId,x.WinLossReason,x.UpdatedAt);}
    public async Task<OpportunityDto?> MoveOpportunityAsync(Guid id,Guid stageId,string? reason,CancellationToken token=default)
    {var x=await db.CrmOpportunities.Include(x=>x.PipelineStage).SingleOrDefaultAsync(x=>x.CompanyId==company.CompanyId&&x.Id==id,token);var stage=await db.CrmPipelineStages.SingleOrDefaultAsync(x=>x.CompanyId==company.CompanyId&&x.Id==stageId&&x.IsActive,token);if(x is null||stage is null)return null;x.PipelineStageId=stage.Id;x.PipelineStage=stage;x.Probability=stage.DefaultProbability;x.WinLossReason=stage.IsWon||stage.IsLost?reason:null;x.UpdatedAt=DateTimeOffset.UtcNow;AddActivity(CrmActivityType.StatusChange,$"Opportunity moved to {stage.Name}",x.Id,x.CustomerId,x.LeadId);await db.SaveChangesAsync(token);return new(x.Id,x.Name,stage.Name,x.Value,x.Probability,x.Value*x.Probability/100m,x.LeadId,x.CustomerId,x.CorporateAccountId,x.WinLossReason,x.UpdatedAt);}
    public async Task<ConversationDto> IngestAsync(IncomingMessageRequest r,CancellationToken token=default)
    {var existingMessage=await db.CrmMessages.AsNoTracking().Where(x=>x.CompanyId==company.CompanyId&&x.ExternalMessageId==r.ExternalMessageId).Select(x=>x.ConversationId).SingleOrDefaultAsync(token);if(existingMessage!=Guid.Empty)return (await GetConversation(existingMessage,token))!;var conversation=await db.CrmConversations.SingleOrDefaultAsync(x=>x.CompanyId==company.CompanyId&&x.Channel==r.Channel&&x.ExternalThreadId==r.ExternalThreadId,token);var customer=await db.Customers.AsNoTracking().FirstOrDefaultAsync(x=>x.CompanyId==company.CompanyId&&(x.Email.ToLower()==r.ParticipantAddress.ToLower()||x.Phone==r.ParticipantAddress),token);if(conversation is null){Guid? leadId=null;if(customer is null){var parts=r.ParticipantAddress.Contains('@')?r.ParticipantAddress.Split('@')[0].Split(['.','_']):["New","Contact"];var lead=await CreateLeadAsync(new(parts.FirstOrDefault()??"New",parts.Skip(1).FirstOrDefault()??"Contact",r.ParticipantAddress.Contains('@')?r.ParticipantAddress:null,r.ParticipantAddress.Contains('@')?null:r.ParticipantAddress,r.Channel.ToString(),0,CrmLeadStatus.New,CrmPriority.Normal,10,0,null,DateTimeOffset.UtcNow,null,null),token);leadId=lead.Id;}var now=DateTimeOffset.UtcNow;conversation=new(){Id=Guid.NewGuid(),CompanyId=company.CompanyId,Channel=r.Channel,ExternalThreadId=r.ExternalThreadId,Subject=r.Subject,ParticipantAddress=r.ParticipantAddress,CustomerId=customer?.Id,LeadId=leadId,BookingId=r.BookingId,QuotationId=r.QuotationId,InvoiceId=r.InvoiceId,Priority=CrmPriority.Normal,IsUnread=true,CreatedAt=now,UpdatedAt=now};db.CrmConversations.Add(conversation);}conversation.IsUnread=true;conversation.UpdatedAt=DateTimeOffset.UtcNow;db.CrmMessages.Add(new(){Id=Guid.NewGuid(),CompanyId=company.CompanyId,ConversationId=conversation.Id,ExternalMessageId=r.ExternalMessageId,IsInbound=true,Sender=r.ParticipantAddress,Body=r.Body,AttachmentUrl=r.AttachmentUrl,Status="Received",SentAt=r.SentAt,CreatedAt=DateTimeOffset.UtcNow});AddActivity(ChannelType(r.Channel),$"Incoming {r.Channel} message",conversation.Id,conversation.CustomerId,conversation.LeadId,conversation.Id,r.Body);await db.SaveChangesAsync(token);await events.PublishAsync(new("CrmMessageReceived","CrmConversation",conversation.Id,JsonSerializer.Serialize(new{r.Channel,conversation.CustomerId,conversation.LeadId})),token);return (await GetConversation(conversation.Id,token))!;}
    public async Task<IReadOnlyList<ConversationDto>> GetConversationsAsync(string? query,CrmConversationChannel? channel,CancellationToken token=default)
    {var q=db.CrmConversations.AsNoTracking().Where(x=>x.CompanyId==company.CompanyId);if(channel.HasValue)q=q.Where(x=>x.Channel==channel);if(!string.IsNullOrWhiteSpace(query)){var term=query.Trim();q=q.Where(x=>x.Subject.Contains(term)||x.ParticipantAddress.Contains(term)||x.Tags.Contains(term)||db.CrmMessages.Any(m=>m.ConversationId==x.Id&&m.Body.Contains(term)));}return await q.OrderByDescending(x=>x.IsPinned).ThenByDescending(x=>x.UpdatedAt).Take(250).Select(ConversationProjection).ToListAsync(token);}
    public async Task<IReadOnlyList<TimelineItemDto>> GetTimelineAsync(Guid? customerId,Guid? leadId,CancellationToken token=default)
    {var activity=await db.CrmActivities.AsNoTracking().Where(x=>x.CompanyId==company.CompanyId&&(!customerId.HasValue||x.CustomerId==customerId)&&(!leadId.HasValue||x.LeadId==leadId)).OrderByDescending(x=>x.OccurredAt).Take(500).Select(x=>new TimelineItemDto(x.Id,x.Type,x.Subject,x.Details,x.ResourceType,x.ResourceId,x.OccurredAt)).ToListAsync(token);if(customerId.HasValue){activity.AddRange(await db.Bookings.AsNoTracking().Where(x=>x.CompanyId==company.CompanyId&&x.CustomerId==customerId).Select(x=>new TimelineItemDto(x.Id,CrmActivityType.Booking,$"Booking {x.BookingReference}",x.Status.ToString(),"Booking",x.Id,x.CreatedAt)).ToListAsync(token));activity.AddRange(await db.Quotations.AsNoTracking().Where(x=>x.CompanyId==company.CompanyId&&x.CustomerId==customerId).Select(x=>new TimelineItemDto(x.Id,CrmActivityType.Quote,$"Quotation {x.QuoteReference}",x.Status.ToString(),"Quotation",x.Id,x.CreatedAt)).ToListAsync(token));activity.AddRange(await db.Invoices.AsNoTracking().Where(x=>x.CompanyId==company.CompanyId&&x.CustomerId==customerId).Select(x=>new TimelineItemDto(x.Id,CrmActivityType.Invoice,$"Invoice {x.InvoiceNumber}",x.Status.ToString(),"Invoice",x.Id,x.CreatedAt)).ToListAsync(token));activity.AddRange(await db.Payments.AsNoTracking().Where(x=>x.CompanyId==company.CompanyId&&x.CustomerId==customerId).Select(x=>new TimelineItemDto(x.Id,CrmActivityType.Payment,$"Payment {x.PaymentReference}",x.Amount.ToString(),"Payment",x.Id,x.CreatedAt)).ToListAsync(token));}return activity.OrderByDescending(x=>x.OccurredAt).Take(500).ToList();}
    public async Task<CrmDashboardDto> GetDashboardAsync(CancellationToken token=default)
    {var leads=db.CrmLeads.AsNoTracking().Where(x=>x.CompanyId==company.CompanyId);var opportunities=db.CrmOpportunities.AsNoTracking().Where(x=>x.CompanyId==company.CompanyId);var total=await leads.CountAsync(token);var converted=await leads.CountAsync(x=>x.Status==CrmLeadStatus.Converted,token);return new(await leads.CountAsync(x=>x.Status!=CrmLeadStatus.Converted&&x.Status!=CrmLeadStatus.Lost,token),await opportunities.CountAsync(token),await opportunities.SumAsync(x=>(decimal?)(x.Value*x.Probability/100m),token)??0,await db.CrmConversations.CountAsync(x=>x.CompanyId==company.CompanyId&&x.IsUnread&&!x.IsArchived,token),await db.CrmTasks.CountAsync(x=>x.CompanyId==company.CompanyId&&x.Status!=CrmTaskStatus.Completed&&x.DueAt<DateTimeOffset.UtcNow,token),await db.CrmReviews.CountAsync(x=>x.CompanyId==company.CompanyId&&x.IsComplaint&&x.Resolution==null,token),await db.CrmCampaigns.Where(x=>x.CompanyId==company.CompanyId).SumAsync(x=>(decimal?)x.Revenue,token)??0,total==0?0:decimal.Round(converted*100m/total,2));}
    private Task<ConversationDto?> GetConversation(Guid id,CancellationToken token)=>db.CrmConversations.AsNoTracking().Where(x=>x.CompanyId==company.CompanyId&&x.Id==id).Select(ConversationProjection).SingleOrDefaultAsync(token);
    private static readonly System.Linq.Expressions.Expression<Func<CrmConversation,ConversationDto>> ConversationProjection=x=>new(x.Id,x.Channel,x.Subject,x.ParticipantAddress,x.Customer==null?null:x.Customer.FirstName+" "+x.Customer.LastName,x.LeadId,x.BookingId,x.QuotationId,x.InvoiceId,x.Priority,x.IsUnread,x.IsPinned,x.IsArchived,x.UpdatedAt,x.Messages.Count);
    private static CrmLeadDto MapLead(CrmLead x)=>new(x.Id,x.Reference,x.FirstName+" "+x.LastName,x.Email,x.Phone,x.Source,x.Score,x.Status,x.Priority,x.Probability,x.ExpectedRevenue,x.FollowUpAt,x.CustomerId,x.UpdatedAt);
    private static void Apply(CrmLead x,CrmLeadRequest r){x.FirstName=r.FirstName.Trim();x.LastName=r.LastName.Trim();x.Email=N(r.Email);x.Phone=N(r.Phone);x.Source=r.Source.Trim();x.Score=Math.Clamp(r.Score,0,100);x.Status=r.Status;x.Priority=r.Priority;x.Probability=Math.Clamp(r.Probability,0,100);x.ExpectedRevenue=Math.Max(0,r.ExpectedRevenue);x.ExpectedCloseAt=r.ExpectedCloseAt;x.FollowUpAt=r.FollowUpAt;x.InternalNotes=N(r.InternalNotes);x.OwnerUserId=r.OwnerUserId;}
    private async Task<bool> ReferencesValid(OpportunityRequest r,CancellationToken t)=>(!r.LeadId.HasValue||await db.CrmLeads.AnyAsync(x=>x.Id==r.LeadId&&x.CompanyId==company.CompanyId,t))&&(!r.CustomerId.HasValue||await db.Customers.AnyAsync(x=>x.Id==r.CustomerId&&x.CompanyId==company.CompanyId,t))&&(!r.CorporateAccountId.HasValue||await db.CorporateAccounts.AnyAsync(x=>x.Id==r.CorporateAccountId&&x.CompanyId==company.CompanyId,t));
    private void AddActivity(CrmActivityType type,string subject,Guid resourceId,Guid? customerId=null,Guid? leadId=null,Guid? conversationId=null,string? details=null)=>db.CrmActivities.Add(new(){Id=Guid.NewGuid(),CompanyId=company.CompanyId,Type=type,Subject=subject,Details=details,ResourceType="CRM",ResourceId=resourceId,CustomerId=customerId,LeadId=leadId,ConversationId=conversationId,OccurredAt=DateTimeOffset.UtcNow});
    private static CrmActivityType ChannelType(CrmConversationChannel x)=>x switch{CrmConversationChannel.Email=>CrmActivityType.Email,CrmConversationChannel.Sms=>CrmActivityType.Sms,CrmConversationChannel.WhatsApp=>CrmActivityType.WhatsApp,CrmConversationChannel.FacebookMessenger=>CrmActivityType.Messenger,CrmConversationChannel.InstagramDirect=>CrmActivityType.Instagram,CrmConversationChannel.LinkedIn=>CrmActivityType.LinkedIn,CrmConversationChannel.GoogleBusiness=>CrmActivityType.GoogleBusiness,CrmConversationChannel.Voice=>CrmActivityType.Call,_=>CrmActivityType.Note};private static string? N(string? x)=>string.IsNullOrWhiteSpace(x)?null:x.Trim();
}
