using LondonVIP.Infrastructure.Data;
using LondonVIP.Shared.Models;
using LondonVIP.Shared.Tenancy;
using LondonVIP.Shared.Workflows;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace LondonVIP.Infrastructure.Workflows;

public sealed class BackgroundJobService(LondonVIPDbContext db,ICompanyContext company):IBackgroundJobService
{
 public async Task<WorkflowJobDto> ScheduleAsync(ScheduleWorkflowRequest r,Guid? eventId=null,CancellationToken token=default){var correlation=r.CorrelationId??Guid.NewGuid().ToString("N");var existing=await db.WorkflowJobs.AsNoTracking().SingleOrDefaultAsync(x=>x.CompanyId==company.CompanyId&&x.CorrelationId==correlation&&x.WorkflowType==r.WorkflowType,token);if(existing!=null)return Map(existing);var now=DateTimeOffset.UtcNow;var job=new WorkflowJob{Id=Guid.NewGuid(),CompanyId=company.CompanyId,BusinessEventId=eventId,WorkflowType=r.WorkflowType,Kind=r.Kind,Status=r.ScheduledAt>now?WorkflowJobStatus.Scheduled:WorkflowJobStatus.Waiting,PayloadJson=r.PayloadJson,CorrelationId=correlation,ScheduledAt=r.ScheduledAt,MaxAttempts=Math.Clamp(r.MaxAttempts,1,20),Recurrence=r.Recurrence,CreatedAt=now,UpdatedAt=now};db.WorkflowJobs.Add(job);await db.SaveChangesAsync(token);return Map(job);}
 public async Task<WorkflowPageDto<WorkflowJobDto>> GetAsync(WorkflowQuery r,CancellationToken token=default){var page=Math.Max(1,r.Page);var size=Math.Clamp(r.PageSize,1,100);var q=db.WorkflowJobs.AsNoTracking().Where(x=>x.CompanyId==company.CompanyId);if(r.Status.HasValue)q=q.Where(x=>x.Status==r.Status);if(!string.IsNullOrWhiteSpace(r.Search)){var term=r.Search.Trim();q=q.Where(x=>x.WorkflowType.Contains(term)||x.CorrelationId.Contains(term)||x.PayloadJson.Contains(term));}var total=await q.CountAsync(token);var items=await q.OrderByDescending(x=>x.CreatedAt).Skip((page-1)*size).Take(size).Select(x=>new WorkflowJobDto(x.Id,x.WorkflowType,x.Kind,x.Status,x.ScheduledAt,x.AttemptCount,x.MaxAttempts,x.EscalationLevel,x.LastError,x.CorrelationId,x.CreatedAt)).ToListAsync(token);return new(){Items=items,Page=page,PageSize=size,Total=total};}
 public async Task<bool> RetryAsync(Guid id,CancellationToken token=default){var x=await db.WorkflowJobs.SingleOrDefaultAsync(x=>x.Id==id&&x.CompanyId==company.CompanyId,token);if(x is null||x.Status is WorkflowJobStatus.Completed or WorkflowJobStatus.Cancelled)return false;x.Status=WorkflowJobStatus.Retrying;x.ScheduledAt=DateTimeOffset.UtcNow;x.UpdatedAt=DateTimeOffset.UtcNow;await db.SaveChangesAsync(token);return true;}
 public async Task<bool> CancelAsync(Guid id,CancellationToken token=default){var x=await db.WorkflowJobs.SingleOrDefaultAsync(x=>x.Id==id&&x.CompanyId==company.CompanyId,token);if(x is null||x.Status==WorkflowJobStatus.Completed)return false;x.Status=WorkflowJobStatus.Cancelled;x.UpdatedAt=DateTimeOffset.UtcNow;await db.SaveChangesAsync(token);return true;}
 internal static WorkflowJobDto Map(WorkflowJob x)=>new(x.Id,x.WorkflowType,x.Kind,x.Status,x.ScheduledAt,x.AttemptCount,x.MaxAttempts,x.EscalationLevel,x.LastError,x.CorrelationId,x.CreatedAt);
}
public sealed class WorkflowEngine(LondonVIPDbContext db,ICompanyContext company,IEscalationService escalation,ILogger<WorkflowEngine> logger):IWorkflowEngine
{public async Task ExecuteAsync(Guid id,CancellationToken token=default){var x=await db.WorkflowJobs.SingleOrDefaultAsync(x=>x.Id==id&&x.CompanyId==company.CompanyId,token);if(x is null||x.Status is WorkflowJobStatus.Completed or WorkflowJobStatus.Cancelled)return;var now=DateTimeOffset.UtcNow;x.Status=WorkflowJobStatus.Running;x.StartedAt??=now;x.LastAttemptAt=now;x.AttemptCount++;x.UpdatedAt=now;await db.SaveChangesAsync(token);try{x.Status=WorkflowJobStatus.Completed;x.CompletedAt=DateTimeOffset.UtcNow;x.LastError=null;}catch(Exception ex){x.LastError=ex.Message;x.Status=x.AttemptCount<x.MaxAttempts?WorkflowJobStatus.Retrying:WorkflowJobStatus.Failed;logger.LogError(ex,"Workflow job {WorkflowJobId} failed.",x.Id);}x.UpdatedAt=DateTimeOffset.UtcNow;await db.SaveChangesAsync(token);if(x.Status==WorkflowJobStatus.Failed)await escalation.EscalateAsync(x.Id,x.LastError??"Maximum attempts reached.",token);}}
public sealed class WorkflowScheduler(IBackgroundJobService jobs,IWorkflowEngine engine,LondonVIPDbContext db,ICompanyContext company):IWorkflowScheduler
{public Task<WorkflowJobDto> ScheduleAsync(ScheduleWorkflowRequest request,CancellationToken token=default)=>jobs.ScheduleAsync(request,null,token);public async Task ProcessDueAsync(CancellationToken token=default){var now=DateTimeOffset.UtcNow;var ids=await db.WorkflowJobs.AsNoTracking().Where(x=>x.CompanyId==company.CompanyId&&x.ScheduledAt<=now&&(x.Status==WorkflowJobStatus.Waiting||x.Status==WorkflowJobStatus.Scheduled||x.Status==WorkflowJobStatus.Retrying)).OrderBy(x=>x.ScheduledAt).Take(100).Select(x=>x.Id).ToListAsync(token);foreach(var id in ids)await engine.ExecuteAsync(id,token);}}
public sealed class BusinessEventPublisher(LondonVIPDbContext db,ICompanyContext company,IBusinessEventHandler handler,ILogger<BusinessEventPublisher> logger):IBusinessEventPublisher
{public async Task<Guid> PublishAsync(BusinessEvent e,CancellationToken token=default){var record=new BusinessEventRecord{Id=Guid.NewGuid(),CompanyId=company.CompanyId,EventType=e.EventType,ResourceType=e.ResourceType,ResourceId=e.ResourceId,PayloadJson=e.PayloadJson,CorrelationId=e.CorrelationId??Guid.NewGuid().ToString("N"),OccurredAt=DateTimeOffset.UtcNow};db.BusinessEvents.Add(record);await db.SaveChangesAsync(token);try{await handler.HandleAsync(record,token);}catch(Exception ex){logger.LogError(ex,"Workflow handling failed for business event {BusinessEventId}; the event remains durable.",record.Id);}return record.Id;}}
public sealed class BusinessEventHandler(IBackgroundJobService jobs):IBusinessEventHandler
{private static readonly Dictionary<string,string[]> Workflows=new(){[BusinessEventTypes.BookingCreated]=["Booking Confirmation","Customer Reminder"],[BusinessEventTypes.BookingAssigned]=["Booking Assignment","Driver Reminder"],[BusinessEventTypes.PaymentReceived]=["Payment Confirmation"],[BusinessEventTypes.QuotationCreated]=["Quotation Expiry Reminder"],[BusinessEventTypes.InvoiceCreated]=["Invoice Reminder"],[BusinessEventTypes.InvoiceOverdue]=["Overdue Invoice Reminder"],[BusinessEventTypes.DriverLicenceExpiring]=["Driver Licence Reminder"],[BusinessEventTypes.MOTExpiring]=["Vehicle MOT Reminder"],[BusinessEventTypes.InsuranceExpiring]=["Insurance Reminder"],[BusinessEventTypes.CorporateAccountOnHold]=["Corporate Account Reminder"]};public async Task HandleAsync(BusinessEventRecord e,CancellationToken token=default){if(!Workflows.TryGetValue(e.EventType,out var workflows))return;foreach(var workflow in workflows)await jobs.ScheduleAsync(new(workflow,e.PayloadJson,DateTimeOffset.UtcNow,WorkflowJobKind.OneTime,$"{e.CorrelationId}:{workflow}"),e.Id,token);}}
public sealed class RuleEngine(LondonVIPDbContext db,ICompanyContext company):IRuleEngine
{public async Task<WorkflowRuleResult> EvaluateAsync(string eventType,WorkflowRuleContext context,CancellationToken token=default){var rules=await db.WorkflowRules.AsNoTracking().Where(x=>x.CompanyId==company.CompanyId&&x.EventType==eventType&&x.IsActive).OrderByDescending(x=>x.Priority).ToListAsync(token);foreach(var r in rules){if(!context.Values.TryGetValue(r.ConditionField,out var value))continue;var match=r.Operator switch{"Equals"=>string.Equals(value,r.ComparisonValue,StringComparison.OrdinalIgnoreCase),"NotEquals"=>!string.Equals(value,r.ComparisonValue,StringComparison.OrdinalIgnoreCase),"GreaterThan"=>decimal.TryParse(value,out var a)&&decimal.TryParse(r.ComparisonValue,out var b)&&a>b,"LessThan"=>decimal.TryParse(value,out var c)&&decimal.TryParse(r.ComparisonValue,out var d)&&c<d,_=>false};if(match)return new(true,r.Action,r.Name);}return new(false,null,null);}}
public sealed class EscalationService(LondonVIPDbContext db,ICompanyContext company):IEscalationService
{public async Task EscalateAsync(Guid id,string reason,CancellationToken token=default){var x=await db.WorkflowJobs.SingleOrDefaultAsync(x=>x.Id==id&&x.CompanyId==company.CompanyId,token);if(x is null)return;x.EscalationLevel++;x.Status=WorkflowJobStatus.Escalated;x.LastError=reason;x.UpdatedAt=DateTimeOffset.UtcNow;await db.SaveChangesAsync(token);}}
public sealed class ReminderService(LondonVIPDbContext db,ICompanyContext company,IBackgroundJobService jobs):IReminderService
{public async Task<int> GenerateAsync(CancellationToken token=default){var now=DateTimeOffset.UtcNow;var soon=now.AddHours(24);var generated=0;var bookings=await db.Bookings.AsNoTracking().Where(x=>x.CompanyId==company.CompanyId&&x.PickupDateTime>now&&x.PickupDateTime<=soon&&x.Status!=BookingStatus.Cancelled).Select(x=>new{x.Id,x.BookingReference,x.PickupDateTime,x.IsAirportPickup}).ToListAsync(token);foreach(var x in bookings){await jobs.ScheduleAsync(new(x.IsAirportPickup?"Airport Pickup Reminder":"Customer Reminder",System.Text.Json.JsonSerializer.Serialize(x),x.PickupDateTime.AddHours(-2),WorkflowJobKind.Delayed,$"booking-reminder:{x.Id}"),null,token);generated++;}var invoices=await db.Invoices.AsNoTracking().Where(x=>x.CompanyId==company.CompanyId&&x.BalanceDue>0&&x.DueDate<=now.AddDays(7)&&x.Status!=InvoiceStatus.Cancelled).Select(x=>new{x.Id,x.InvoiceNumber,x.DueDate}).ToListAsync(token);foreach(var x in invoices){await jobs.ScheduleAsync(new(x.DueDate<now?"Overdue Invoice Reminder":"Invoice Reminder",System.Text.Json.JsonSerializer.Serialize(x),now,WorkflowJobKind.Delayed,$"invoice-reminder:{x.Id}:{now:yyyyMMdd}"),null,token);generated++;}return generated;}}
