using LondonVIP.Infrastructure.Data;
using LondonVIP.Shared.Accounting;
using LondonVIP.Shared.Models;
using LondonVIP.Shared.Tenancy;
using Microsoft.EntityFrameworkCore;

namespace LondonVIP.Infrastructure.Accounting;

public sealed class JournalService(LondonVIPDbContext db,ICompanyContext company):IJournalService
{
 public async Task<JournalResult> CreateAsync(JournalRequest r,CancellationToken t=default){if(r.Entries.Count<2||r.Entries.Any(x=>x.Debit<0||x.Credit<0||(x.Debit>0&&x.Credit>0))||r.Entries.Sum(x=>x.Debit)!=r.Entries.Sum(x=>x.Credit)||r.Entries.Sum(x=>x.Debit)<=0)throw new InvalidOperationException("Journal entries must contain equal positive debits and credits.");var ids=r.Entries.Select(x=>x.LedgerAccountId).Distinct().ToList();if(await db.LedgerAccounts.CountAsync(x=>x.CompanyId==company.CompanyId&&x.IsActive&&x.AllowPosting&&ids.Contains(x.Id),t)!=ids.Count)throw new InvalidOperationException("A posting account is invalid.");if(await db.Journals.AnyAsync(x=>x.CompanyId==company.CompanyId&&x.Reference==r.Reference,t))throw new InvalidOperationException("Journal reference already exists.");var x=new Journal{Id=Guid.NewGuid(),CompanyId=company.CompanyId,Reference=r.Reference.Trim(),JournalDate=r.JournalDate,Description=r.Description.Trim(),SourceType=r.SourceType.Trim(),SourceId=r.SourceId,Status=JournalStatus.Draft,CreatedAt=DateTimeOffset.UtcNow,Entries=r.Entries.Select(e=>new JournalEntry{Id=Guid.NewGuid(),CompanyId=company.CompanyId,LedgerAccountId=e.LedgerAccountId,Description=e.Description.Trim(),Debit=e.Debit,Credit=e.Credit,Department=e.Department,CostCentre=e.CostCentre}).ToList()};db.Add(x);await db.SaveChangesAsync(t);return Map(x);}
 public async Task<JournalResult?> PostAsync(Guid id,CancellationToken t=default){var x=await db.Journals.Include(x=>x.Entries).SingleOrDefaultAsync(x=>x.CompanyId==company.CompanyId&&x.Id==id,t);if(x is null)return null;if(x.Status!=JournalStatus.Draft)throw new InvalidOperationException("Only draft journals can be posted.");if(await db.AccountingPeriods.AnyAsync(p=>p.CompanyId==company.CompanyId&&p.Status==AccountingPeriodStatus.Closed&&p.StartsOn<=x.JournalDate&&p.EndsOn>=x.JournalDate,t))throw new InvalidOperationException("The accounting period is closed.");x.Status=JournalStatus.Posted;x.PostedAt=DateTimeOffset.UtcNow;await db.SaveChangesAsync(t);return Map(x);}
 public async Task<TrialBalanceDto> TrialBalanceAsync(DateOnly from,DateOnly to,CancellationToken t=default){var values=await db.JournalEntries.AsNoTracking().Where(x=>x.CompanyId==company.CompanyId&&x.Journal.Status==JournalStatus.Posted&&x.Journal.JournalDate>=from&&x.Journal.JournalDate<=to).GroupBy(x=>new{x.LedgerAccount.Code,x.LedgerAccount.Name,x.LedgerAccount.Type}).Select(g=>new{g.Key.Code,g.Key.Name,g.Key.Type,Debit=g.Sum(x=>x.Debit),Credit=g.Sum(x=>x.Credit)}).OrderBy(x=>x.Code).ToListAsync(t);var rows=values.Select(x=>new TrialBalanceLine(x.Code,x.Name,x.Type,x.Debit,x.Credit)).ToList();return new(from,to,rows,rows.Sum(x=>x.Debit),rows.Sum(x=>x.Credit));}
 static JournalResult Map(Journal x)=>new(x.Id,x.Reference,x.Status,x.Entries.Sum(e=>e.Debit),x.Entries.Sum(e=>e.Credit));
}

public sealed class AccountingReportService(LondonVIPDbContext db,ICompanyContext company,TimeProvider clock):IAccountingReportService
{
 public async Task<FinanceDashboardDto> DashboardAsync(CancellationToken t=default){var now=clock.GetUtcNow();var start=new DateTimeOffset(now.Year,now.Month,1,0,0,0,TimeSpan.Zero);var revenue=await db.Invoices.Where(x=>x.CompanyId==company.CompanyId&&x.InvoiceDate>=start&&x.Status!=InvoiceStatus.Cancelled).SumAsync(x=>(decimal?)x.Subtotal,t)??0;var expenses=await db.Expenses.Where(x=>x.CompanyId==company.CompanyId&&x.ExpenseDate>=DateOnly.FromDateTime(start.Date)&&x.Status!=ExpenseStatus.Rejected).SumAsync(x=>(decimal?)x.NetAmount,t)??0;return new(await db.Invoices.Where(x=>x.CompanyId==company.CompanyId&&x.Status!=InvoiceStatus.Cancelled).SumAsync(x=>(decimal?)x.BalanceDue,t)??0,await db.SupplierInvoices.Where(x=>x.CompanyId==company.CompanyId&&x.Status!=PayableStatus.Cancelled).SumAsync(x=>(decimal?)(x.TotalAmount-x.AmountPaid),t)??0,revenue,expenses,await db.Payments.Where(x=>x.CompanyId==company.CompanyId&&x.PaymentDate>=start).SumAsync(x=>(decimal?)x.Amount,t)??0,await VatAsync(DateOnly.FromDateTime(start.Date),DateOnly.FromDateTime(now.Date),t).ContinueWith(x=>x.Result.VatDue,t),await db.Invoices.CountAsync(x=>x.CompanyId==company.CompanyId&&x.BalanceDue>0&&x.DueDate<now,t),await db.Expenses.CountAsync(x=>x.CompanyId==company.CompanyId&&(x.Status==ExpenseStatus.Submitted||x.Status==ExpenseStatus.Draft),t),await db.AccountingPeriods.CountAsync(x=>x.CompanyId==company.CompanyId&&x.Status==AccountingPeriodStatus.Open,t));}
 public async Task<VatReportDto> VatAsync(DateOnly from,DateOnly to,CancellationToken t=default){var start=new DateTimeOffset(from.ToDateTime(TimeOnly.MinValue),TimeSpan.Zero);var end=new DateTimeOffset(to.ToDateTime(TimeOnly.MaxValue),TimeSpan.Zero);var sales=await db.Invoices.Where(x=>x.CompanyId==company.CompanyId&&x.InvoiceDate>=start&&x.InvoiceDate<=end&&x.Status!=InvoiceStatus.Cancelled).GroupBy(_=>1).Select(g=>new{Net=g.Sum(x=>x.Subtotal),Vat=g.Sum(x=>x.TaxAmount)}).SingleOrDefaultAsync(t);var purchases=await db.SupplierInvoices.Where(x=>x.CompanyId==company.CompanyId&&x.InvoiceDate>=from&&x.InvoiceDate<=to&&x.Status!=PayableStatus.Cancelled).GroupBy(_=>1).Select(g=>new{Net=g.Sum(x=>x.NetAmount),Vat=g.Sum(x=>x.VatAmount)}).SingleOrDefaultAsync(t);var expenses=await db.Expenses.Where(x=>x.CompanyId==company.CompanyId&&x.ExpenseDate>=from&&x.ExpenseDate<=to&&x.Status!=ExpenseStatus.Rejected).GroupBy(_=>1).Select(g=>new{Net=g.Sum(x=>x.NetAmount),Vat=g.Sum(x=>x.VatAmount)}).SingleOrDefaultAsync(t);var netPurchases=(purchases?.Net??0)+(expenses?.Net??0);var input=(purchases?.Vat??0)+(expenses?.Vat??0);return new(from,to,sales?.Net??0,sales?.Vat??0,netPurchases,input,(sales?.Vat??0)-input);}
 public async Task<ProfitAndLossDto> ProfitAndLossAsync(DateOnly from,DateOnly to,CancellationToken t=default){var vat=await VatAsync(from,to,t);var entries=await db.JournalEntries.Where(x=>x.CompanyId==company.CompanyId&&x.Journal.Status==JournalStatus.Posted&&x.Journal.JournalDate>=from&&x.Journal.JournalDate<=to).GroupBy(x=>x.LedgerAccount.Type).Select(g=>new{Type=g.Key,Amount=g.Sum(x=>x.Credit-x.Debit)}).ToListAsync(t);var revenue=entries.Where(x=>x.Type==LedgerAccountType.Revenue).Sum(x=>x.Amount);if(revenue==0)revenue=vat.NetSales;var expense=Math.Abs(entries.Where(x=>x.Type==LedgerAccountType.Expense).Sum(x=>x.Amount));if(expense==0)expense=vat.NetPurchases;return new(from,to,revenue,0,expense,revenue-expense);}
}

public sealed class DriverSettlementService(LondonVIPDbContext db,ICompanyContext company):IDriverSettlementService
{
 public async Task<DriverSettlement> CreateAsync(DriverSettlementRequest r,CancellationToken t=default){if(r.PeriodEnd<r.PeriodStart||r.Bonuses<0||r.Penalties<0)throw new InvalidOperationException("Settlement values are invalid.");if(!await db.Drivers.AnyAsync(x=>x.CompanyId==company.CompanyId&&x.Id==r.DriverId,t))throw new InvalidOperationException("Driver was not found.");if(await db.DriverSettlements.AnyAsync(x=>x.CompanyId==company.CompanyId&&x.DriverId==r.DriverId&&x.PeriodStart==r.PeriodStart&&x.PeriodEnd==r.PeriodEnd&&x.Status!=SettlementStatus.Cancelled,t))throw new InvalidOperationException("A settlement already exists for this period.");var start=new DateTimeOffset(r.PeriodStart.ToDateTime(TimeOnly.MinValue),TimeSpan.Zero);var end=new DateTimeOffset(r.PeriodEnd.ToDateTime(TimeOnly.MaxValue),TimeSpan.Zero);var gross=await db.Bookings.Where(x=>x.CompanyId==company.CompanyId&&x.DriverId==r.DriverId&&x.Status==BookingStatus.Completed&&x.PickupDateTime>=start&&x.PickupDateTime<=end).SumAsync(x=>(decimal?)x.TotalFare,t)??0;var rate=await db.CompanySettings.Where(x=>x.CompanyId==company.CompanyId).Select(x=>x.DriverCommissionPercentage).SingleAsync(t);var commission=decimal.Round(gross*rate/100m,2);var x=new DriverSettlement{Id=Guid.NewGuid(),CompanyId=company.CompanyId,DriverId=r.DriverId,Reference=$"DRV-{r.PeriodEnd:yyyyMMdd}-{Guid.NewGuid():N}"[..21].ToUpperInvariant(),PeriodStart=r.PeriodStart,PeriodEnd=r.PeriodEnd,Status=SettlementStatus.Draft,GrossFares=gross,Commission=commission,Bonuses=r.Bonuses,Penalties=r.Penalties,Adjustments=r.Adjustments,NetPayable=gross-commission+r.Bonuses-r.Penalties+r.Adjustments,CreatedAt=DateTimeOffset.UtcNow};db.Add(x);await db.SaveChangesAsync(t);return x;}
}
