using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
using System.Xml.Linq;
using LondonVIP.Infrastructure.Data;
using LondonVIP.Shared.Accounting;
using LondonVIP.Shared.Invoicing;
using LondonVIP.Shared.Models;
using LondonVIP.Shared.Tenancy;
using Microsoft.EntityFrameworkCore;
using LondonVIP.Shared.Workflows;

namespace LondonVIP.Infrastructure.Accounting;

public sealed class CreditNoteService(LondonVIPDbContext db,ICompanyContext company):ICreditNoteService
{
 public async Task<CreditNote>CreateAsync(CreditNoteRequest r,CancellationToken t=default){var invoice=await db.Invoices.Include(x=>x.Lines).SingleOrDefaultAsync(x=>x.CompanyId==company.CompanyId&&x.Id==r.InvoiceId,t)??throw new InvalidOperationException("Invoice was not found.");if(invoice.Status==InvoiceStatus.Cancelled||r.Lines.Count==0)throw new InvalidOperationException("Invoice cannot be credited.");var lines=r.Lines.Select(x=>{if(x.Quantity<=0||x.UnitPrice<0||x.TaxRate<0)throw new InvalidOperationException("Credit line is invalid.");if(x.InvoiceLineId.HasValue&&!invoice.Lines.Any(y=>y.Id==x.InvoiceLineId))throw new InvalidOperationException("Invoice line was not found.");var net=decimal.Round(x.Quantity*x.UnitPrice,2);var tax=decimal.Round(net*x.TaxRate/100m,2);return new CreditNoteLine{Id=Guid.NewGuid(),CompanyId=company.CompanyId,InvoiceLineId=x.InvoiceLineId,Description=x.Description,Quantity=x.Quantity,UnitPrice=x.UnitPrice,TaxRate=x.TaxRate,NetAmount=net,TaxAmount=tax,TotalAmount=net+tax};}).ToList();var prior=await db.CreditNotes.Where(x=>x.CompanyId==company.CompanyId&&x.InvoiceId==invoice.Id&&x.Status!=CreditNoteStatus.Cancelled).SumAsync(x=>(decimal?)x.TotalAmount,t)??0;var total=lines.Sum(x=>x.TotalAmount);if(prior+total>invoice.TotalAmount)throw new InvalidOperationException("Credit exceeds the invoice total.");var count=await db.CreditNotes.CountAsync(x=>x.CompanyId==company.CompanyId,t)+1;var result=new CreditNote{Id=Guid.NewGuid(),CompanyId=company.CompanyId,InvoiceId=invoice.Id,CreditNoteNumber=$"CN-{DateTime.UtcNow:yyyy}-{count:000000}",CreditDate=DateTimeOffset.UtcNow,Status=CreditNoteStatus.Draft,Subtotal=lines.Sum(x=>x.NetAmount),TaxAmount=lines.Sum(x=>x.TaxAmount),TotalAmount=total,Reason=r.Reason,CreatedAt=DateTimeOffset.UtcNow,UpdatedAt=DateTimeOffset.UtcNow,Lines=lines};db.Add(result);await db.SaveChangesAsync(t);return result;}
 public async Task<CreditNote?>ApproveAsync(Guid id,CancellationToken t=default){await using var tx=await db.Database.BeginTransactionAsync(t);var x=await db.CreditNotes.Include(x=>x.Invoice).SingleOrDefaultAsync(x=>x.CompanyId==company.CompanyId&&x.Id==id,t);if(x is null)return null;if(x.Status!=CreditNoteStatus.Draft&&x.Status!=CreditNoteStatus.Submitted)throw new InvalidOperationException("Credit note is not awaiting approval.");x.Status=CreditNoteStatus.Issued;x.ApprovedAt=DateTimeOffset.UtcNow;x.UpdatedAt=DateTimeOffset.UtcNow;var issuedCredits=(await db.CreditNotes.Where(c=>c.CompanyId==company.CompanyId&&c.InvoiceId==x.InvoiceId&&c.Status==CreditNoteStatus.Issued&&c.Id!=x.Id).SumAsync(c=>(decimal?)c.TotalAmount,t)??0)+x.TotalAmount;x.Invoice.BalanceDue=Math.Max(0,x.Invoice.TotalAmount-x.Invoice.AmountPaid-issuedCredits);x.Invoice.Status=x.Invoice.BalanceDue==0?InvoiceStatus.Paid:x.Invoice.AmountPaid>0?InvoiceStatus.PartiallyPaid:InvoiceStatus.Issued;x.Invoice.UpdatedAt=DateTimeOffset.UtcNow;await db.SaveChangesAsync(t);await tx.CommitAsync(t);return x;}
}

public sealed record RecurringLine(string Description,decimal Quantity,decimal UnitPrice,decimal TaxRate);
public sealed class RecurringInvoiceService(LondonVIPDbContext db,ICompanyContext company,IInvoiceNumberGenerator numbers,IBusinessEventPublisher events):IRecurringInvoiceService
{
 public async Task<RecurringInvoiceSchedule>CreateAsync(RecurringInvoiceRequest r,CancellationToken t=default){if(r.Interval<1||r.EndsAt<r.StartsAt||r.CustomerId is null&&r.CorporateAccountId is null)throw new InvalidOperationException("Recurring schedule is invalid.");if(JsonSerializer.Deserialize<List<RecurringLine>>(r.LinesJson) is null)throw new InvalidOperationException("Invoice lines are invalid.");var x=new RecurringInvoiceSchedule{Id=Guid.NewGuid(),CompanyId=company.CompanyId,Name=r.Name,CustomerId=r.CustomerId,CorporateAccountId=r.CorporateAccountId,Frequency=r.Frequency,Interval=r.Interval,StartsAt=r.StartsAt,NextRunAt=r.StartsAt,EndsAt=r.EndsAt,Status=RecurringScheduleStatus.Active,PaymentTermsDays=r.PaymentTermsDays,LinesJson=r.LinesJson,CreatedAt=DateTimeOffset.UtcNow,UpdatedAt=DateTimeOffset.UtcNow};db.Add(x);await db.SaveChangesAsync(t);return x;}
 public async Task<bool>CommandAsync(Guid id,string action,CancellationToken t=default){var x=await db.RecurringInvoiceSchedules.SingleOrDefaultAsync(x=>x.CompanyId==company.CompanyId&&x.Id==id,t);if(x is null)return false;x.Status=action.ToLowerInvariant() switch{"pause"=>RecurringScheduleStatus.Paused,"resume"=>RecurringScheduleStatus.Active,"cancel"=>RecurringScheduleStatus.Cancelled,"retry"=>RecurringScheduleStatus.Active,_=>throw new InvalidOperationException("Schedule action is invalid.")};if(action.Equals("retry",StringComparison.OrdinalIgnoreCase))x.NextRunAt=DateTimeOffset.UtcNow;x.UpdatedAt=DateTimeOffset.UtcNow;await db.SaveChangesAsync(t);return true;}
 public async Task<int>ProcessDueAsync(CancellationToken t=default){var now=DateTimeOffset.UtcNow;var due=await db.RecurringInvoiceSchedules.Where(x=>x.CompanyId==company.CompanyId&&x.Status==RecurringScheduleStatus.Active&&x.NextRunAt<=now&&(x.EndsAt==null||x.EndsAt>=now)).Take(100).ToListAsync(t);var count=0;foreach(var s in due){try{var lines=JsonSerializer.Deserialize<List<RecurringLine>>(s.LinesJson)??[];var invoice=new Invoice{Id=Guid.NewGuid(),CompanyId=company.CompanyId,CustomerId=s.CustomerId,CorporateAccountId=s.CorporateAccountId,InvoiceNumber=await numbers.GenerateAsync(company.CompanyId,t),InvoiceDate=now,DueDate=now.AddDays(s.PaymentTermsDays),Status=InvoiceStatus.Draft,CreatedAt=now,UpdatedAt=now};foreach(var l in lines){var net=decimal.Round(l.Quantity*l.UnitPrice,2);var tax=decimal.Round(net*l.TaxRate/100m,2);invoice.Lines.Add(new(){Id=Guid.NewGuid(),Description=l.Description,Quantity=l.Quantity,UnitPrice=l.UnitPrice,TaxRate=l.TaxRate,LineSubtotal=net,TaxAmount=tax,LineTotal=net+tax,CreatedAt=now});}invoice.Subtotal=invoice.Lines.Sum(x=>x.LineSubtotal);invoice.TaxAmount=invoice.Lines.Sum(x=>x.TaxAmount);invoice.TotalAmount=invoice.Subtotal+invoice.TaxAmount;invoice.BalanceDue=invoice.TotalAmount;db.Add(invoice);s.LastRunAt=now;s.NextRunAt=Next(s,now);s.FailureCount=0;s.LastError=null;if(s.EndsAt<s.NextRunAt)s.Status=RecurringScheduleStatus.Completed;await db.SaveChangesAsync(t);await events.PublishAsync(new(BusinessEventTypes.RecurringInvoiceGenerated,"Invoice",invoice.Id,JsonSerializer.Serialize(new{invoice.TotalAmount}),invoice.Id.ToString()),t);count++;}catch(Exception ex){s.FailureCount++;s.Status=RecurringScheduleStatus.Failed;s.LastError=ex.Message.Length>1000?ex.Message[..1000]:ex.Message;}s.UpdatedAt=now;}await db.SaveChangesAsync(t);return count;}
 static DateTimeOffset Next(RecurringInvoiceSchedule s,DateTimeOffset from)=>s.Frequency switch{RecurrenceFrequency.Daily=>from.AddDays(s.Interval),RecurrenceFrequency.Weekly=>from.AddDays(7*s.Interval),RecurrenceFrequency.Monthly=>from.AddMonths(s.Interval),RecurrenceFrequency.Quarterly=>from.AddMonths(3*s.Interval),RecurrenceFrequency.Yearly=>from.AddYears(s.Interval),_=>from.AddDays(s.Interval)};
}

public sealed class SupplierPaymentService(LondonVIPDbContext db,ICompanyContext company):ISupplierPaymentService
{
 public async Task<SupplierPayment>CreateAsync(SupplierPaymentRequest r,CancellationToken t=default){if(r.Amount<=0||r.Allocations.Values.Any(x=>x<=0)||r.Allocations.Values.Sum()>r.Amount)throw new InvalidOperationException("Supplier payment is invalid.");var invoices=await db.SupplierInvoices.Where(x=>x.CompanyId==company.CompanyId&&x.SupplierId==r.SupplierId&&r.Allocations.Keys.Contains(x.Id)).ToListAsync(t);if(invoices.Count!=r.Allocations.Count)throw new InvalidOperationException("Supplier invoice was not found.");var x=new SupplierPayment{Id=Guid.NewGuid(),CompanyId=company.CompanyId,SupplierId=r.SupplierId,Reference=r.Reference,PaymentDate=r.PaymentDate,Amount=r.Amount,Method=r.Method,Status=SupplierPaymentStatus.Paid,UnallocatedAmount=r.Amount-r.Allocations.Values.Sum(),CreatedAt=DateTimeOffset.UtcNow};foreach(var invoice in invoices){var amount=r.Allocations[invoice.Id];if(amount>invoice.TotalAmount-invoice.AmountPaid)throw new InvalidOperationException("Allocation exceeds outstanding balance.");invoice.AmountPaid+=amount;invoice.Status=invoice.AmountPaid==invoice.TotalAmount?PayableStatus.Paid:PayableStatus.PartiallyPaid;x.Allocations.Add(new(){Id=Guid.NewGuid(),CompanyId=company.CompanyId,SupplierInvoiceId=invoice.Id,Amount=amount,CreatedAt=DateTimeOffset.UtcNow});}db.Add(x);await db.SaveChangesAsync(t);return x;}
}

public sealed class BankImportService(LondonVIPDbContext db,ICompanyContext company):IBankImportService
{
 public async Task<BankImportResult>ImportAsync(BankImportRequest r,CancellationToken t=default){if(!await db.BankAccounts.AnyAsync(x=>x.CompanyId==company.CompanyId&&x.Id==r.BankAccountId&&x.IsActive,t))throw new InvalidOperationException("Bank account was not found.");var hash=Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(r.Content)));var existing=await db.BankImportBatches.SingleOrDefaultAsync(x=>x.CompanyId==company.CompanyId&&x.BankAccountId==r.BankAccountId&&x.Sha256==hash,t);if(existing is not null)return new(existing.Id,0,existing.ImportedCount,0);var rows=Parse(r);if(rows.Count==0)throw new InvalidOperationException("The statement contains no valid transactions.");await using var transaction=await db.Database.BeginTransactionAsync(t);var batch=new BankImportBatch{Id=Guid.NewGuid(),CompanyId=company.CompanyId,BankAccountId=r.BankAccountId,Format=r.Format,FileName=r.FileName,Sha256=hash,CreatedAt=DateTimeOffset.UtcNow};foreach(var row in rows){if(await db.BankTransactions.AnyAsync(x=>x.CompanyId==company.CompanyId&&x.BankAccountId==r.BankAccountId&&x.TransactionDate==row.Date&&x.Reference==row.Reference&&x.Amount==row.Amount,t)){batch.DuplicateCount++;continue;}db.BankTransactions.Add(new(){Id=Guid.NewGuid(),CompanyId=company.CompanyId,BankAccountId=r.BankAccountId,TransactionDate=row.Date,Reference=row.Reference,Description=row.Description,Amount=row.Amount,Type=row.Amount>=0?BankTransactionType.Deposit:BankTransactionType.Withdrawal,ReconciliationStatus=ReconciliationStatus.Unmatched,ImportedStatementReference=batch.Id.ToString(),CreatedAt=DateTimeOffset.UtcNow});batch.ImportedCount++;}db.Add(batch);await db.SaveChangesAsync(t);await transaction.CommitAsync(t);return new(batch.Id,batch.ImportedCount,batch.DuplicateCount,0);}
 public async Task<bool>ReconcileAsync(ReconcileRequest r,CancellationToken t=default){var x=await db.BankTransactions.SingleOrDefaultAsync(x=>x.CompanyId==company.CompanyId&&x.Id==r.BankTransactionId,t);if(x is null)return false;if(r.PaymentId.HasValue&&!await db.Payments.AnyAsync(p=>p.CompanyId==company.CompanyId&&p.Id==r.PaymentId,t)||r.SupplierInvoiceId.HasValue&&!await db.SupplierInvoices.AnyAsync(p=>p.CompanyId==company.CompanyId&&p.Id==r.SupplierInvoiceId,t))return false;x.MatchedPaymentId=r.PaymentId;x.MatchedSupplierInvoiceId=r.SupplierInvoiceId;x.ReconciliationStatus=ReconciliationStatus.Reconciled;await db.SaveChangesAsync(t);return true;}
 public async Task<bool>UndoAsync(Guid id,CancellationToken t=default){var x=await db.BankTransactions.SingleOrDefaultAsync(x=>x.CompanyId==company.CompanyId&&x.Id==id,t);if(x is null)return false;x.MatchedPaymentId=null;x.MatchedSupplierInvoiceId=null;x.ReconciliationStatus=ReconciliationStatus.Unmatched;await db.SaveChangesAsync(t);return true;}
 static List<ImportedRow>Parse(BankImportRequest request)=>request.Format switch{BankImportFormat.Csv=>ParseCsv(request.Content),BankImportFormat.Qif=>ParseQif(request.Content),BankImportFormat.Ofx=>ParseOfx(request.Content),BankImportFormat.Camt=>ParseCamt(request.Content),_=>throw new InvalidOperationException("Statement format is unsupported.")};
 static List<ImportedRow>ParseCsv(string content)=>content.Split(['\r','\n'],StringSplitOptions.RemoveEmptyEntries).Skip(1).Select((line,index)=>{var cells=line.Split(',');if(cells.Length<4||!DateOnly.TryParse(cells[0],CultureInfo.InvariantCulture,out var date)||!decimal.TryParse(cells[2],NumberStyles.Number,CultureInfo.InvariantCulture,out var amount))throw new InvalidOperationException($"Invalid CSV transaction at line {index+2}.");return new ImportedRow(date,cells[1].Trim(),amount,cells[3].Trim());}).ToList();
 static List<ImportedRow>ParseQif(string content){var result=new List<ImportedRow>();foreach(var block in content.Split('^',StringSplitOptions.RemoveEmptyEntries)){var values=block.Split(['\r','\n'],StringSplitOptions.RemoveEmptyEntries).Where(x=>x.Length>1).GroupBy(x=>x[0]).ToDictionary(x=>x.Key,x=>x.Last()[1..]);if(!values.TryGetValue('D',out var rawDate)||!DateOnly.TryParse(rawDate,CultureInfo.InvariantCulture,out var date)||!values.TryGetValue('T',out var rawAmount)||!decimal.TryParse(rawAmount,NumberStyles.Number,CultureInfo.InvariantCulture,out var amount))continue;result.Add(new(date,values.GetValueOrDefault('N')??values.GetValueOrDefault('P')??Guid.NewGuid().ToString("N"),amount,values.GetValueOrDefault('M')??values.GetValueOrDefault('P')??"QIF transaction"));}return result;}
 static List<ImportedRow>ParseOfx(string content){var result=new List<ImportedRow>();foreach(Match block in Regex.Matches(content,"<STMTTRN>(.*?)</STMTTRN>",RegexOptions.Singleline|RegexOptions.IgnoreCase)){string?Tag(string name)=>Regex.Match(block.Groups[1].Value,$"<{name}>([^<\\r\\n]+)",RegexOptions.IgnoreCase) is{Success:true}m?m.Groups[1].Value.Trim():null;var rawDate=Tag("DTPOSTED");var rawAmount=Tag("TRNAMT");if(rawDate is null||rawAmount is null||rawDate.Length<8||!DateOnly.TryParseExact(rawDate[..8],"yyyyMMdd",CultureInfo.InvariantCulture,DateTimeStyles.None,out var date)||!decimal.TryParse(rawAmount,NumberStyles.Number,CultureInfo.InvariantCulture,out var amount))throw new InvalidOperationException("Invalid OFX transaction.");result.Add(new(date,Tag("FITID")??Guid.NewGuid().ToString("N"),amount,Tag("MEMO")??Tag("NAME")??"OFX transaction"));}return result;}
 static List<ImportedRow>ParseCamt(string content){XDocument document;try{document=XDocument.Parse(content);}catch(Exception ex){throw new InvalidOperationException("Invalid CAMT document.",ex);}return document.Descendants().Where(x=>x.Name.LocalName=="Ntry").Select(x=>{string?Value(string name)=>x.Descendants().FirstOrDefault(y=>y.Name.LocalName==name)?.Value;var rawDate=Value("Dt")??Value("DtTm");if(rawDate is null||!DateOnly.TryParse(rawDate[..Math.Min(10,rawDate.Length)],CultureInfo.InvariantCulture,out var date)||!decimal.TryParse(Value("Amt"),NumberStyles.Number,CultureInfo.InvariantCulture,out var amount))throw new InvalidOperationException("Invalid CAMT transaction.");if(Value("CdtDbtInd")=="DBIT")amount=-amount;return new ImportedRow(date,Value("NtryRef")??Value("AcctSvcrRef")??Guid.NewGuid().ToString("N"),amount,Value("AddtlNtryInf")??"CAMT transaction");}).ToList();}
 sealed record ImportedRow(DateOnly Date,string Reference,decimal Amount,string Description);
}
