using LondonVIP.Infrastructure.Data;
using LondonVIP.Shared.Dispatch;
using LondonVIP.Shared.Models;
using LondonVIP.Shared.Tenancy;
using Microsoft.EntityFrameworkCore;

namespace LondonVIP.Infrastructure.Dispatch;

public sealed class DispatchService(LondonVIPDbContext db, ICompanyContext company) : IDispatchService
{
    public async Task<DispatchPageDto<DispatchBoardItemDto>> GetBookingsAsync(DispatchQuery request, CancellationToken token = default) { var page = Math.Max(1, request.Page); var size = Math.Clamp(request.PageSize, 1, 100); var q = db.Bookings.AsNoTracking().Where(x => x.CompanyId == company.CompanyId); if (request.Status.HasValue) q = q.Where(x => x.Status == request.Status); if (request.DriverId.HasValue) q = q.Where(x => x.DriverId == request.DriverId); if (request.VehicleId.HasValue) q = q.Where(x => x.Driver != null && x.Driver.VehicleId == request.VehicleId); if (request.AirportOnly == true) q = q.Where(x => x.IsAirportPickup); if (request.CorporateOnly == true) q = q.Where(x => x.CorporateAccountId != null); if (request.Date.HasValue) { var start = new DateTimeOffset(request.Date.Value.ToDateTime(TimeOnly.MinValue), TimeSpan.Zero); var end = start.AddDays(1); q = q.Where(x => x.PickupDateTime >= start && x.PickupDateTime < end); } if (!string.IsNullOrWhiteSpace(request.Search)) { var term = request.Search.Trim(); q = q.Where(x => x.BookingReference.Contains(term) || x.Customer.FirstName.Contains(term) || x.Customer.LastName.Contains(term) || x.Customer.Phone.Contains(term) || x.PickupAddress.Contains(term) || x.Destination.Contains(term)); } var total = await q.CountAsync(token); var items = await Project(q.OrderBy(x => x.PickupDateTime).Skip((page - 1) * size).Take(size)).ToListAsync(token); SetTiming(items); return new() { Items = items, Page = page, PageSize = size, Total = total }; }
    public async Task<DispatchBoardItemDto?> GetBookingAsync(Guid id, CancellationToken token = default) { var item = await Project(db.Bookings.AsNoTracking().Where(x => x.Id == id && x.CompanyId == company.CompanyId)).SingleOrDefaultAsync(token); if (item != null) SetTiming([item]); return item; }
    public async Task<List<DispatchSearchResultDto>> SearchAsync(string term, int limit, CancellationToken token = default) { term = term.Trim(); if (term.Length < 2) return []; limit = Math.Clamp(limit, 1, 50); var bookings = await db.Bookings.AsNoTracking().Where(x => x.CompanyId == company.CompanyId && (x.BookingReference.Contains(term) || x.Customer.FirstName.Contains(term) || x.Customer.LastName.Contains(term) || x.Customer.Phone.Contains(term))).Take(limit).Select(x => new DispatchSearchResultDto("Booking", x.Id, x.BookingReference, x.Customer.FirstName + " " + x.Customer.LastName, x.PickupAddress + " → " + x.Destination, $"/erp/bookings?id={x.Id}")).ToListAsync(token); var drivers = await db.Drivers.AsNoTracking().Where(x => x.CompanyId == company.CompanyId && (x.FirstName.Contains(term) || x.LastName.Contains(term) || x.Phone.Contains(term) || (x.Vehicle != null && x.Vehicle.RegistrationNumber.Contains(term)))).Take(limit).Select(x => new DispatchSearchResultDto("Driver", x.Id, x.DriverNumber ?? "", x.FirstName + " " + x.LastName, x.Vehicle == null ? x.Phone : x.Vehicle.RegistrationNumber, $"/erp/drivers?id={x.Id}")).ToListAsync(token); var quotes = await db.Quotations.AsNoTracking().Where(x => x.CompanyId == company.CompanyId && x.QuoteReference.Contains(term)).Take(limit).Select(x => new DispatchSearchResultDto("Quotation", x.Id, x.QuoteReference, x.Customer.FirstName + " " + x.Customer.LastName, x.PickupAddress, $"/erp/quotes?id={x.Id}")).ToListAsync(token); var invoices = await db.Invoices.AsNoTracking().Where(x => x.CompanyId == company.CompanyId && x.InvoiceNumber.Contains(term)).Take(limit).Select(x => new DispatchSearchResultDto("Invoice", x.Id, x.InvoiceNumber, x.Customer == null ? "Corporate invoice" : x.Customer.FirstName + " " + x.Customer.LastName, x.BalanceDue.ToString(), $"/erp/invoicing?id={x.Id}")).ToListAsync(token); return bookings.Concat(drivers).Concat(quotes).Concat(invoices).Take(limit).ToList(); }
    internal static IQueryable<DispatchBoardItemDto> Project(IQueryable<Booking> q) => q.Select(x => new DispatchBoardItemDto { BookingId = x.Id, BookingReference = x.BookingReference, PickupDateTime = x.PickupDateTime, CustomerName = x.Customer.FirstName + " " + x.Customer.LastName, PickupAddress = x.PickupAddress, Destination = x.Destination, AirportCode = x.Airport == null ? null : x.Airport.Code, FlightNumber = x.FlightNumber, VehicleType = x.VehicleType, DriverId = x.DriverId, DriverName = x.Driver == null ? null : x.Driver.FirstName + " " + x.Driver.LastName, DriverVehicleRegistration = x.Driver == null || x.Driver.Vehicle == null ? null : x.Driver.Vehicle.RegistrationNumber, TotalFare = x.TotalFare, PaymentStatus = x.PaymentStatus, Status = x.Status });
    private static void SetTiming(IEnumerable<DispatchBoardItemDto> items) { var now = DateTimeOffset.UtcNow; foreach (var x in items) x.TimingState = x.Status is BookingStatus.DriverEnRoute or BookingStatus.DriverArrived or BookingStatus.PassengerOnBoard ? DispatchTimingState.Active : x.PickupDateTime < now ? DispatchTimingState.Overdue : x.PickupDateTime <= now.AddHours(1) ? DispatchTimingState.Approaching : DispatchTimingState.Scheduled; }
}

public sealed class ConflictDetectionService(LondonVIPDbContext db, ICompanyContext company) : IConflictDetectionService
{ public async Task<bool> HasConflictAsync(Guid bookingId, Guid driverId, CancellationToken token = default) { var pickup = await db.Bookings.Where(x => x.Id == bookingId && x.CompanyId == company.CompanyId).Select(x => (DateTimeOffset?)x.PickupDateTime).SingleOrDefaultAsync(token); if (!pickup.HasValue) return true; var start = pickup.Value.AddHours(-2); var end = pickup.Value.AddHours(2); return await db.Bookings.AsNoTracking().AnyAsync(x => x.CompanyId == company.CompanyId && x.Id != bookingId && x.DriverId == driverId && x.PickupDateTime >= start && x.PickupDateTime <= end && x.Status != BookingStatus.Completed && x.Status != BookingStatus.Cancelled && x.Status != BookingStatus.NoShow && x.Status != BookingStatus.UnableToComplete, token); } }

public sealed class AssignmentEngine(LondonVIPDbContext db, ICompanyContext company, IConflictDetectionService conflicts) : IAssignmentEngine
{ public async Task<DispatchValidationResult> ValidateAsync(Guid bookingId, Guid driverId, CancellationToken token = default) { var errors = new Dictionary<string, string[]>(); var booking = await db.Bookings.AsNoTracking().SingleOrDefaultAsync(x => x.Id == bookingId && x.CompanyId == company.CompanyId, token); if (booking is null) { errors["bookingId"] = ["Booking was not found."]; return new() { Errors = errors }; } var driver = await db.Drivers.AsNoTracking().Include(x => x.Vehicle).SingleOrDefaultAsync(x => x.Id == driverId && x.CompanyId == company.CompanyId, token); if (driver is null) { errors["driverId"] = ["Driver was not found."]; return new() { Errors = errors }; } var today = DateOnly.FromDateTime(DateTime.UtcNow); if (!driver.IsActive) errors["driver"] = ["Driver is inactive."]; if (driver.Vehicle is null) errors["vehicle"] = ["Driver has no assigned vehicle."]; else { if (!driver.Vehicle.IsActive) errors["vehicle"] = ["Vehicle is inactive."]; if (driver.Vehicle.VehicleType != booking.VehicleType) errors["vehicleType"] = ["Vehicle type is not compatible with the booking."]; if (driver.Vehicle.MOTExpiry is { } mot && mot < today) errors["mot"] = ["Vehicle MOT has expired."]; if (driver.Vehicle.InsuranceExpiry is { } insurance && insurance < today) errors["insurance"] = ["Vehicle insurance has expired."]; if (driver.Vehicle.PrivateHireLicenceExpiry is { } vpl && vpl < today) errors["vehicleLicence"] = ["Vehicle private-hire licence has expired."]; } if (driver.DrivingLicenceExpiry is { } licence && licence < today) errors["drivingLicence"] = ["Driver licence has expired."]; if (driver.PrivateHireLicenceExpiry is { } phl && phl < today) errors["privateHireLicence"] = ["Driver private-hire licence has expired."]; if (await conflicts.HasConflictAsync(bookingId, driverId, token)) errors["conflict"] = ["Driver has an overlapping operational booking."]; return new() { Errors = errors }; } }

public sealed class DriverAvailabilityService(LondonVIPDbContext db, ICompanyContext company) : IDriverAvailabilityService
{ private static readonly BookingStatus[] Active = [BookingStatus.Assigned, BookingStatus.DriverEnRoute, BookingStatus.DriverArrived, BookingStatus.PassengerOnBoard]; public async Task<List<DispatchDriverDto>> GetDriversAsync(CancellationToken token = default) { var today = DateTimeOffset.UtcNow.Date; var tomorrow = today.AddDays(1); var drivers = await db.Drivers.AsNoTracking().Where(x => x.CompanyId == company.CompanyId).Select(x => new { x.Id, x.FirstName, x.LastName, x.Phone, x.IsActive, x.AvailabilityStatus, x.VehicleId, VehicleType = x.Vehicle == null ? (VehicleType?)null : x.Vehicle.VehicleType, Vehicle = x.Vehicle == null ? null : x.Vehicle.Make + " " + x.Vehicle.Model, Registration = x.Vehicle == null ? null : x.Vehicle.RegistrationNumber, x.DrivingLicenceExpiry, x.PrivateHireLicenceExpiry, VehicleLicence = x.Vehicle == null ? null : x.Vehicle.PrivateHireLicenceExpiry, Mot = x.Vehicle == null ? null : x.Vehicle.MOTExpiry, Insurance = x.Vehicle == null ? null : x.Vehicle.InsuranceExpiry, Current = db.Bookings.Where(b => b.CompanyId == company.CompanyId && b.DriverId == x.Id && Active.Contains(b.Status)).Select(b => new { b.Id, b.BookingReference }).FirstOrDefault(), Jobs = db.Bookings.Count(b => b.CompanyId == company.CompanyId && b.DriverId == x.Id && b.PickupDateTime >= today && b.PickupDateTime < tomorrow) }).ToListAsync(token); var date = DateOnly.FromDateTime(DateTime.UtcNow); return drivers.Select(x => new DispatchDriverDto { DriverId = x.Id, Name = x.FirstName + " " + x.LastName, Phone = x.Phone, VehicleId = x.VehicleId, VehicleType = x.VehicleType, Vehicle = x.Vehicle, Registration = x.Registration, CurrentBookingId = x.Current?.Id, CurrentBookingReference = x.Current?.BookingReference, TodaysJobs = x.Jobs, CalculatedStatus = !x.IsActive ? "Suspended" : Expired(x.DrivingLicenceExpiry, x.PrivateHireLicenceExpiry, date) ? "Licence Expired" : Expired(x.VehicleLicence, x.Mot, x.Insurance, date) ? "Vehicle Expired" : x.Current != null ? "Busy" : x.AvailabilityStatus.ToString() }).OrderBy(x => x.Name).ToList(); } private static bool Expired(DateOnly? a, DateOnly? b, DateOnly today) => (a.HasValue && a < today) || (b.HasValue && b < today); private static bool Expired(DateOnly? a, DateOnly? b, DateOnly? c, DateOnly today) => (a.HasValue && a < today) || (b.HasValue && b < today) || (c.HasValue && c < today); }

public sealed class DispatchTimelineService(LondonVIPDbContext db, ICompanyContext company) : IDispatchTimelineService
{ public Task<List<DispatchTimelineItemDto>> GetAsync(Guid? bookingId, int limit, CancellationToken token = default) { limit = Math.Clamp(limit, 1, 100); var q = db.SecurityAuditEvents.AsNoTracking().Where(x => x.CompanyId == company.CompanyId && x.Category == "Dispatch"); if (bookingId.HasValue) q = q.Where(x => x.ResourceIdentifier == bookingId.Value.ToString()); return q.OrderByDescending(x => x.Timestamp).Take(limit).Select(x => new DispatchTimelineItemDto(x.Id, x.Timestamp, x.EventType, x.Description, x.UserId, x.ResourceIdentifier, x.CorrelationId)).ToListAsync(token); } }

public sealed class DriverRecommendationService(LondonVIPDbContext db, ICompanyContext company, IDriverAvailabilityService availability) : IDriverRecommendationService
{ public async Task<List<DriverRecommendationDto>> RecommendAsync(Guid bookingId, CancellationToken token = default) { var booking = await db.Bookings.AsNoTracking().Where(x => x.Id == bookingId && x.CompanyId == company.CompanyId).Select(x => new { x.PickupDateTime, x.VehicleType }).SingleOrDefaultAsync(token); if (booking is null) return []; var drivers = await availability.GetDriversAsync(token); var ids = drivers.Select(x => x.DriverId).ToArray(); var start = booking.PickupDateTime.AddHours(-2); var end = booking.PickupDateTime.AddHours(2); var conflicts = await db.Bookings.AsNoTracking().Where(x => x.CompanyId == company.CompanyId && x.Id != bookingId && x.DriverId != null && ids.Contains(x.DriverId.Value) && x.PickupDateTime >= start && x.PickupDateTime <= end && x.Status != BookingStatus.Completed && x.Status != BookingStatus.Cancelled && x.Status != BookingStatus.NoShow && x.Status != BookingStatus.UnableToComplete).Select(x => x.DriverId!.Value).Distinct().ToListAsync(token); return drivers.Where(x => x.CalculatedStatus == DriverAvailabilityStatus.Available.ToString() && x.VehicleId != null && x.VehicleType == booking.VehicleType && !conflicts.Contains(x.DriverId)).Select(x => new DriverRecommendationDto { DriverId = x.DriverId, DriverName = x.Name, Vehicle = x.Vehicle, Registration = x.Registration, Score = Math.Max(0, 100 - x.TodaysJobs * 10), TodaysJobs = x.TodaysJobs, VehicleSuitable = true, Reasons = ["Available", "Vehicle and compliance checks passed", $"{x.TodaysJobs} jobs today"] }).OrderByDescending(x => x.Score).ThenBy(x => x.DriverName).Take(5).ToList(); } }

public sealed class DispatchDashboardService(LondonVIPDbContext db, ICompanyContext company, IDispatchService dispatch, IDriverAvailabilityService availability, IDispatchTimelineService timeline) : IDispatchDashboardService
{
    public async Task<DispatchDashboardDto> GetAsync(CancellationToken token = default) { var now = DateTimeOffset.UtcNow; var today = new DateTimeOffset(now.Date, TimeSpan.Zero); var tomorrow = today.AddDays(1); var waiting = await dispatch.GetBookingsAsync(new() { Status = BookingStatus.Confirmed, PageSize = 10 }, token); var drivers = await availability.GetDriversAsync(token); var alerts = await GetAlertsAsync(token); var todayBookings = db.Bookings.AsNoTracking().Where(x => x.CompanyId == company.CompanyId && x.PickupDateTime >= today && x.PickupDateTime < tomorrow); var revenue = await todayBookings.Where(x => x.Status == BookingStatus.Completed).Select(x => x.TotalFare).ToListAsync(token); return new() { Kpis = new() { BookingsWaiting = waiting.Total, Assigned = await db.Bookings.CountAsync(x => x.CompanyId == company.CompanyId && x.Status == BookingStatus.Assigned, token), DriversAvailable = drivers.Count(x => x.CalculatedStatus == "Available"), DriversBusy = drivers.Count(x => x.CalculatedStatus == "Busy"), DriversOffline = drivers.Count(x => x.CalculatedStatus == "Offline"), AirportJobsToday = await todayBookings.CountAsync(x => x.IsAirportPickup, token), CorporateJobsToday = await todayBookings.CountAsync(x => x.CorporateAccountId != null, token), CompletedToday = await todayBookings.CountAsync(x => x.Status == BookingStatus.Completed, token), CancelledToday = await todayBookings.CountAsync(x => x.Status == BookingStatus.Cancelled, token), RevenueToday = revenue.Sum(), OutstandingAlerts = alerts.Count }, WaitingBookings = waiting.Items, Drivers = drivers, Timeline = await timeline.GetAsync(null, 30, token), Alerts = alerts }; }
    public async Task<List<DispatchAlertDto>> GetAlertsAsync(CancellationToken token = default)
    {
        var now = DateTimeOffset.UtcNow; var today = DateOnly.FromDateTime(now.UtcDateTime); var soon = today.AddDays(30); var alerts = new List<DispatchAlertDto>();
        alerts.AddRange(await db.Drivers.AsNoTracking().Where(x => x.CompanyId == company.CompanyId && x.IsActive && ((x.DrivingLicenceExpiry != null && x.DrivingLicenceExpiry <= soon) || (x.PrivateHireLicenceExpiry != null && x.PrivateHireLicenceExpiry <= soon))).Select(x => new DispatchAlertDto("DriverCompliance", x.DrivingLicenceExpiry < today ? "Critical" : "Warning", "Driver licence expiry", x.FirstName + " " + x.LastName, x.Id, x.DrivingLicenceExpiry == null ? null : new DateTimeOffset(x.DrivingLicenceExpiry.Value.ToDateTime(TimeOnly.MinValue), TimeSpan.Zero))).ToListAsync(token));
        alerts.AddRange(await db.Vehicles.AsNoTracking().Where(x => x.CompanyId == company.CompanyId && x.IsActive && ((x.MOTExpiry != null && x.MOTExpiry <= soon) || (x.InsuranceExpiry != null && x.InsuranceExpiry <= soon) || (x.PrivateHireLicenceExpiry != null && x.PrivateHireLicenceExpiry <= soon))).Select(x => new DispatchAlertDto("VehicleCompliance", "Warning", "Vehicle document expiry", x.RegistrationNumber, x.Id, null)).ToListAsync(token));
        alerts.AddRange(await db.CorporateAccounts.AsNoTracking().Where(x => x.CompanyId == company.CompanyId && x.IsOnHold).Select(x => new DispatchAlertDto("CorporateHold", "Warning", "Corporate account on hold", x.AccountName, x.Id, null)).ToListAsync(token));
        alerts.AddRange(await db.Notifications.AsNoTracking().Where(x => x.CompanyId == company.CompanyId && x.Status == NotificationStatus.Failed).Take(20).Select(x => new DispatchAlertDto("NotificationFailure", "Warning", x.Subject, x.Recipient, x.Id, null)).ToListAsync(token));
        alerts.AddRange(await db.Invoices.AsNoTracking().Where(x => x.CompanyId == company.CompanyId && x.BalanceDue > 0 && x.DueDate < now && x.Status != InvoiceStatus.Cancelled).Take(20).Select(x => new DispatchAlertDto("PaymentOverdue", "Critical", "Invoice overdue", x.InvoiceNumber, x.Id, x.DueDate)).ToListAsync(token));
        alerts.AddRange(await db.Quotations.AsNoTracking().Where(x => x.CompanyId == company.CompanyId && x.Status == QuoteStatus.Active && x.ExpiresAt > now).Take(20).Select(x => new DispatchAlertDto("OutstandingQuotation", "Information", "Quotation awaiting response", x.QuoteReference, x.Id, x.ExpiresAt)).ToListAsync(token));
        return alerts.OrderBy(x => x.Severity).Take(100).ToList();
    }
}
