using System.Security.Cryptography;
using System.Net.Http.Json;
using System.Text;
using System.Text.Json;
using LondonVIP.Infrastructure.Data;
using LondonVIP.Shared.Growth;
using LondonVIP.Shared.Integrations;
using LondonVIP.Shared.Models;
using LondonVIP.Shared.Tenancy;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;

namespace LondonVIP.Infrastructure.Growth;

public sealed class SocialOperationsService(LondonVIPDbContext db,ICompanyContext company,ISocialProviderRegistry providers,IDataProtectionProvider protection):ISocialOperationsService
{
 readonly IDataProtector protector=protection.CreateProtector("LondonVIP.Growth.SocialTokens.v1");
 public async Task<IReadOnlyList<ProviderConfigurationStatus>> StatusAsync(CancellationToken t=default){var connected=await db.SocialProviderConnections.AsNoTracking().Where(x=>x.CompanyId==company.CompanyId).ToListAsync(t);return providers.All.Select(x=>{var c=connected.FirstOrDefault(y=>y.Provider==x.Provider&&y.Status!=ProviderConnectionStatus.Disconnected);return new ProviderConfigurationStatus(x.Provider,x.IsConfigured,x.IsConfigured,c is not null,c?.Status.ToString()??(x.IsConfigured?"Ready to connect":"Provider Not Configured"),c?.LastError);}).ToList();}
 public async Task<OAuthStartResult> BeginOAuthAsync(MarketingChannel provider,string redirectUri,CancellationToken t=default){var p=providers.Find(provider);if(p is null||!p.IsConfigured)return new(false,null,"Provider Not Configured");if(!Uri.TryCreate(redirectUri,UriKind.Absolute,out _))return new(false,null,"A valid absolute redirect URI is required.");var state=Convert.ToHexString(RandomNumberGenerator.GetBytes(32));var verifier=Base64Url(RandomNumberGenerator.GetBytes(48));var challenge=Base64Url(SHA256.HashData(Encoding.ASCII.GetBytes(verifier)));db.OAuthAuthorizationStates.Add(new(){Id=Guid.NewGuid(),CompanyId=company.CompanyId,Provider=provider,StateHash=Hash(state),CodeVerifierProtected=protector.Protect(verifier),RedirectUri=redirectUri,ExpiresAt=DateTimeOffset.UtcNow.AddMinutes(10)});await db.SaveChangesAsync(t);return new(true,p.BuildAuthorizationUrl(state,challenge,redirectUri),"Authorization started.");}
 public async Task<ProviderOperationResult> CompleteOAuthAsync(MarketingChannel provider,OAuthCallbackRequest r,CancellationToken t=default){var state=await db.OAuthAuthorizationStates.SingleOrDefaultAsync(x=>x.CompanyId==company.CompanyId&&x.Provider==provider&&x.StateHash==Hash(r.State)&&x.ConsumedAt==null,t);if(state is null||state.ExpiresAt<DateTimeOffset.UtcNow||state.RedirectUri!=r.RedirectUri)return new(false,false,"OAuth state is invalid or expired.");var p=providers.Find(provider);if(p is null||!p.IsConfigured)return new(false,true,"Provider Not Configured");var token=await p.ExchangeCodeAsync(r.Code,protector.Unprotect(state.CodeVerifierProtected),r.RedirectUri,t);state.ConsumedAt=DateTimeOffset.UtcNow;if(!token.Success){await db.SaveChangesAsync(t);return new(false,token.NotConfigured,token.Message);}var account=token.AccountKey??provider.ToString();var connection=await db.SocialProviderConnections.SingleOrDefaultAsync(x=>x.CompanyId==company.CompanyId&&x.Provider==provider&&x.AccountKey==account,t)??new SocialProviderConnection{Id=Guid.NewGuid(),CompanyId=company.CompanyId,Provider=provider,AccountKey=account,CreatedAt=DateTimeOffset.UtcNow};if(db.Entry(connection).State==EntityState.Detached)db.Add(connection);connection.DisplayName=token.DisplayName??account;connection.ProtectedAccessToken=protector.Protect(token.AccessToken!);connection.ProtectedRefreshToken=token.RefreshToken is null?null:protector.Protect(token.RefreshToken);connection.TokenExpiresAt=token.ExpiresAt;connection.Scopes=token.Scopes??"";connection.Status=ProviderConnectionStatus.Connected;connection.LastError=null;connection.UpdatedAt=DateTimeOffset.UtcNow;await db.SaveChangesAsync(t);return new(true,false,"Provider connected.",connection.Id.ToString());}
 public async Task<bool> DisconnectAsync(Guid id,CancellationToken t=default){var x=await db.SocialProviderConnections.SingleOrDefaultAsync(x=>x.Id==id&&x.CompanyId==company.CompanyId,t);if(x is null)return false;x.Status=ProviderConnectionStatus.Disconnected;x.ProtectedAccessToken="";x.ProtectedRefreshToken=null;x.UpdatedAt=DateTimeOffset.UtcNow;await db.SaveChangesAsync(t);return true;}
 public async Task<ProviderOperationResult> QueueAsync(Guid id,bool immediate,CancellationToken t=default){var x=await db.SocialPosts.SingleOrDefaultAsync(x=>x.Id==id&&x.CompanyId==company.CompanyId,t);if(x is null)return new(false,false,"Post was not found.");if(providers.Find(x.Channel)?.IsConfigured!=true)return new(false,true,"Provider Not Configured");x.PublishStatus=PublishStatus.Queued;x.Status=GrowthStatus.Active;x.NextAttemptAt=immediate?DateTimeOffset.UtcNow:x.ScheduledAt??DateTimeOffset.UtcNow;await db.SaveChangesAsync(t);if(immediate)await ProcessDueAsync(t);return new(true,false,"Post queued.",x.ProviderReference);}
 public async Task<int> ProcessDueAsync(CancellationToken t=default){var now=DateTimeOffset.UtcNow;var posts=await db.SocialPosts.Where(x=>x.CompanyId==company.CompanyId&&x.PublishStatus==PublishStatus.Queued&&x.NextAttemptAt<=now).OrderBy(x=>x.NextAttemptAt).Take(50).ToListAsync(t);var count=0;foreach(var post in posts){var provider=providers.Find(post.Channel);var connection=await db.SocialProviderConnections.AsNoTracking().FirstOrDefaultAsync(x=>x.CompanyId==company.CompanyId&&x.Provider==post.Channel&&x.AccountKey==post.AccountKey&&x.Status==ProviderConnectionStatus.Connected,t);if(provider is null||!provider.IsConfigured||connection is null){post.PublishStatus=PublishStatus.Failed;post.LastError="Provider Not Configured or account not connected.";continue;}if(connection.TokenExpiresAt<=now){post.PublishStatus=PublishStatus.Failed;post.LastError="Provider token has expired.";continue;}connection.ProtectedAccessToken=protector.Unprotect(connection.ProtectedAccessToken);var ids=(post.MediaAssetIds??"").Split(',',StringSplitOptions.RemoveEmptyEntries).Select(x=>Guid.TryParse(x,out var id)?id:Guid.Empty).Where(x=>x!=Guid.Empty).ToList();var media=await db.MediaAssets.AsNoTracking().Where(x=>x.CompanyId==company.CompanyId&&ids.Contains(x.Id)&&!x.IsArchived).ToListAsync(t);post.PublishStatus=PublishStatus.Publishing;var result=await provider.PublishAsync(connection,post,media,t);post.AttemptCount++;if(result.Success){post.PublishStatus=PublishStatus.Published;post.Status=GrowthStatus.Completed;post.PublishedAt=now;post.ProviderReference=result.ProviderReference;post.LastError=null;count++;}else{post.LastError=result.Message;post.PublishStatus=post.AttemptCount>=5?PublishStatus.Failed:PublishStatus.Queued;post.NextAttemptAt=post.AttemptCount>=5?null:now.AddMinutes(Math.Pow(2,post.AttemptCount));}}await db.SaveChangesAsync(t);return count;}
 static string Hash(string value)=>Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(value)));static string Base64Url(byte[] value)=>Convert.ToBase64String(value).TrimEnd('=').Replace('+','-').Replace('/','_');
}

public sealed class NewsletterOptInService(LondonVIPDbContext db,ICompanyContext company):INewsletterOptInService
{
 public async Task<string?> SubscribeAsync(NewsletterRequest r,CancellationToken t=default){if(!System.Net.Mail.MailAddress.TryCreate(r.Email,out var mail))return null;var email=mail.Address.ToUpperInvariant();var x=await db.NewsletterSubscribers.SingleOrDefaultAsync(x=>x.CompanyId==company.CompanyId&&x.Email==email,t);if(x?.IsConfirmed==true&&x.UnsubscribedAt is null)return "confirmed";x??=new(){Id=Guid.NewGuid(),CompanyId=company.CompanyId,Email=email,SubscribedAt=DateTimeOffset.UtcNow};if(db.Entry(x).State==EntityState.Detached)db.Add(x);var token=Convert.ToHexString(RandomNumberGenerator.GetBytes(32));x.Name=r.Name;x.Lists=r.Lists??"General";x.Segments=r.Segments??"";x.ConfirmationTokenHash=Hash(token);x.ConfirmationExpiresAt=DateTimeOffset.UtcNow.AddHours(24);x.ConfirmationSendCount++;x.UnsubscribedAt=null;await db.SaveChangesAsync(t);return token;}
 public async Task<bool> ConfirmAsync(string token,CancellationToken t=default){var hash=Hash(token);var x=await db.NewsletterSubscribers.SingleOrDefaultAsync(x=>x.CompanyId==company.CompanyId&&x.ConfirmationTokenHash==hash,t);if(x is null||x.ConfirmationExpiresAt<DateTimeOffset.UtcNow)return false;if(x.IsConfirmed)return true;x.IsConfirmed=true;x.ConfirmedAt=DateTimeOffset.UtcNow;x.ConfirmationTokenHash="";await db.SaveChangesAsync(t);return true;}
 public async Task<string?> ResendAsync(string email,CancellationToken t=default){var x=await db.NewsletterSubscribers.SingleOrDefaultAsync(x=>x.CompanyId==company.CompanyId&&x.Email==email.ToUpper(),t);return x is null||x.IsConfirmed?null:await SubscribeAsync(new(x.Email,x.Name,x.Lists,x.Segments),t);}static string Hash(string x)=>Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(x)));
}

public sealed class AnalyticsService(LondonVIPDbContext db,ICompanyContext company):IAnalyticsService
{
 public async Task TrackAsync(AnalyticsTrackRequest r,CancellationToken t=default){var sessionHash=Hash(r.SessionKey);var session=await db.AnalyticsSessions.SingleOrDefaultAsync(x=>x.CompanyId==company.CompanyId&&x.SessionKeyHash==sessionHash,t)??new(){Id=Guid.NewGuid(),CompanyId=company.CompanyId,AnonymousIdHash=Hash(r.AnonymousId),SessionKeyHash=sessionHash,StartedAt=DateTimeOffset.UtcNow};if(db.Entry(session).State==EntityState.Detached)db.Add(session);session.Source=r.Source;session.Medium=r.Medium;session.Campaign=r.Campaign;session.ReferrerHost=r.ReferrerHost;session.LastSeenAt=DateTimeOffset.UtcNow;session.Events.Add(new(){Id=Guid.NewGuid(),CompanyId=company.CompanyId,Type=r.Type,Path=r.Path,Goal=r.Goal,Value=r.Value,QuotationId=r.QuotationId,BookingId=r.BookingId,OccurredAt=DateTimeOffset.UtcNow});await db.SaveChangesAsync(t);}
 public async Task<GrowthReportDto> ReportAsync(DateTimeOffset from,DateTimeOffset to,CancellationToken t=default){var events=db.AnalyticsEvents.AsNoTracking().Where(x=>x.CompanyId==company.CompanyId&&x.OccurredAt>=from&&x.OccurredAt<=to);var quoteStarts=await events.CountAsync(x=>x.Type==AnalyticsEventType.QuoteStarted,t);var quoteDone=await events.CountAsync(x=>x.Type==AnalyticsEventType.QuoteCompleted,t);var bookingStarts=await events.CountAsync(x=>x.Type==AnalyticsEventType.BookingStarted,t);var bookingDone=await events.CountAsync(x=>x.Type==AnalyticsEventType.BookingCompleted,t);var leads=await db.LeadCaptures.Where(x=>x.CompanyId==company.CompanyId&&x.CreatedAt>=from&&x.CreatedAt<=to).GroupBy(x=>x.Source).Select(g=>new{g.Key,Count=g.Count()}).ToDictionaryAsync(x=>x.Key,x=>x.Count,t);var campaigns=await db.MarketingCampaigns.Where(x=>x.CompanyId==company.CompanyId).ToListAsync(t);return new(campaigns.Sum(x=>x.Cost)==0?0:(campaigns.Sum(x=>x.Revenue)-campaigns.Sum(x=>x.Cost))/campaigns.Sum(x=>x.Cost)*100,quoteStarts==0?0:(decimal)quoteDone/quoteStarts*100,bookingStarts==0?0:(decimal)bookingDone/bookingStarts*100,leads,await db.SocialPosts.Where(x=>x.CompanyId==company.CompanyId).GroupBy(x=>x.Channel).Select(g=>new{Key=g.Key.ToString(),Count=g.Sum(x=>x.EngagementCount)}).ToDictionaryAsync(x=>x.Key,x=>x.Count,t),await db.CampaignDeliveries.CountAsync(x=>x.CompanyId==company.CompanyId&&x.Status==CampaignDeliveryStatus.Delivered,t),campaigns.Sum(x=>x.OpenCount),await db.CrmReviews.CountAsync(x=>x.CompanyId==company.CompanyId,t),await db.Referrals.CountAsync(x=>x.CompanyId==company.CompanyId&&x.Status>=ReferralStatus.Qualified,t),await db.LoyaltyAccounts.CountAsync(x=>x.CompanyId==company.CompanyId,t));}static string Hash(string x)=>Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(x)));
}

public sealed class AiMarketingService(IConfiguration configuration,IHttpClientFactory clients,LondonVIPDbContext db,ICompanyContext company):IAiMarketingService
{
 public async Task<AiMarketingResult> GenerateAsync(AiMarketingRequest r,CancellationToken t=default){var endpoint=configuration["Growth:AI:Endpoint"];var key=configuration["Growth:AI:ApiKey"];var model=configuration["Growth:AI:Model"];if(string.IsNullOrWhiteSpace(endpoint)||string.IsNullOrWhiteSpace(key)||string.IsNullOrWhiteSpace(model))return new(false,true,"Provider Not Configured");using var request=new HttpRequestMessage(HttpMethod.Post,endpoint);request.Headers.Authorization=new("Bearer",key);request.Content=JsonContent.Create(new{model,messages=new[]{new{role="system",content="You are the compliant marketing assistant for a premium London private-hire operator. Never invent prices, guarantees or regulatory claims."},new{role="user",content=$"Create {r.GenerationType}. Brief: {r.Brief}. Tone: {r.Tone}. Audience: {r.Audience}. Keywords: {r.Keywords}."}}});using var response=await clients.CreateClient("LondonVIP.Integrations").SendAsync(request,t);var body=await response.Content.ReadAsStringAsync(t);if(!response.IsSuccessStatusCode)return new(false,false,$"AI provider returned {(int)response.StatusCode}.");using var json=JsonDocument.Parse(body);var output=json.RootElement.GetProperty("choices")[0].GetProperty("message").GetProperty("content").GetString()??"";db.AiMarketingGenerations.Add(new(){Id=Guid.NewGuid(),CompanyId=company.CompanyId,GenerationType=r.GenerationType,Prompt=r.Brief,Output=output,ProviderKey=new Uri(endpoint).Host,Model=model,Status="Completed",CreatedAt=DateTimeOffset.UtcNow});await db.SaveChangesAsync(t);return new(true,false,"Generated.",output);}
}

public sealed class CampaignEngine(LondonVIPDbContext db,ICompanyContext company):ICampaignEngine
{
 public async Task<bool> CommandAsync(Guid id,string action,CancellationToken t=default){var x=await db.MarketingCampaigns.SingleOrDefaultAsync(x=>x.Id==id&&x.CompanyId==company.CompanyId,t);if(x is null)return false;switch(action.ToLowerInvariant()){case "schedule":if(x.ScheduledAt is null)throw new InvalidOperationException("A schedule date is required.");x.Status=GrowthStatus.Active;break;case "pause":if(x.Status!=GrowthStatus.Active)throw new InvalidOperationException("Only active campaigns can be paused.");x.Status=GrowthStatus.Paused;break;case "resume":if(x.Status!=GrowthStatus.Paused)throw new InvalidOperationException("Only paused campaigns can resume.");x.Status=GrowthStatus.Active;break;case "cancel":x.Status=GrowthStatus.Cancelled;break;case "archive":x.Status=GrowthStatus.Completed;break;default:throw new InvalidOperationException("Campaign action is invalid.");}x.UpdatedAt=DateTimeOffset.UtcNow;await db.SaveChangesAsync(t);return true;}
 public async Task<int> ProcessDueAsync(CancellationToken t=default){var now=DateTimeOffset.UtcNow;var campaigns=await db.MarketingCampaigns.Where(x=>x.CompanyId==company.CompanyId&&x.Status==GrowthStatus.Active&&x.ScheduledAt<=now).Take(20).ToListAsync(t);var created=0;foreach(var campaign in campaigns){if(!await db.CampaignDeliveries.AnyAsync(x=>x.CompanyId==company.CompanyId&&x.MarketingCampaignId==campaign.Id,t)){var audience=await db.NewsletterSubscribers.AsNoTracking().Where(x=>x.CompanyId==company.CompanyId&&x.IsConfirmed&&x.UnsubscribedAt==null).Select(x=>x.Email).Take(10000).ToListAsync(t);foreach(var recipient in audience){db.CampaignDeliveries.Add(new(){Id=Guid.NewGuid(),CompanyId=company.CompanyId,MarketingCampaignId=campaign.Id,Recipient=recipient,RecipientType="NewsletterSubscriber",Status=CampaignDeliveryStatus.Pending,NextAttemptAt=now,CreatedAt=now});created++;}}campaign.Status=GrowthStatus.Completed;campaign.UpdatedAt=now;}await db.SaveChangesAsync(t);return created;}
}
