using System.Net.Http.Headers;
using System.Net.Http.Json;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using LondonVIP.Shared.Growth;
using LondonVIP.Shared.Models;
using Microsoft.Extensions.Configuration;

namespace LondonVIP.Infrastructure.Growth;

public sealed class SocialProviderRegistry : ISocialProviderRegistry
{
    public SocialProviderRegistry(IConfiguration configuration,IHttpClientFactory clients)
    {
        All=new[]{MarketingChannel.Facebook,MarketingChannel.Instagram,MarketingChannel.LinkedIn,MarketingChannel.GoogleBusiness,MarketingChannel.X,MarketingChannel.TikTok,MarketingChannel.YouTube}
            .Select(x=>(ISocialProvider)new ConfiguredSocialProvider(x,configuration,clients)).ToList();
    }
    public IReadOnlyList<ISocialProvider> All { get; }
    public ISocialProvider? Find(MarketingChannel provider)=>All.FirstOrDefault(x=>x.Provider==provider);
}

public sealed class ConfiguredSocialProvider(MarketingChannel provider,IConfiguration configuration,IHttpClientFactory clients):ISocialProvider
{
    readonly IConfigurationSection config=configuration.GetSection($"Growth:Social:{provider}");
    public MarketingChannel Provider=>provider;
    public bool IsConfigured=>config.GetValue<bool>("Enabled")&&!string.IsNullOrWhiteSpace(config["ClientId"])&&!string.IsNullOrWhiteSpace(config["ClientSecret"]);
    string AuthorizationEndpoint=>config["AuthorizationEndpoint"]??Defaults(provider).Authorization;
    string TokenEndpoint=>config["TokenEndpoint"]??Defaults(provider).Token;
    string PublishEndpoint=>config["PublishEndpoint"]??Defaults(provider).Publish;
    string Scopes=>config["Scopes"]??Defaults(provider).Scopes;
    HttpClient Client=>clients.CreateClient("LondonVIP.Integrations");
    public string BuildAuthorizationUrl(string state,string challenge,string redirectUri){var values=new Dictionary<string,string?>{{"client_id",config["ClientId"]},{"redirect_uri",redirectUri},{"response_type","code"},{"scope",Scopes},{"state",state},{"code_challenge",challenge},{"code_challenge_method","S256"},{"access_type",provider==MarketingChannel.GoogleBusiness||provider==MarketingChannel.YouTube?"offline":null}};return AuthorizationEndpoint+"?"+string.Join('&',values.Where(x=>x.Value is not null).Select(x=>$"{Uri.EscapeDataString(x.Key)}={Uri.EscapeDataString(x.Value!)}"));}
    public async Task<OAuthTokenResult> ExchangeCodeAsync(string code,string verifier,string redirectUri,CancellationToken token=default){if(!IsConfigured)return new(false,true,"Provider Not Configured");using var response=await Client.PostAsync(TokenEndpoint,new FormUrlEncodedContent(new Dictionary<string,string>{{"grant_type","authorization_code"},{"code",code},{"client_id",config["ClientId"]!},{"client_secret",config["ClientSecret"]!},{"redirect_uri",redirectUri},{"code_verifier",verifier}}),token);return await Token(response,token);}
    public async Task<ProviderOperationResult> RefreshAsync(SocialProviderConnection connection,CancellationToken token=default){if(!IsConfigured)return new(false,true,"Provider Not Configured");if(string.IsNullOrWhiteSpace(connection.ProtectedRefreshToken))return new(false,false,"No refresh token is available.");return new(false,false,"Token refresh must be performed through SocialOperationsService.");}
    public async Task<ProviderOperationResult> PublishAsync(SocialProviderConnection connection,SocialPost post,IReadOnlyList<MediaAsset> media,CancellationToken token=default){if(!IsConfigured)return new(false,true,"Provider Not Configured");if(string.IsNullOrWhiteSpace(PublishEndpoint))return new(false,true,"Provider publishing endpoint is not configured.");using var request=new HttpRequestMessage(HttpMethod.Post,Expand(PublishEndpoint,connection.AccountKey));request.Headers.Authorization=new AuthenticationHeaderValue("Bearer",connection.ProtectedAccessToken);request.Content=JsonContent.Create(Payload(post,media,connection.AccountKey));using var response=await Client.SendAsync(request,token);var body=await response.Content.ReadAsStringAsync(token);if(!response.IsSuccessStatusCode)return new(false,false,$"Provider returned {(int)response.StatusCode}: {Safe(body)}");using var json=JsonDocument.Parse(string.IsNullOrWhiteSpace(body)?"{}":body);var id=FindId(json.RootElement);return new(true,false,"Published.",id);}
    public Task<bool> ValidateWebhookAsync(string payload,string? signature,CancellationToken token=default){var secret=config["WebhookSecret"];if(string.IsNullOrWhiteSpace(secret)||string.IsNullOrWhiteSpace(signature))return Task.FromResult(false);var expected=Convert.ToHexString(HMACSHA256.HashData(Encoding.UTF8.GetBytes(secret),Encoding.UTF8.GetBytes(payload))).ToLowerInvariant();var supplied=signature.Replace("sha256=","",StringComparison.OrdinalIgnoreCase).ToLowerInvariant();return Task.FromResult(CryptographicOperations.FixedTimeEquals(Encoding.ASCII.GetBytes(expected),Encoding.ASCII.GetBytes(supplied)));}
    async Task<OAuthTokenResult> Token(HttpResponseMessage response,CancellationToken token){var body=await response.Content.ReadAsStringAsync(token);if(!response.IsSuccessStatusCode)return new(false,false,$"OAuth provider returned {(int)response.StatusCode}: {Safe(body)}");using var json=JsonDocument.Parse(body);var root=json.RootElement;var access=Get(root,"access_token");if(string.IsNullOrWhiteSpace(access))return new(false,false,"OAuth response did not include an access token.");var seconds=int.TryParse(Get(root,"expires_in"),out var value)?value:3600;return new(true,false,"Connected.",access,Get(root,"refresh_token"),DateTimeOffset.UtcNow.AddSeconds(seconds),config["AccountKey"]??Get(root,"user_id")??Get(root,"id"),config["DisplayName"]??provider.ToString(),Get(root,"scope")??Scopes);}
    object Payload(SocialPost post,IReadOnlyList<MediaAsset> media,string account)=>provider switch{MarketingChannel.Facebook=>new{message=post.Body,attached_media=media.Select(x=>new{media_fbid=x.CdnUrl??x.StoragePath})},MarketingChannel.Instagram=>new{caption=post.Body,image_url=media.FirstOrDefault()?.CdnUrl},MarketingChannel.LinkedIn=>new{author=account,commentary=post.Body,visibility="PUBLIC",distribution=new{feedDistribution="MAIN_FEED",targetEntities=Array.Empty<string>()},lifecycleState="PUBLISHED"},MarketingChannel.GoogleBusiness=>new{languageCode="en-GB",summary=post.Body,topicType="STANDARD",media=media.Select(x=>new{mediaFormat=x.ContentType.StartsWith("video/")?"VIDEO":"PHOTO",sourceUrl=x.CdnUrl})},MarketingChannel.X=>new{text=post.Body,media=media.Count==0?null:new{media_ids=media.Select(x=>x.CdnUrl??x.StoragePath)}},MarketingChannel.TikTok=>new{post_info=new{title=post.Body,privacy_level="PUBLIC_TO_EVERYONE"},source_info=new{source="PULL_FROM_URL",video_url=media.FirstOrDefault()?.CdnUrl}},MarketingChannel.YouTube=>new{snippet=new{title=post.Body.Length>100?post.Body[..100]:post.Body,description=post.Body},status=new{privacyStatus="public"}},_=>new{text=post.Body}};
    static string Expand(string value,string account)=>value.Replace("{accountId}",Uri.EscapeDataString(account),StringComparison.Ordinal).Replace("{locationId}",Uri.EscapeDataString(account),StringComparison.Ordinal);
    static string? Get(JsonElement x,string name)=>x.TryGetProperty(name,out var v)?v.ToString():null;static string? FindId(JsonElement x)=>Get(x,"id")??Get(x,"name")??Get(x,"data");static string Safe(string x)=>x.Length>500?x[..500]:x;
    static (string Authorization,string Token,string Publish,string Scopes) Defaults(MarketingChannel x)=>x switch{MarketingChannel.Facebook or MarketingChannel.Instagram=>("https://www.facebook.com/v23.0/dialog/oauth","https://graph.facebook.com/v23.0/oauth/access_token","https://graph.facebook.com/v23.0/{accountId}/feed","pages_manage_posts pages_read_engagement instagram_basic instagram_content_publish"),MarketingChannel.LinkedIn=>("https://www.linkedin.com/oauth/v2/authorization","https://www.linkedin.com/oauth/v2/accessToken","https://api.linkedin.com/rest/posts","w_organization_social r_organization_social"),MarketingChannel.GoogleBusiness=>("https://accounts.google.com/o/oauth2/v2/auth","https://oauth2.googleapis.com/token","https://mybusiness.googleapis.com/v4/accounts/{accountId}/locations/{locationId}/localPosts","https://www.googleapis.com/auth/business.manage"),MarketingChannel.X=>("https://twitter.com/i/oauth2/authorize","https://api.x.com/2/oauth2/token","https://api.x.com/2/tweets","tweet.read tweet.write users.read offline.access"),MarketingChannel.TikTok=>("https://www.tiktok.com/v2/auth/authorize/","https://open.tiktokapis.com/v2/oauth/token/","https://open.tiktokapis.com/v2/post/publish/video/init/","user.info.basic video.publish"),MarketingChannel.YouTube=>("https://accounts.google.com/o/oauth2/v2/auth","https://oauth2.googleapis.com/token","https://www.googleapis.com/upload/youtube/v3/videos?part=snippet,status","https://www.googleapis.com/auth/youtube.upload"),_=>("","","","")};
}
