using LondonVIP.Infrastructure.Accounting;
using LondonVIP.Infrastructure.Data;
using LondonVIP.Infrastructure.Security;
using LondonVIP.Shared.Accounting;
using LondonVIP.Shared.Models;
using LondonVIP.Shared.Security;
using LondonVIP.Shared.Tenancy;
using Microsoft.EntityFrameworkCore;
using Models = LondonVIP.Shared.Models;
using LondonVIP.Shared.Workflows;

namespace LondonVIP.Api;

public static class AccountingEndpoints
{
 public static IEndpointRouteBuilder MapAccountingEndpoints(this IEndpointRouteBuilder e){var g=e.MapGroup("/api/finance").RequireAuthorization(SecurityPolicies.FinanceOperations).RequireRateLimiting("operations");g.MapGet("",(IAccountingReportService s,CancellationToken t)=>s.DashboardAsync(t));g.MapGet("/accounts",Accounts);g.MapPost("/accounts",CreateAccount);g.MapGet("/journals",Journals);g.MapPost("/journals",CreateJournal);g.MapPost("/journals/{id:guid}/post",PostJournal);g.MapGet("/trial-balance",TrialBalance);g.MapGet("/vat",Vat);g.MapGet("/reports/profit-loss",ProfitLoss);g.MapGet("/suppliers",Suppliers);g.MapPost("/suppliers",CreateSupplier);g.MapGet("/supplier-invoices",SupplierInvoices);g.MapPost("/supplier-invoices",CreateSupplierInvoice);g.MapPatch("/supplier-invoices/{id:guid}/status",SupplierInvoiceStatus);g.MapGet("/expenses",Expenses);g.MapPost("/expenses",CreateExpense);g.MapPatch("/expenses/{id:guid}/status",ExpenseStatus);g.MapGet("/bank/accounts",BankAccounts);g.MapPost("/bank/accounts",CreateBankAccount);g.MapGet("/bank/transactions",BankTransactions);g.MapPost("/bank/transactions",CreateBankTransaction);g.MapPost("/bank/transfers",CreateBankTransfer);g.MapGet("/budgets",Budgets);g.MapPost("/budgets",CreateBudget);g.MapGet("/driver-settlements",Settlements);g.MapPost("/driver-settlements",CreateSettlement);e.MapAccountingCompletionEndpoints();return e;}
 static Task<List<object>> Accounts(LondonVIPDbContext db,ICompanyContext c,CancellationToken t)=>db.LedgerAccounts.AsNoTracking().Where(x=>x.CompanyId==c.CompanyId).OrderBy(x=>x.Code).Select(x=>(object)new{x.Id,x.Code,x.Name,x.Type,x.OpeningBalance,x.AllowPosting,x.IsActive}).ToListAsync(t);
 static async Task<IResult>CreateAccount(LedgerAccount r,LondonVIPDbContext db,ICompanyContext c,IAuditService a,CancellationToken t){if(string.IsNullOrWhiteSpace(r.Code)||string.IsNullOrWhiteSpace(r.Name))return Results.BadRequest();var x=new LedgerAccount{Id=Guid.NewGuid(),CompanyId=c.CompanyId,Code=r.Code.Trim(),Name=r.Name.Trim(),Type=r.Type,ParentId=r.ParentId,AllowPosting=r.AllowPosting,IsActive=r.IsActive,OpeningBalance=r.OpeningBalance,CreatedAt=DateTimeOffset.UtcNow};db.Add(x);await db.SaveChangesAsync(t);await Audit(a,c,"LedgerAccountCreated",x.Id,t);return Results.Created($"/api/finance/accounts/{x.Id}",new{x.Id});}
 static Task<List<object>> Journals(LondonVIPDbContext db,ICompanyContext c,CancellationToken t)=>db.Journals.AsNoTracking().Where(x=>x.CompanyId==c.CompanyId).OrderByDescending(x=>x.JournalDate).Select(x=>(object)new{x.Id,x.Reference,x.JournalDate,x.Description,x.Status,Debit=x.Entries.Sum(e=>e.Debit),Credit=x.Entries.Sum(e=>e.Credit)}).ToListAsync(t);
 static async Task<IResult>CreateJournal(JournalRequest r,IJournalService s,IAuditService a,ICompanyContext c,CancellationToken t){try{var x=await s.CreateAsync(r,t);await Audit(a,c,"JournalCreated",x.Id,t);return Results.Created($"/api/finance/journals/{x.Id}",x);}catch(InvalidOperationException ex){return Results.BadRequest(new{ex.Message});}}
 static async Task<IResult>PostJournal(Guid id,IJournalService s,IAuditService a,ICompanyContext c,CancellationToken t){try{var x=await s.PostAsync(id,t);if(x is null)return Results.NotFound();await Audit(a,c,"JournalPosted",id,t);return Results.Ok(x);}catch(InvalidOperationException ex){return Results.BadRequest(new{ex.Message});}}
 static Task<TrialBalanceDto>TrialBalance(DateOnly from,DateOnly to,IJournalService s,CancellationToken t)=>s.TrialBalanceAsync(from,to,t);static Task<VatReportDto>Vat(DateOnly from,DateOnly to,IAccountingReportService s,CancellationToken t)=>s.VatAsync(from,to,t);static Task<ProfitAndLossDto>ProfitLoss(DateOnly from,DateOnly to,IAccountingReportService s,CancellationToken t)=>s.ProfitAndLossAsync(from,to,t);
 static Task<List<object>>Suppliers(LondonVIPDbContext db,ICompanyContext c,CancellationToken t)=>db.Suppliers.AsNoTracking().Where(x=>x.CompanyId==c.CompanyId).OrderBy(x=>x.Name).Select(x=>(object)new{x.Id,x.SupplierNumber,x.Name,x.ContactName,x.Email,x.Phone,x.PaymentTermsDays,x.IsActive,Balance=db.SupplierInvoices.Where(i=>i.CompanyId==c.CompanyId&&i.SupplierId==x.Id&&i.Status!=PayableStatus.Cancelled).Sum(i=>(decimal?)(i.TotalAmount-i.AmountPaid))??0}).ToListAsync(t);
 static async Task<IResult>CreateSupplier(SupplierRequest r,LondonVIPDbContext db,ICompanyContext c,IAuditService a,CancellationToken t){if(string.IsNullOrWhiteSpace(r.SupplierNumber)||string.IsNullOrWhiteSpace(r.Name)||r.PaymentTermsDays<0)return Results.BadRequest();var x=new Supplier{Id=Guid.NewGuid(),CompanyId=c.CompanyId,SupplierNumber=r.SupplierNumber.Trim(),Name=r.Name.Trim(),ContactName=r.ContactName,Email=r.Email,Phone=r.Phone,Address=r.Address,VatNumber=r.VatNumber,PaymentTermsDays=r.PaymentTermsDays,IsActive=r.IsActive,CreatedAt=DateTimeOffset.UtcNow};db.Add(x);await db.SaveChangesAsync(t);await Audit(a,c,"SupplierCreated",x.Id,t);return Results.Created($"/api/finance/suppliers/{x.Id}",new{x.Id});}
 static Task<List<object>>SupplierInvoices(LondonVIPDbContext db,ICompanyContext c,CancellationToken t)=>db.SupplierInvoices.AsNoTracking().Where(x=>x.CompanyId==c.CompanyId).OrderByDescending(x=>x.InvoiceDate).Select(x=>(object)new{x.Id,x.SupplierId,Supplier=x.Supplier.Name,x.SupplierReference,x.InvoiceDate,x.DueDate,x.Status,x.NetAmount,x.VatAmount,x.TotalAmount,x.AmountPaid,Balance=x.TotalAmount-x.AmountPaid}).ToListAsync(t);
 static async Task<IResult>CreateSupplierInvoice(SupplierInvoiceRequest r,LondonVIPDbContext db,ICompanyContext c,IAuditService a,CancellationToken t){if(r.NetAmount<0||r.VatAmount<0||r.DueDate<r.InvoiceDate||!await db.Suppliers.AnyAsync(x=>x.CompanyId==c.CompanyId&&x.Id==r.SupplierId&&x.IsActive,t))return Results.BadRequest();var x=new SupplierInvoice{Id=Guid.NewGuid(),CompanyId=c.CompanyId,SupplierId=r.SupplierId,SupplierReference=r.SupplierReference.Trim(),InvoiceDate=r.InvoiceDate,DueDate=r.DueDate,Status=PayableStatus.Draft,NetAmount=r.NetAmount,VatAmount=r.VatAmount,TotalAmount=r.NetAmount+r.VatAmount,Notes=r.Notes,CreatedAt=DateTimeOffset.UtcNow};db.Add(x);await db.SaveChangesAsync(t);await Audit(a,c,"SupplierInvoiceCreated",x.Id,t);return Results.Created($"/api/finance/supplier-invoices/{x.Id}",new{x.Id});}
 static Task<List<object>>Expenses(LondonVIPDbContext db,ICompanyContext c,CancellationToken t)=>db.Expenses.AsNoTracking().Where(x=>x.CompanyId==c.CompanyId).OrderByDescending(x=>x.ExpenseDate).Select(x=>(object)new{x.Id,x.Reference,x.Category,x.Description,x.ExpenseDate,x.NetAmount,x.VatAmount,x.TotalAmount,x.Status,x.DriverId,x.VehicleId,x.ReceiptStoragePath}).ToListAsync(t);
 static async Task<IResult>CreateExpense(ExpenseRequest r,LondonVIPDbContext db,ICompanyContext c,IAuditService a,CancellationToken t){if(string.IsNullOrWhiteSpace(r.Reference)||!ExpenseCategories.All.Contains(r.Category.Trim())||r.NetAmount<0||r.VatAmount<0)return Results.BadRequest();if(r.DriverId.HasValue&&!await db.Drivers.AnyAsync(x=>x.CompanyId==c.CompanyId&&x.Id==r.DriverId,t)||r.VehicleId.HasValue&&!await db.Vehicles.AnyAsync(x=>x.CompanyId==c.CompanyId&&x.Id==r.VehicleId,t))return Results.NotFound();var x=new Expense{Id=Guid.NewGuid(),CompanyId=c.CompanyId,Reference=r.Reference.Trim(),Category=r.Category.Trim(),Description=r.Description,ExpenseDate=r.ExpenseDate,NetAmount=r.NetAmount,VatAmount=r.VatAmount,TotalAmount=r.NetAmount+r.VatAmount,Status=Models.ExpenseStatus.Submitted,DriverId=r.DriverId,VehicleId=r.VehicleId,ReceiptStoragePath=r.ReceiptStoragePath,Department=r.Department,CostCentre=r.CostCentre,CreatedAt=DateTimeOffset.UtcNow};db.Add(x);await db.SaveChangesAsync(t);await Audit(a,c,"ExpenseSubmitted",x.Id,t);return Results.Created($"/api/finance/expenses/{x.Id}",new{x.Id});}
 static async Task<IResult>ExpenseStatus(Guid id,Models.ExpenseStatus status,LondonVIPDbContext db,ICompanyContext c,IAuditService a,IBusinessEventPublisher events,CancellationToken t){var x=await db.Expenses.SingleOrDefaultAsync(x=>x.CompanyId==c.CompanyId&&x.Id==id,t);if(x is null)return Results.NotFound();x.Status=status;await db.SaveChangesAsync(t);await Audit(a,c,"ExpenseStatusChanged",id,t);if(status==Models.ExpenseStatus.Approved)await events.PublishAsync(new(BusinessEventTypes.ExpenseApproved,"Expense",x.Id,System.Text.Json.JsonSerializer.Serialize(new{x.TotalAmount}),x.Id.ToString()),t);return Results.Ok();}
 static async Task<IResult>SupplierInvoiceStatus(Guid id,PayableStatus status,LondonVIPDbContext db,ICompanyContext c,IAuditService a,IBusinessEventPublisher events,CancellationToken t){var x=await db.SupplierInvoices.SingleOrDefaultAsync(x=>x.CompanyId==c.CompanyId&&x.Id==id,t);if(x is null)return Results.NotFound();x.Status=status;await db.SaveChangesAsync(t);await Audit(a,c,"SupplierInvoiceStatusChanged",id,t);if(status==PayableStatus.Approved)await events.PublishAsync(new(BusinessEventTypes.SupplierInvoiceApproved,"SupplierInvoice",x.Id,System.Text.Json.JsonSerializer.Serialize(new{x.TotalAmount}),x.Id.ToString()),t);return Results.Ok();}
 static Task<List<object>>BankAccounts(LondonVIPDbContext db,ICompanyContext c,CancellationToken t)=>db.BankAccounts.AsNoTracking().Where(x=>x.CompanyId==c.CompanyId).Select(x=>(object)new{x.Id,x.Name,x.CurrencyCode,x.SortCodeMasked,x.AccountNumberMasked,x.OpeningBalance,x.IsActive}).ToListAsync(t);
 static async Task<IResult>CreateBankAccount(BankAccount r,LondonVIPDbContext db,ICompanyContext c,IAuditService a,CancellationToken t){if(string.IsNullOrWhiteSpace(r.Name)||r.CurrencyCode.Length!=3)return Results.BadRequest();var x=new BankAccount{Id=Guid.NewGuid(),CompanyId=c.CompanyId,Name=r.Name.Trim(),CurrencyCode=r.CurrencyCode.ToUpperInvariant(),SortCodeMasked=r.SortCodeMasked,AccountNumberMasked=r.AccountNumberMasked,OpeningBalance=r.OpeningBalance,IsActive=r.IsActive};db.Add(x);await db.SaveChangesAsync(t);await Audit(a,c,"BankAccountCreated",x.Id,t);return Results.Created($"/api/finance/bank/accounts/{x.Id}",new{x.Id});}
 static Task<List<object>>BankTransactions(LondonVIPDbContext db,ICompanyContext c,CancellationToken t)=>db.BankTransactions.AsNoTracking().Where(x=>x.CompanyId==c.CompanyId).OrderByDescending(x=>x.TransactionDate).Select(x=>(object)new{x.Id,x.BankAccountId,x.TransactionDate,x.Type,x.Reference,x.Description,x.Amount,x.ReconciliationStatus,x.MatchedPaymentId,x.MatchedSupplierInvoiceId}).ToListAsync(t);
 static async Task<IResult>CreateBankTransaction(BankTransaction r,LondonVIPDbContext db,ICompanyContext c,IAuditService a,CancellationToken t){if(r.Amount==0||!await db.BankAccounts.AnyAsync(x=>x.CompanyId==c.CompanyId&&x.Id==r.BankAccountId&&x.IsActive,t))return Results.BadRequest();var x=new BankTransaction{Id=Guid.NewGuid(),CompanyId=c.CompanyId,BankAccountId=r.BankAccountId,TransactionDate=r.TransactionDate,Type=r.Type,Reference=r.Reference,Description=r.Description,Amount=r.Amount,ReconciliationStatus=ReconciliationStatus.Unmatched,ImportedStatementReference=r.ImportedStatementReference,CreatedAt=DateTimeOffset.UtcNow};db.Add(x);await db.SaveChangesAsync(t);await Audit(a,c,"BankTransactionCreated",x.Id,t);return Results.Created($"/api/finance/bank/transactions/{x.Id}",new{x.Id});}
 static async Task<IResult>CreateBankTransfer(BankTransferRequest r,LondonVIPDbContext db,ICompanyContext c,IAuditService a,CancellationToken t){if(r.FromBankAccountId==r.ToBankAccountId||r.Amount<=0||string.IsNullOrWhiteSpace(r.Reference))return Results.BadRequest();var accounts=await db.BankAccounts.Where(x=>x.CompanyId==c.CompanyId&&x.IsActive&&(x.Id==r.FromBankAccountId||x.Id==r.ToBankAccountId)).Select(x=>x.Id).ToListAsync(t);if(accounts.Count!=2)return Results.NotFound();await using var transaction=await db.Database.BeginTransactionAsync(t);var correlation=Guid.NewGuid().ToString("N");db.BankTransactions.AddRange(new BankTransaction{Id=Guid.NewGuid(),CompanyId=c.CompanyId,BankAccountId=r.FromBankAccountId,TransactionDate=r.TransferDate,Type=BankTransactionType.Transfer,Reference=r.Reference.Trim(),Description=r.Description,Amount=-r.Amount,ReconciliationStatus=ReconciliationStatus.Unmatched,ImportedStatementReference=correlation,CreatedAt=DateTimeOffset.UtcNow},new BankTransaction{Id=Guid.NewGuid(),CompanyId=c.CompanyId,BankAccountId=r.ToBankAccountId,TransactionDate=r.TransferDate,Type=BankTransactionType.Transfer,Reference=r.Reference.Trim(),Description=r.Description,Amount=r.Amount,ReconciliationStatus=ReconciliationStatus.Unmatched,ImportedStatementReference=correlation,CreatedAt=DateTimeOffset.UtcNow});await db.SaveChangesAsync(t);await transaction.CommitAsync(t);await Audit(a,c,"BankTransferCreated",Guid.Empty,t);return Results.Created("/api/finance/bank/transactions",new{CorrelationId=correlation});}
 static Task<List<object>>Budgets(LondonVIPDbContext db,ICompanyContext c,CancellationToken t)=>db.Budgets.AsNoTracking().Where(x=>x.CompanyId==c.CompanyId).Select(x=>(object)new{x.Id,x.FiscalYearId,x.Department,x.CostCentre,x.LedgerAccountId,x.Amount,x.ForecastAmount}).ToListAsync(t);
 static async Task<IResult>CreateBudget(Budget r,LondonVIPDbContext db,ICompanyContext c,IAuditService a,CancellationToken t){if(r.Amount<0||r.ForecastAmount<0)return Results.BadRequest();var x=new Budget{Id=Guid.NewGuid(),CompanyId=c.CompanyId,FiscalYearId=r.FiscalYearId,Department=r.Department,CostCentre=r.CostCentre,LedgerAccountId=r.LedgerAccountId,Amount=r.Amount,ForecastAmount=r.ForecastAmount};db.Add(x);await db.SaveChangesAsync(t);await Audit(a,c,"BudgetCreated",x.Id,t);return Results.Created($"/api/finance/budgets/{x.Id}",new{x.Id});}
 static Task<List<object>>Settlements(LondonVIPDbContext db,ICompanyContext c,CancellationToken t)=>db.DriverSettlements.AsNoTracking().Where(x=>x.CompanyId==c.CompanyId).OrderByDescending(x=>x.PeriodEnd).Select(x=>(object)new{x.Id,x.Reference,x.DriverId,Driver=x.Driver.FirstName+" "+x.Driver.LastName,x.PeriodStart,x.PeriodEnd,x.Status,x.GrossFares,x.Commission,x.Bonuses,x.Penalties,x.Adjustments,x.NetPayable}).ToListAsync(t);
 static async Task<IResult>CreateSettlement(DriverSettlementRequest r,IDriverSettlementService s,IAuditService a,ICompanyContext c,IBusinessEventPublisher events,CancellationToken t){try{var x=await s.CreateAsync(r,t);await Audit(a,c,"DriverSettlementCreated",x.Id,t);await events.PublishAsync(new(BusinessEventTypes.DriverSettlementCreated,"DriverSettlement",x.Id,System.Text.Json.JsonSerializer.Serialize(new{x.NetPayable}),x.Id.ToString()),t);return Results.Created($"/api/finance/driver-settlements/{x.Id}",new{x.Id,x.Reference,x.NetPayable});}catch(InvalidOperationException ex){return Results.BadRequest(new{ex.Message});}}
 static Task Audit(IAuditService a,ICompanyContext c,string type,Guid id,CancellationToken t)=>a.WriteAsync(type,"Finance","Success",SecurityEventSeverity.Information,$"{type} completed.","Finance",id.ToString(),c.CompanyId,t);
}
