using LondonVIP.Infrastructure.Data;
using LondonVIP.Infrastructure.Security;
using LondonVIP.Shared.CorporateAccounts;
using LondonVIP.Shared.Models;
using LondonVIP.Shared.Security;
using LondonVIP.Shared.Tenancy;
using Microsoft.EntityFrameworkCore;

namespace LondonVIP.Api;

public static class CorporateAccountEndpoints
{
    public static IEndpointRouteBuilder MapCorporateAccountEndpoints(this IEndpointRouteBuilder endpoints)
    {
        var group=endpoints.MapGroup("/api/accounts").RequireRateLimiting("operations");
        group.MapGet("",ListAsync).RequireAuthorization(SecurityPolicies.CorporateAccountsRead);
        group.MapGet("/summary",SummaryAsync).RequireAuthorization(SecurityPolicies.CorporateAccountsRead);
        group.MapGet("/{id:guid}",DetailAsync).RequireAuthorization(SecurityPolicies.CorporateAccountsRead);
        group.MapGet("/{id:guid}/bookings",BookingsAsync).RequireAuthorization(SecurityPolicies.CorporateAccountsRead);
        group.MapGet("/{id:guid}/statement",StatementAsync).RequireAuthorization(SecurityPolicies.CorporateAccountsRead);
        group.MapPost("",CreateAsync).RequireAuthorization(SecurityPolicies.CorporateAccountsWrite);
        group.MapPut("/{id:guid}",UpdateAsync).RequireAuthorization(SecurityPolicies.CorporateAccountsFinancialWrite);
        group.MapPatch("/{id:guid}/status",StatusAsync).RequireAuthorization(SecurityPolicies.CorporateAccountsFinancialWrite);
        return endpoints;
    }
    private static async Task<IResult> ListAsync(string? search,bool? active,bool? onHold,BillingTerms? billingTerms,LondonVIPDbContext db,ICompanyContext company,CancellationToken token)
    {
        var q=db.CorporateAccounts.AsNoTracking().Where(x=>x.CompanyId==company.CompanyId);
        if(!string.IsNullOrWhiteSpace(search)){var s=search.Trim();q=q.Where(x=>x.AccountNumber.Contains(s)||x.AccountName.Contains(s)||(x.TradingName??"").Contains(s)||x.PrimaryContactName.Contains(s)||x.Email.Contains(s)||x.Phone.Contains(s));}if(active.HasValue)q=q.Where(x=>x.IsActive==active);if(onHold.HasValue)q=q.Where(x=>x.IsOnHold==onHold);if(billingTerms.HasValue)q=q.Where(x=>x.BillingTerms==billingTerms);
        var accounts=await q.OrderBy(x=>x.AccountName).ToListAsync(token);var bookingDates=await db.Bookings.AsNoTracking().Where(x=>x.CompanyId==company.CompanyId&&x.CorporateAccountId!=null).Select(x=>new{Id=x.CorporateAccountId!.Value,x.PickupDateTime}).ToListAsync(token);var dates=bookingDates.GroupBy(x=>x.Id).ToDictionary(x=>x.Key,x=>x.Max(y=>y.PickupDateTime));
        return Results.Ok(accounts.Select(x=>List(x,dates.GetValueOrDefault(x.Id))));
    }
    private static async Task<IResult> SummaryAsync(LondonVIPDbContext db,ICompanyContext company,CancellationToken token)=>Results.Ok(new CorporateAccountSummaryDto{ActiveAccounts=await db.CorporateAccounts.CountAsync(x=>x.CompanyId==company.CompanyId&&x.IsActive,token),AccountsOnHold=await db.CorporateAccounts.CountAsync(x=>x.CompanyId==company.CompanyId&&x.IsOnHold,token),AccountsWithCreditLimit=await db.CorporateAccounts.CountAsync(x=>x.CompanyId==company.CompanyId&&x.CreditLimit!=null,token),CorporateBookings=await db.Bookings.CountAsync(x=>x.CompanyId==company.CompanyId&&x.CorporateAccountId!=null,token),CurrentBalanceTotal=await db.CorporateAccounts.Where(x=>x.CompanyId==company.CompanyId).SumAsync(x=>(decimal?)x.CurrentBalance,token)??0m});
    private static async Task<IResult> DetailAsync(Guid id,LondonVIPDbContext db,ICompanyContext company,IAuditService audit,CancellationToken token){var a=await db.CorporateAccounts.AsNoTracking().SingleOrDefaultAsync(x=>x.Id==id&&x.CompanyId==company.CompanyId,token);if(a is null){await Cross(db,audit,id,company.CompanyId,token);return Results.NotFound();}var b=await AccountBookings(db,id,company.CompanyId,token);return Results.Ok(Detail(a,b));}
    private static async Task<IResult> BookingsAsync(Guid id,LondonVIPDbContext db,ICompanyContext company,IAuditService audit,CancellationToken token){if(!await db.CorporateAccounts.AnyAsync(x=>x.Id==id&&x.CompanyId==company.CompanyId,token)){await Cross(db,audit,id,company.CompanyId,token);return Results.NotFound();}return Results.Ok(await AccountBookings(db,id,company.CompanyId,token));}
    private static async Task<IResult> StatementAsync(Guid id,LondonVIPDbContext db,ICompanyContext company,IAuditService audit,CancellationToken token){var a=await db.CorporateAccounts.AsNoTracking().SingleOrDefaultAsync(x=>x.Id==id&&x.CompanyId==company.CompanyId,token);if(a is null){await Cross(db,audit,id,company.CompanyId,token);return Results.NotFound();}var rows=await AccountBookings(db,id,company.CompanyId,token);return Results.Ok(new CorporateAccountStatementDto{CorporateAccountId=a.Id,AccountNumber=a.AccountNumber,AccountName=a.AccountName,StatementDate=DateTimeOffset.UtcNow,CurrentBalance=a.CurrentBalance,CreditLimit=a.CreditLimit,AvailableCredit=a.CreditLimit is null?null:a.CreditLimit-a.CurrentBalance,IsOnHold=a.IsOnHold,Transactions=rows.Where(x=>x.Status!=BookingStatus.Cancelled).ToList()});}
    private static async Task<IResult> CreateAsync(CorporateAccountCreateDto r,LondonVIPDbContext db,ICompanyContext company,IAuditService audit,CancellationToken token){var e=await Validate(r,null,db,company.CompanyId,token);if(e.Count>0)return Results.ValidationProblem(e);var now=DateTimeOffset.UtcNow;var a=new CorporateAccount{Id=Guid.NewGuid(),CompanyId=company.CompanyId,CreatedAt=now,UpdatedAt=now,CurrentBalance=0m};Apply(a,r);db.CorporateAccounts.Add(a);await db.SaveChangesAsync(token);await audit.WriteAsync("CorporateAccountCreated","CorporateAccounts","Succeeded",SecurityEventSeverity.Information,"Corporate account created.","CorporateAccount",a.Id.ToString(),company.CompanyId,token);return Results.Created($"/api/accounts/{a.Id}",Detail(a,[]));}
    private static async Task<IResult> UpdateAsync(Guid id,CorporateAccountUpdateDto r,LondonVIPDbContext db,ICompanyContext company,IAuditService audit,CancellationToken token){var a=await db.CorporateAccounts.SingleOrDefaultAsync(x=>x.Id==id&&x.CompanyId==company.CompanyId,token);if(a is null){await Cross(db,audit,id,company.CompanyId,token);return Results.NotFound();}var e=await Validate(r,id,db,company.CompanyId,token);if(e.Count>0)return Results.ValidationProblem(e);Apply(a,r);a.UpdatedAt=DateTimeOffset.UtcNow;await db.SaveChangesAsync(token);await audit.WriteAsync("CorporateAccountUpdated","CorporateAccounts","Succeeded",SecurityEventSeverity.Information,"Corporate account updated.","CorporateAccount",id.ToString(),company.CompanyId,token);return Results.Ok(Detail(a,[]));}
    private static async Task<IResult> StatusAsync(Guid id,CorporateAccountStatusDto r,LondonVIPDbContext db,ICompanyContext company,IAuditService audit,CancellationToken token){var a=await db.CorporateAccounts.SingleOrDefaultAsync(x=>x.Id==id&&x.CompanyId==company.CompanyId,token);if(a is null){await Cross(db,audit,id,company.CompanyId,token);return Results.NotFound();}var wasActive=a.IsActive;var wasHold=a.IsOnHold;a.IsActive=r.IsActive;a.IsOnHold=r.IsOnHold;a.UpdatedAt=DateTimeOffset.UtcNow;await db.SaveChangesAsync(token);if(wasActive!=a.IsActive)await audit.WriteAsync(a.IsActive?"CorporateAccountActivated":"CorporateAccountDeactivated","CorporateAccounts","Succeeded",SecurityEventSeverity.Information,"Corporate account active state changed.","CorporateAccount",id.ToString(),company.CompanyId,token);if(wasHold!=a.IsOnHold)await audit.WriteAsync(a.IsOnHold?"CorporateAccountPlacedOnHold":"CorporateAccountRemovedFromHold","CorporateAccounts","Succeeded",SecurityEventSeverity.Information,"Corporate account hold state changed.","CorporateAccount",id.ToString(),company.CompanyId,token);return Results.Ok(new{a.Id,a.IsActive,a.IsOnHold});}
    private static async Task<List<CorporateAccountBookingDto>> AccountBookings(LondonVIPDbContext db,Guid id,Guid companyId,CancellationToken token)=>(await db.Bookings.AsNoTracking().Where(x=>x.CompanyId==companyId&&x.CorporateAccountId==id).Select(x=>new CorporateAccountBookingDto{BookingId=x.Id,BookingReference=x.BookingReference,PickupDateTime=x.PickupDateTime,CustomerName=x.Customer.FirstName+" "+x.Customer.LastName,JourneySummary=x.PickupAddress+" → "+x.Destination,PurchaseOrderReference=x.PurchaseOrderReference,Amount=x.TotalFare,Status=x.Status}).ToListAsync(token)).OrderByDescending(x=>x.PickupDateTime).ToList();
    private static async Task<Dictionary<string,string[]>> Validate(CorporateAccountCreateDto r,Guid? id,LondonVIPDbContext db,Guid companyId,CancellationToken token){var e=CorporateAccountValidator.Validate(r);var n=CorporateAccountValidator.NormalizeAccountNumber(r.AccountNumber);var existing=await db.CorporateAccounts.Where(x=>x.CompanyId==companyId&&x.Id!=id).Select(x=>x.AccountNumber).ToListAsync(token);if(existing.Any(x=>CorporateAccountValidator.NormalizeAccountNumber(x)==n))e["accountNumber"]=["Account number already exists for the current company."];return e;}
    private static void Apply(CorporateAccount a,CorporateAccountCreateDto r){a.AccountNumber=r.AccountNumber.Trim().ToUpperInvariant();a.AccountName=r.AccountName.Trim();a.TradingName=N(r.TradingName);a.PrimaryContactName=r.PrimaryContactName.Trim();a.Email=r.Email.Trim();a.Phone=r.Phone.Trim();a.BillingEmail=N(r.BillingEmail);a.AddressLine1=r.AddressLine1.Trim();a.AddressLine2=N(r.AddressLine2);a.TownCity=r.TownCity.Trim();a.Postcode=r.Postcode.Trim();a.Country=r.Country.Trim();a.BillingTerms=r.BillingTerms;a.CreditLimit=r.CreditLimit;a.IsActive=r.IsActive;a.IsOnHold=r.IsOnHold;a.PurchaseOrderRequired=r.PurchaseOrderRequired;a.DefaultPurchaseOrderReference=N(r.DefaultPurchaseOrderReference);a.Notes=N(r.Notes);}private static string? N(string? x)=>string.IsNullOrWhiteSpace(x)?null:x.Trim();
    private static CorporateAccountListItemDto List(CorporateAccount a,DateTimeOffset? d)=>new(){Id=a.Id,AccountNumber=a.AccountNumber,AccountName=a.AccountName,PrimaryContactName=a.PrimaryContactName,Email=a.Email,BillingTerms=a.BillingTerms,CreditLimit=a.CreditLimit,CurrentBalance=a.CurrentBalance,IsActive=a.IsActive,IsOnHold=a.IsOnHold,LastBookingDate=d};
    private static CorporateAccountDetailDto Detail(CorporateAccount a,IReadOnlyList<CorporateAccountBookingDto> b)=>new(){Id=a.Id,AccountNumber=a.AccountNumber,AccountName=a.AccountName,TradingName=a.TradingName,PrimaryContactName=a.PrimaryContactName,Email=a.Email,Phone=a.Phone,BillingEmail=a.BillingEmail,AddressLine1=a.AddressLine1,AddressLine2=a.AddressLine2,TownCity=a.TownCity,Postcode=a.Postcode,Country=a.Country,BillingTerms=a.BillingTerms,CreditLimit=a.CreditLimit,CurrentBalance=a.CurrentBalance,IsActive=a.IsActive,IsOnHold=a.IsOnHold,PurchaseOrderRequired=a.PurchaseOrderRequired,DefaultPurchaseOrderReference=a.DefaultPurchaseOrderReference,Notes=a.Notes,BookingCount=b.Count,UpcomingBookingCount=b.Count(x=>x.PickupDateTime>=DateTimeOffset.UtcNow&&x.Status!=BookingStatus.Cancelled),CompletedBookingCount=b.Count(x=>x.Status==BookingStatus.Completed),LastBookingDate=b.Select(x=>(DateTimeOffset?)x.PickupDateTime).Max(),CreatedAt=a.CreatedAt,UpdatedAt=a.UpdatedAt};
    private static async Task Cross(LondonVIPDbContext db,IAuditService audit,Guid id,Guid companyId,CancellationToken token){if(await db.CorporateAccounts.AnyAsync(x=>x.Id==id&&x.CompanyId!=companyId,token))await audit.WriteAsync("CrossTenantAccessAttempt","Authorization","Denied",SecurityEventSeverity.High,"Cross-tenant corporate account access was blocked.","CorporateAccount",id.ToString(),companyId,token);}
}
