using LondonVIP.Infrastructure.Data;
using LondonVIP.Infrastructure.Security;
using LondonVIP.Shared.Crm;
using LondonVIP.Shared.Models;
using LondonVIP.Shared.Security;
using LondonVIP.Shared.Tenancy;
using Microsoft.EntityFrameworkCore;

namespace LondonVIP.Api;

public static class CrmEndpoints
{
    public static IEndpointRouteBuilder MapCrmEndpoints(this IEndpointRouteBuilder endpoints)
    {
        var read=endpoints.MapGroup("/api/crm").RequireAuthorization(SecurityPolicies.CrmRead).RequireRateLimiting("operations");
        read.MapGet("/dashboard",(ICrmService s,CancellationToken t)=>s.GetDashboardAsync(t));read.MapGet("/leads",(string? q,ICrmService s,CancellationToken t)=>s.SearchLeadsAsync(q,t));read.MapGet("/leads/{id:guid}",async(Guid id,ICrmService s,CancellationToken t)=>await s.GetLeadAsync(id,t) is{} x?Results.Ok(x):Results.NotFound());
        read.MapGet("/pipeline",(ICrmService s,CancellationToken t)=>s.GetPipelineAsync(t));read.MapGet("/conversations",(string? q,CrmConversationChannel? channel,ICrmService s,CancellationToken t)=>s.GetConversationsAsync(q,channel,t));read.MapGet("/timeline",(Guid? customerId,Guid? leadId,ICrmService s,CancellationToken t)=>s.GetTimelineAsync(customerId,leadId,t));
        read.MapGet("/tasks",async(LondonVIPDbContext db,ICompanyContext c,CancellationToken t)=>await db.CrmTasks.AsNoTracking().Where(x=>x.CompanyId==c.CompanyId).OrderBy(x=>x.DueAt).Take(500).ToListAsync(t));
        read.MapGet("/reviews",async(LondonVIPDbContext db,ICompanyContext c,CancellationToken t)=>await db.CrmReviews.AsNoTracking().Where(x=>x.CompanyId==c.CompanyId).OrderByDescending(x=>x.ReviewedAt).Take(500).ToListAsync(t));
        read.MapGet("/campaigns",async(LondonVIPDbContext db,ICompanyContext c,CancellationToken t)=>await db.CrmCampaigns.AsNoTracking().Where(x=>x.CompanyId==c.CompanyId).OrderByDescending(x=>x.CreatedAt).Take(500).ToListAsync(t));
        read.MapGet("/stages",async(LondonVIPDbContext db,ICompanyContext c,CancellationToken t)=>await db.CrmPipelineStages.AsNoTracking().Where(x=>x.CompanyId==c.CompanyId).OrderBy(x=>x.SortOrder).ToListAsync(t));
        var write=endpoints.MapGroup("/api/crm").RequireAuthorization(SecurityPolicies.CrmWrite).RequireRateLimiting("operations");
        write.MapPost("/leads",CreateLead);write.MapPut("/leads/{id:guid}",UpdateLead);write.MapPost("/leads/{id:guid}/convert",ConvertLead);write.MapPost("/opportunities",CreateOpportunity);write.MapPatch("/opportunities/{id:guid}/stage/{stageId:guid}",MoveOpportunity);write.MapPost("/communications/incoming",Ingest);
        write.MapPost("/stages",CreateStage);write.MapPost("/tasks",CreateTask);write.MapPost("/reviews",CreateReview);write.MapPost("/campaigns",CreateCampaign);
        return endpoints;
    }
    private static async Task<IResult> CreateLead(CrmLeadRequest r,ICrmService s,IAuditService a,ICompanyContext c,CancellationToken t){var e=Validate(r);if(e.Count>0)return Results.ValidationProblem(e);var x=await s.CreateLeadAsync(r,t);await Audit(a,c,"CrmLeadCreated","CrmLead",x.Id,t);return Results.Created($"/api/crm/leads/{x.Id}",x);}
    private static async Task<IResult> UpdateLead(Guid id,CrmLeadRequest r,ICrmService s,IAuditService a,ICompanyContext c,CancellationToken t){var e=Validate(r);if(e.Count>0)return Results.ValidationProblem(e);var x=await s.UpdateLeadAsync(id,r,t);if(x is null)return Results.NotFound();await Audit(a,c,"CrmLeadUpdated","CrmLead",id,t);return Results.Ok(x);}
    private static async Task<IResult> ConvertLead(Guid id,ICrmService s,IAuditService a,ICompanyContext c,CancellationToken t){var customer=await s.ConvertLeadAsync(id,t);if(customer is null)return Results.NotFound();await Audit(a,c,"CrmLeadConverted","CrmLead",id,t);return Results.Ok(new{CustomerId=customer});}
    private static async Task<IResult> CreateOpportunity(OpportunityRequest r,ICrmService s,IAuditService a,ICompanyContext c,CancellationToken t){if(string.IsNullOrWhiteSpace(r.Name)||r.Name.Length>200||r.Value<0||r.Probability is<0 or>100)return Results.BadRequest();var x=await s.CreateOpportunityAsync(r,t);if(x is null)return Results.ValidationProblem(new Dictionary<string,string[]>{{"references",["Stage or related resource is invalid for the current tenant."]}});await Audit(a,c,"CrmOpportunityCreated","CrmOpportunity",x.Id,t);return Results.Created($"/api/crm/opportunities/{x.Id}",x);}
    private static async Task<IResult> MoveOpportunity(Guid id,Guid stageId,string? reason,ICrmService s,IAuditService a,ICompanyContext c,CancellationToken t){var x=await s.MoveOpportunityAsync(id,stageId,reason,t);if(x is null)return Results.NotFound();await Audit(a,c,"CrmOpportunityStageChanged","CrmOpportunity",id,t);return Results.Ok(x);}
    private static async Task<IResult> Ingest(IncomingMessageRequest r,ICrmService s,IAuditService a,ICompanyContext c,CancellationToken t){if(string.IsNullOrWhiteSpace(r.ExternalThreadId)||string.IsNullOrWhiteSpace(r.ExternalMessageId)||string.IsNullOrWhiteSpace(r.ParticipantAddress)||string.IsNullOrWhiteSpace(r.Body))return Results.BadRequest();var x=await s.IngestAsync(r,t);await Audit(a,c,"CrmMessageReceived","CrmConversation",x.Id,t);return Results.Accepted($"/api/crm/conversations/{x.Id}",x);}
    private static async Task<IResult> CreateStage(PipelineStageRequest r,LondonVIPDbContext db,ICompanyContext c,IAuditService a,CancellationToken t){if(string.IsNullOrWhiteSpace(r.Name)||r.DefaultProbability is<0 or>100||await db.CrmPipelineStages.AnyAsync(x=>x.CompanyId==c.CompanyId&&x.SortOrder==r.SortOrder,t))return Results.BadRequest();var x=new CrmPipelineStage{Id=Guid.NewGuid(),CompanyId=c.CompanyId,Name=r.Name.Trim(),SortOrder=r.SortOrder,DefaultProbability=r.DefaultProbability,IsWon=r.IsWon,IsLost=r.IsLost,IsActive=r.IsActive};db.Add(x);await db.SaveChangesAsync(t);await Audit(a,c,"CrmPipelineStageCreated","CrmPipelineStage",x.Id,t);return Results.Created($"/api/crm/stages/{x.Id}",x);}
    private static async Task<IResult> CreateTask(CrmTaskRequest r,LondonVIPDbContext db,ICompanyContext c,IAuditService a,CancellationToken t){if(string.IsNullOrWhiteSpace(r.Title)||r.Title.Length>250)return Results.BadRequest();var x=new CrmTask{Id=Guid.NewGuid(),CompanyId=c.CompanyId,Type=r.Type,Status=CrmTaskStatus.Open,Title=r.Title.Trim(),Description=r.Description,AssignedUserId=r.AssignedUserId,LeadId=r.LeadId,CustomerId=r.CustomerId,CorporateAccountId=r.CorporateAccountId,DueAt=r.DueAt,Recurrence=r.Recurrence,CreatedAt=DateTimeOffset.UtcNow,UpdatedAt=DateTimeOffset.UtcNow};db.Add(x);await db.SaveChangesAsync(t);await Audit(a,c,"CrmTaskCreated","CrmTask",x.Id,t);return Results.Created($"/api/crm/tasks/{x.Id}",x);}
    private static async Task<IResult> CreateReview(CrmReviewRequest r,LondonVIPDbContext db,ICompanyContext c,IAuditService a,CancellationToken t){if(r.Rating is<1 or>5||string.IsNullOrWhiteSpace(r.Body)||string.IsNullOrWhiteSpace(r.ExternalId))return Results.BadRequest();var x=new CrmReview{Id=Guid.NewGuid(),CompanyId=c.CompanyId,Source=r.Source,ExternalId=r.ExternalId,CustomerId=r.CustomerId,BookingId=r.BookingId,Rating=r.Rating,Body=r.Body,IsComplaint=r.IsComplaint,Resolution=r.Resolution,ReviewedAt=r.ReviewedAt,UpdatedAt=DateTimeOffset.UtcNow};db.Add(x);await db.SaveChangesAsync(t);await Audit(a,c,"CrmReviewCreated","CrmReview",x.Id,t);return Results.Created($"/api/crm/reviews/{x.Id}",x);}
    private static async Task<IResult> CreateCampaign(CrmCampaignRequest r,LondonVIPDbContext db,ICompanyContext c,IAuditService a,CancellationToken t){if(string.IsNullOrWhiteSpace(r.Name)||string.IsNullOrWhiteSpace(r.AudienceDefinition)||r.Cost<0)return Results.BadRequest();var x=new CrmCampaign{Id=Guid.NewGuid(),CompanyId=c.CompanyId,Name=r.Name,Channel=r.Channel,AudienceDefinition=r.AudienceDefinition,Status=r.Status,Cost=r.Cost,StartsAt=r.StartsAt,EndsAt=r.EndsAt,CreatedAt=DateTimeOffset.UtcNow};db.Add(x);await db.SaveChangesAsync(t);await Audit(a,c,"CrmCampaignCreated","CrmCampaign",x.Id,t);return Results.Created($"/api/crm/campaigns/{x.Id}",x);}
    private static Dictionary<string,string[]> Validate(CrmLeadRequest r){var e=new Dictionary<string,string[]>();if(string.IsNullOrWhiteSpace(r.FirstName)||r.FirstName.Length>100)e["firstName"]=["First name is required and limited to 100 characters."];if(string.IsNullOrWhiteSpace(r.LastName)||r.LastName.Length>100)e["lastName"]=["Last name is required and limited to 100 characters."];if(string.IsNullOrWhiteSpace(r.Email)&&string.IsNullOrWhiteSpace(r.Phone))e["contact"]=["Email or phone is required."];if(r.Email?.Length>254||r.Phone?.Length>30)e["contact"]=["Contact details exceed allowed lengths."];if(r.Score is<0 or>100||r.Probability is<0 or>100||r.ExpectedRevenue<0)e["values"]=["Score, probability or revenue is invalid."];return e;}
    private static Task Audit(IAuditService a,ICompanyContext c,string type,string resource,Guid id,CancellationToken t)=>a.WriteAsync(type,"CRM","Succeeded",SecurityEventSeverity.Information,$"{resource} changed.",resource,id.ToString(),c.CompanyId,t);
}
