using LondonVIP.Infrastructure.Bookings;
using LondonVIP.Infrastructure.Customers;
using LondonVIP.Infrastructure.Data;
using LondonVIP.Infrastructure.Security;
using LondonVIP.Shared.CustomerPortal;
using LondonVIP.Shared.Models;
using LondonVIP.Shared.Notifications;
using LondonVIP.Shared.Security;
using LondonVIP.Shared.Tenancy;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using LondonVIP.Shared.Quotations;

namespace LondonVIP.Api;

public static class CustomerPlatformEndpoints
{
    public static IEndpointRouteBuilder MapCustomerPlatformEndpoints(this IEndpointRouteBuilder endpoints)
    {
        var auth = endpoints.MapGroup("/api/customer-auth").RequireRateLimiting("login");
        auth.MapPost("/register", Register).AllowAnonymous(); auth.MapPost("/verify-email", VerifyEmail).AllowAnonymous(); auth.MapPost("/forgot-password", ForgotPassword).AllowAnonymous(); auth.MapPost("/reset-password", ResetPassword).AllowAnonymous();
        var portal = endpoints.MapGroup("/api/customer").RequireAuthorization(SecurityPolicies.CustomerPortal).RequireRateLimiting("operations");
        portal.MapGet("/profile", Profile); portal.MapPut("/profile", UpdateProfile); portal.MapGet("/addresses", Addresses); portal.MapPost("/addresses", AddAddress); portal.MapPut("/addresses/{id:guid}", UpdateAddress); portal.MapDelete("/addresses/{id:guid}", DeleteAddress);
        portal.MapGet("/dashboard", Dashboard); portal.MapGet("/quotes", Quotes); portal.MapGet("/notifications", Notifications);
        portal.MapGet("/preferences", Preferences); portal.MapPut("/preferences", UpdatePreferences); portal.MapGet("/bookings", Bookings); portal.MapGet("/bookings/{id:guid}", BookingDetail); portal.MapPut("/bookings/{id:guid}", AmendBooking); portal.MapPost("/bookings/{id:guid}/cancel", CancelBooking); portal.MapPost("/bookings/{id:guid}/duplicate", DuplicateBooking); portal.MapPost("/payments/intents", PaymentIntent);
        portal.MapPost("/quotes", CreateQuote); portal.MapPost("/quotes/{id:guid}/convert", ConvertQuote);
        return endpoints;
    }

    private static async Task<IResult> Register(CustomerRegistrationRequest request, LondonVIPDbContext db, UserManager<ApplicationUser> users, IAuditService audit, INotificationService notifications, CancellationToken token)
    {
        var company = await db.Companies.SingleOrDefaultAsync(x => x.Slug == request.CompanySlug && x.IsActive, token); if (company is null) return Results.ValidationProblem(new Dictionary<string,string[]> { ["companySlug"] = ["Company was not found."] });
        if (string.IsNullOrWhiteSpace(request.FirstName) || string.IsNullOrWhiteSpace(request.LastName) || string.IsNullOrWhiteSpace(request.Email) || string.IsNullOrWhiteSpace(request.Phone)) return Results.ValidationProblem(new Dictionary<string,string[]> { ["profile"] = ["Name, email and phone are required."] });
        var normalized = users.NormalizeEmail(request.Email.Trim()); if (await db.Users.AnyAsync(x => x.CompanyId == company.Id && x.NormalizedEmail == normalized, token)) return Results.Conflict(new { message = "An account already exists." });
        await using var tx = await db.Database.BeginTransactionAsync(token); var now = DateTimeOffset.UtcNow; var customer = new Customer { Id = Guid.NewGuid(), CompanyId = company.Id, FirstName = request.FirstName.Trim(), LastName = request.LastName.Trim(), Email = request.Email.Trim(), Phone = request.Phone.Trim(), IsActive = true, CreatedAt = now, UpdatedAt = now }; db.Customers.Add(customer); await db.SaveChangesAsync(token);
        var user = new ApplicationUser { Id = Guid.NewGuid(), CompanyId = company.Id, CustomerId = customer.Id, UserName = customer.Email, Email = customer.Email, IsActive = true, CreatedAt = now }; var result = await users.CreateAsync(user, request.Password); if (!result.Succeeded) { await tx.RollbackAsync(token); return Results.ValidationProblem(result.Errors.GroupBy(x => x.Code).ToDictionary(x => x.Key, x => x.Select(y => y.Description).ToArray())); } await users.AddToRoleAsync(user, SecurityRoles.Customer);
        var verification = await users.GenerateEmailConfirmationTokenAsync(user); await notifications.QueueAsync(new(customer.Email, NotificationRecipientType.Customer, NotificationType.SystemAlert, "Verify your account", $"Use the secure verification token in the London VIP Cars portal: {verification}", "customer-email-verification", CorrelationId: user.Id.ToString()), token); await tx.CommitAsync(token); await audit.WriteAsync("CustomerRegistered", "CustomerPortal", "Succeeded", SecurityEventSeverity.Information, "Customer self-service account registered.", "Customer", customer.Id.ToString(), company.Id, token); return Results.Created("/customer-portal", new { customer.Id, VerificationRequired = true });
    }
    private static async Task<IResult> VerifyEmail(CustomerEmailTokenRequest request, LondonVIPDbContext db, UserManager<ApplicationUser> users, CancellationToken token) { var user = await FindUser(request.CompanySlug, request.Email, db, token); if (user is null) return Results.BadRequest(); var result = await users.ConfirmEmailAsync(user, request.Token); return result.Succeeded ? Results.Ok() : Results.ValidationProblem(new Dictionary<string,string[]> { ["token"] = ["Verification token is invalid or expired."] }); }
    private static async Task<IResult> ForgotPassword(CustomerForgotPasswordRequest request, LondonVIPDbContext db, UserManager<ApplicationUser> users, INotificationService notifications, CancellationToken token) { var user = await FindUser(request.CompanySlug, request.Email, db, token); if (user is not null) { var reset = await users.GeneratePasswordResetTokenAsync(user); await notifications.QueueAsync(new(user.Email!, NotificationRecipientType.Customer, NotificationType.SystemAlert, "Reset your password", $"Use this secure reset token in the portal: {reset}", "customer-password-reset", CorrelationId: user.Id.ToString()), token); } return Results.Accepted(); }
    private static async Task<IResult> ResetPassword(CustomerResetPasswordRequest request, LondonVIPDbContext db, UserManager<ApplicationUser> users, CancellationToken token) { var user = await FindUser(request.CompanySlug, request.Email, db, token); if (user is null) return Results.BadRequest(); var result = await users.ResetPasswordAsync(user, request.Token, request.NewPassword); return result.Succeeded ? Results.Ok() : Results.ValidationProblem(result.Errors.GroupBy(x => x.Code).ToDictionary(x => x.Key, x => x.Select(y => y.Description).ToArray())); }
    private static async Task<ApplicationUser?> FindUser(string slug, string email, LondonVIPDbContext db, CancellationToken token) { var companyId = await db.Companies.Where(x => x.Slug == slug && x.IsActive).Select(x => (Guid?)x.Id).SingleOrDefaultAsync(token); if (companyId is null) return null; var normalized = email.Trim().ToUpperInvariant(); return await db.Users.SingleOrDefaultAsync(x => x.CompanyId == companyId && x.NormalizedEmail == normalized && x.CustomerId != null, token); }
    private static async Task<IResult> Profile(ICustomerIdentityResolver identity, LondonVIPDbContext db, ICompanyContext company, CancellationToken token) { var id = await identity.GetCustomerIdAsync(token); var c = id is null ? null : await db.Customers.AsNoTracking().SingleOrDefaultAsync(x => x.Id == id && x.CompanyId == company.CompanyId, token); return c is null ? Results.NotFound() : Results.Ok(new { c.Id, c.FirstName, c.LastName, c.Email, c.Phone, c.SecondaryPhone, c.Address, c.Postcode }); }
    private static async Task<IResult> Dashboard(ICustomerIdentityResolver identity,LondonVIPDbContext db,ICompanyContext company,CancellationToken token){var id=await identity.GetCustomerIdAsync(token);var c=id is null?null:await db.Customers.AsNoTracking().SingleOrDefaultAsync(x=>x.Id==id&&x.CompanyId==company.CompanyId,token);if(c is null)return Results.NotFound();var bookings=await db.Bookings.AsNoTracking().Where(x=>x.CompanyId==company.CompanyId&&x.CustomerId==id).OrderByDescending(x=>x.PickupDateTime).Select(x=>new CustomerPortalBookingDto{Id=x.Id,BookingReference=x.BookingReference,PickupDateTime=x.PickupDateTime,PickupAddress=x.PickupAddress,Destination=x.Destination,Status=x.Status.ToString(),PaymentStatus=x.PaymentStatus,VehicleType=x.VehicleType.ToString(),TotalFare=x.TotalFare,DriverName=x.Driver==null?null:x.Driver.FirstName+" "+x.Driver.LastName,FlightNumber=x.FlightNumber,InvoiceNumber=db.InvoiceLines.Where(l=>l.BookingId==x.Id).Select(l=>l.Invoice.InvoiceNumber).FirstOrDefault()}).Take(500).ToListAsync(token);var invoices=await db.Invoices.AsNoTracking().Where(x=>x.CompanyId==company.CompanyId&&x.CustomerId==id).OrderByDescending(x=>x.InvoiceDate).Select(x=>new CustomerPortalInvoiceDto{Id=x.Id,InvoiceNumber=x.InvoiceNumber,InvoiceDate=x.InvoiceDate,DueDate=x.DueDate,Status=x.Status.ToString(),TotalAmount=x.TotalAmount,AmountPaid=x.AmountPaid,BalanceDue=x.BalanceDue}).Take(500).ToListAsync(token);var payments=await db.Payments.AsNoTracking().Where(x=>x.CompanyId==company.CompanyId&&x.CustomerId==id).OrderByDescending(x=>x.PaymentDate).Select(x=>new CustomerPortalPaymentDto{Id=x.Id,PaymentReference=x.PaymentReference,PaymentDate=x.PaymentDate,PaymentMethod=x.PaymentMethod.ToString(),Amount=x.Amount,AllocatedAmount=x.Allocations.Sum(a=>a.Amount)}).Take(500).ToListAsync(token);return Results.Ok(new CustomerPortalDashboardDto{CustomerId=c.Id,CustomerName=c.FirstName+" "+c.LastName,Email=c.Email,Phone=c.Phone,Bookings=bookings,Invoices=invoices,Payments=payments});}
    private static async Task<IResult> Quotes(ICustomerIdentityResolver identity,LondonVIPDbContext db,ICompanyContext company,CancellationToken token){var id=await identity.GetCustomerIdAsync(token);if(id is null)return Results.NotFound();return Results.Ok(await db.Quotations.AsNoTracking().Where(x=>x.CompanyId==company.CompanyId&&x.CustomerId==id).OrderByDescending(x=>x.CreatedAt).Select(x=>new QuotationListItemDto{Id=x.Id,QuoteReference=x.QuoteReference,PickupDateTime=x.PickupDateTime,ExpiresAt=x.ExpiresAt,Status=x.Status,VehicleType=x.VehicleType,TotalFare=x.TotalFare,ConvertedBookingId=x.ConvertedBookingId}).Take(500).ToListAsync(token));}
    private static async Task<IResult> Notifications(ICustomerIdentityResolver identity,LondonVIPDbContext db,ICompanyContext company,CancellationToken token){var id=await identity.GetCustomerIdAsync(token);if(id is null)return Results.NotFound();var c=await db.Customers.AsNoTracking().SingleAsync(x=>x.Id==id&&x.CompanyId==company.CompanyId,token);var recipients=new[]{c.Id.ToString(),c.Email,c.Phone};return Results.Ok(await db.Notifications.AsNoTracking().Where(x=>x.CompanyId==company.CompanyId&&x.RecipientType==NotificationRecipientType.Customer&&recipients.Contains(x.Recipient)).OrderByDescending(x=>x.CreatedAt).Take(100).Select(x=>new NotificationDto{Id=x.Id,Recipient=x.Recipient,RecipientType=x.RecipientType,NotificationType=x.NotificationType,Channel=x.Channel,Subject=x.Subject,Body=x.Body,TemplateName=x.TemplateName,Status=x.Status,CreatedAt=x.CreatedAt,SentAt=x.SentAt,RetryCount=x.RetryCount,CorrelationId=x.CorrelationId}).ToListAsync(token));}
    private static async Task<IResult> UpdateProfile(CustomerProfileUpdateRequest r, ICustomerIdentityResolver identity, LondonVIPDbContext db, ICompanyContext company, IAuditService audit, CancellationToken token) { var id = await identity.GetCustomerIdAsync(token); var c = id is null ? null : await db.Customers.SingleOrDefaultAsync(x => x.Id == id && x.CompanyId == company.CompanyId, token); if (c is null) return Results.NotFound(); if (string.IsNullOrWhiteSpace(r.FirstName) || string.IsNullOrWhiteSpace(r.LastName) || string.IsNullOrWhiteSpace(r.Email) || string.IsNullOrWhiteSpace(r.Phone)) return Results.BadRequest(); c.FirstName=r.FirstName.Trim();c.LastName=r.LastName.Trim();c.Email=r.Email.Trim();c.Phone=r.Phone.Trim();c.SecondaryPhone=r.SecondaryPhone?.Trim();c.Address=r.Address?.Trim();c.Postcode=r.Postcode?.Trim();c.UpdatedAt=DateTimeOffset.UtcNow;await db.SaveChangesAsync(token);await audit.WriteAsync("CustomerProfileUpdated","CustomerPortal","Succeeded",SecurityEventSeverity.Information,"Customer profile updated.","Customer",c.Id.ToString(),company.CompanyId,token);return Results.NoContent(); }
    private static async Task<IResult> Addresses(ICustomerIdentityResolver identity, LondonVIPDbContext db, ICompanyContext company, CancellationToken token) { var id=await identity.GetCustomerIdAsync(token);return id is null?Results.NotFound():Results.Ok(await db.CustomerAddresses.AsNoTracking().Where(x=>x.CompanyId==company.CompanyId&&x.CustomerId==id).OrderByDescending(x=>x.IsDefault).ThenBy(x=>x.Label).Select(x=>new CustomerAddressDto(x.Id,x.Label,x.AddressLine1,x.AddressLine2,x.City,x.Postcode,x.IsFavourite,x.IsDefault)).ToListAsync(token)); }
    private static async Task<IResult> AddAddress(CustomerAddressRequest r,ICustomerIdentityResolver identity,LondonVIPDbContext db,ICompanyContext company,CancellationToken token){var id=await identity.GetCustomerIdAsync(token);if(id is null||!Valid(r))return Results.BadRequest();if(r.IsDefault)await db.CustomerAddresses.Where(x=>x.CustomerId==id&&x.CompanyId==company.CompanyId).ExecuteUpdateAsync(x=>x.SetProperty(y=>y.IsDefault,false),token);var now=DateTimeOffset.UtcNow;var a=new CustomerAddress{Id=Guid.NewGuid(),CompanyId=company.CompanyId,CustomerId=id.Value,Label=r.Label.Trim(),AddressLine1=r.AddressLine1.Trim(),AddressLine2=r.AddressLine2?.Trim(),City=r.City.Trim(),Postcode=r.Postcode.Trim(),IsFavourite=r.IsFavourite,IsDefault=r.IsDefault,CreatedAt=now,UpdatedAt=now};db.Add(a);await db.SaveChangesAsync(token);return Results.Created($"/api/customer/addresses/{a.Id}",new CustomerAddressDto(a.Id,a.Label,a.AddressLine1,a.AddressLine2,a.City,a.Postcode,a.IsFavourite,a.IsDefault));}
    private static async Task<IResult> UpdateAddress(Guid id,CustomerAddressRequest r,ICustomerIdentityResolver identity,LondonVIPDbContext db,ICompanyContext company,CancellationToken token){var customer=await identity.GetCustomerIdAsync(token);var a=customer is null?null:await db.CustomerAddresses.SingleOrDefaultAsync(x=>x.Id==id&&x.CustomerId==customer&&x.CompanyId==company.CompanyId,token);if(a is null)return Results.NotFound();if(!Valid(r))return Results.BadRequest();a.Label=r.Label.Trim();a.AddressLine1=r.AddressLine1.Trim();a.AddressLine2=r.AddressLine2?.Trim();a.City=r.City.Trim();a.Postcode=r.Postcode.Trim();a.IsFavourite=r.IsFavourite;a.IsDefault=r.IsDefault;a.UpdatedAt=DateTimeOffset.UtcNow;await db.SaveChangesAsync(token);return Results.NoContent();}
    private static async Task<IResult> DeleteAddress(Guid id,ICustomerIdentityResolver identity,LondonVIPDbContext db,ICompanyContext company,CancellationToken token){var customer=await identity.GetCustomerIdAsync(token);var deleted=customer is null?0:await db.CustomerAddresses.Where(x=>x.Id==id&&x.CustomerId==customer&&x.CompanyId==company.CompanyId).ExecuteDeleteAsync(token);return deleted==0?Results.NotFound():Results.NoContent();}
    private static bool Valid(CustomerAddressRequest r)=>!string.IsNullOrWhiteSpace(r.Label)&&!string.IsNullOrWhiteSpace(r.AddressLine1)&&!string.IsNullOrWhiteSpace(r.City)&&!string.IsNullOrWhiteSpace(r.Postcode)&&r.Label.Length<=80;
    private static async Task<IResult> Preferences(ICustomerIdentityResolver identity,LondonVIPDbContext db,ICompanyContext company,CancellationToken token){var id=await identity.GetCustomerIdAsync(token);var p=id is null?null:await db.CustomerPreferences.AsNoTracking().SingleOrDefaultAsync(x=>x.CustomerId==id&&x.CompanyId==company.CompanyId,token);return id is null?Results.NotFound():Results.Ok(p is null?new CustomerPreferencesDto(null,null,false,true,true,"en-GB"):new(p.EmergencyContactName,p.EmergencyContactPhone,p.MarketingEnabled,p.EmailNotifications,p.SmsNotifications,p.Language));}
    private static async Task<IResult> UpdatePreferences(CustomerPreferencesDto r,ICustomerIdentityResolver identity,LondonVIPDbContext db,ICompanyContext company,CancellationToken token){var id=await identity.GetCustomerIdAsync(token);if(id is null)return Results.NotFound();var p=await db.CustomerPreferences.SingleOrDefaultAsync(x=>x.CustomerId==id&&x.CompanyId==company.CompanyId,token)??new CustomerPreferences{CustomerId=id.Value,CompanyId=company.CompanyId};p.EmergencyContactName=r.EmergencyContactName;p.EmergencyContactPhone=r.EmergencyContactPhone;p.MarketingEnabled=r.MarketingEnabled;p.EmailNotifications=r.EmailNotifications;p.SmsNotifications=r.SmsNotifications;p.Language=r.Language;p.UpdatedAt=DateTimeOffset.UtcNow;if(db.Entry(p).State==EntityState.Detached)db.Add(p);await db.SaveChangesAsync(token);return Results.NoContent();}
    private static async Task<IResult> Bookings(ICustomerIdentityResolver identity,LondonVIPDbContext db,ICompanyContext company,CancellationToken token){var id=await identity.GetCustomerIdAsync(token);return id is null?Results.NotFound():Results.Ok(await db.Bookings.AsNoTracking().Where(x=>x.CompanyId==company.CompanyId&&x.CustomerId==id).OrderByDescending(x=>x.PickupDateTime).Select(x=>new{x.Id,x.BookingReference,x.PickupDateTime,x.PickupAddress,x.Destination,x.Status,x.TotalFare,x.PaymentStatus}).Take(500).ToListAsync(token));}
    private static async Task<IResult> BookingDetail(Guid id,ICustomerIdentityResolver identity,LondonVIPDbContext db,ICompanyContext company,CancellationToken token){var customer=await identity.GetCustomerIdAsync(token);var b=customer is null?null:await db.Bookings.AsNoTracking().Where(x=>x.Id==id&&x.CustomerId==customer&&x.CompanyId==company.CompanyId).Select(x=>new CustomerPortalBookingDetailDto{Booking=new CustomerPortalBookingDto{Id=x.Id,BookingReference=x.BookingReference,PickupDateTime=x.PickupDateTime,PickupAddress=x.PickupAddress,Destination=x.Destination,Status=x.Status.ToString(),PaymentStatus=x.PaymentStatus,VehicleType=x.VehicleType.ToString(),TotalFare=x.TotalFare,DriverName=x.Driver==null?null:x.Driver.FirstName+" "+x.Driver.LastName,FlightNumber=x.FlightNumber},PassengerCount=x.PassengerCount,LuggageCount=x.LuggageCount,IsAirportPickup=x.IsAirportPickup,IsMeetAndGreet=x.IsMeetAndGreet,CustomerNotes=x.CustomerNotes}).SingleOrDefaultAsync(token);return b is null?Results.NotFound():Results.Ok(b);}
    private static async Task<IResult> AmendBooking(Guid id,CustomerBookingAmendRequest r,ICustomerIdentityResolver identity,LondonVIPDbContext db,ICompanyContext company,IAuditService audit,CancellationToken token){var customer=await identity.GetCustomerIdAsync(token);var b=customer is null?null:await db.Bookings.SingleOrDefaultAsync(x=>x.Id==id&&x.CustomerId==customer&&x.CompanyId==company.CompanyId,token);if(b is null)return Results.NotFound();if(b.Status is not(BookingStatus.Pending or BookingStatus.Confirmed)||r.PickupDateTime<=DateTimeOffset.UtcNow.AddHours(2))return Results.Conflict(new{message="Booking can no longer be amended online."});b.PickupDateTime=r.PickupDateTime;b.PickupAddress=r.PickupAddress;b.Destination=r.Destination;b.PassengerCount=r.PassengerCount;b.LuggageCount=r.LuggageCount;b.CustomerNotes=r.Notes;b.UpdatedAt=DateTimeOffset.UtcNow;await db.SaveChangesAsync(token);await audit.WriteAsync("CustomerBookingAmended","CustomerPortal","Succeeded",SecurityEventSeverity.Information,"Customer amended booking.","Booking",id.ToString(),company.CompanyId,token);return Results.NoContent();}
    private static async Task<IResult> CancelBooking(Guid id,CustomerBookingCancelRequest r,ICustomerIdentityResolver identity,LondonVIPDbContext db,ICompanyContext company,IAuditService audit,INotificationService notifications,CancellationToken token){var customer=await identity.GetCustomerIdAsync(token);var b=customer is null?null:await db.Bookings.Include(x=>x.Customer).SingleOrDefaultAsync(x=>x.Id==id&&x.CustomerId==customer&&x.CompanyId==company.CompanyId,token);if(b is null)return Results.NotFound();if(b.Status is BookingStatus.Completed or BookingStatus.Cancelled or BookingStatus.DriverEnRoute or BookingStatus.DriverArrived or BookingStatus.PassengerOnBoard)return Results.Conflict(new{message="Booking cannot be cancelled online."});b.Status=BookingStatus.Cancelled;b.CustomerNotes=string.Join(Environment.NewLine,new[]{b.CustomerNotes,$"Cancellation: {r.Reason}"}.Where(x=>!string.IsNullOrWhiteSpace(x)));b.UpdatedAt=DateTimeOffset.UtcNow;await db.SaveChangesAsync(token);await audit.WriteAsync("CustomerBookingCancelled","CustomerPortal","Succeeded",SecurityEventSeverity.Information,"Customer cancelled booking.","Booking",id.ToString(),company.CompanyId,token);await notifications.QueueAsync(new(b.Customer.Email,NotificationRecipientType.Customer,NotificationType.BookingCancelled,"Booking cancelled",$"Booking {b.BookingReference} was cancelled.","customer-booking-cancelled",CorrelationId:id.ToString()),token);return Results.NoContent();}
    private static async Task<IResult> DuplicateBooking(Guid id,ICustomerIdentityResolver identity,LondonVIPDbContext db,ICompanyContext company,CancellationToken token){var customer=await identity.GetCustomerIdAsync(token);var source=customer is null?null:await db.Bookings.AsNoTracking().SingleOrDefaultAsync(x=>x.Id==id&&x.CustomerId==customer&&x.CompanyId==company.CompanyId,token);if(source is null)return Results.NotFound();var now=DateTimeOffset.UtcNow;var copy=new Booking{Id=Guid.NewGuid(),CompanyId=company.CompanyId,CustomerId=customer!.Value,CorporateAccountId=source.CorporateAccountId,PickupAddress=source.PickupAddress,Destination=source.Destination,PickupDateTime=now.AddDays(1),PassengerCount=source.PassengerCount,LuggageCount=source.LuggageCount,VehicleType=source.VehicleType,AirportId=source.AirportId,IsAirportPickup=source.IsAirportPickup,IsMeetAndGreet=source.IsMeetAndGreet,CustomerNotes=source.CustomerNotes,BaseFare=source.BaseFare,Extras=source.Extras,TotalFare=source.TotalFare,Status=BookingStatus.Pending,PaymentStatus="Pending",CreatedAt=now,UpdatedAt=now};copy.BookingReference=BookingReferenceGenerator.Generate(copy.Id,now);db.Add(copy);await db.SaveChangesAsync(token);return Results.Created($"/api/customer/bookings/{copy.Id}",new{copy.Id,copy.BookingReference});}
    private static async Task<IResult> PaymentIntent(CustomerPaymentIntentRequest r,ICustomerIdentityResolver identity,LondonVIPDbContext db,ICompanyContext company,IPaymentGateway gateway,CancellationToken token){var customer=await identity.GetCustomerIdAsync(token);if(customer is null||!await db.Invoices.AnyAsync(x=>x.Id==r.InvoiceId&&x.CustomerId==customer&&x.CompanyId==company.CompanyId&&x.BalanceDue>=r.Amount,token))return Results.NotFound();var result=await gateway.CreateIntentAsync(r,token);return result.Available?Results.Ok(result):Results.Json(result,statusCode:StatusCodes.Status503ServiceUnavailable);}
    private static async Task<IResult> CreateQuote(CustomerQuoteCreateRequest r,ICustomerIdentityResolver identity,IQuotationWorkflowService service,LondonVIPDbContext db,ICompanyContext company,CancellationToken token){var customer=await identity.GetCustomerIdAsync(token);if(customer is null)return Results.NotFound();if(r.CorporateAccountId is not null&&!await db.CorporateAccounts.AnyAsync(x=>x.Id==r.CorporateAccountId&&x.CompanyId==company.CompanyId&&x.IsActive,token))return Results.NotFound();var result=await service.SaveAsync(new QuotationCreateDto{CustomerId=customer.Value,CorporateAccountId=r.CorporateAccountId,Pricing=r.Pricing,PickupDateTime=r.PickupDateTime,FlightNumber=r.FlightNumber,Notes=r.Notes},token:token);return result.Outcome==QuotationOperationOutcome.Success?Results.Created($"/api/customer/quotes/{result.Quotation!.Id}",new{result.Quotation.Id,result.Quotation.QuoteReference,result.Quotation.TotalFare,result.Quotation.ExpiresAt}):Results.BadRequest(new{message=result.Error});}
    private static async Task<IResult> ConvertQuote(Guid id,ICustomerIdentityResolver identity,IQuotationWorkflowService service,LondonVIPDbContext db,ICompanyContext company,CancellationToken token){var customer=await identity.GetCustomerIdAsync(token);if(customer is null||!await db.Quotations.AnyAsync(x=>x.Id==id&&x.CustomerId==customer&&x.CompanyId==company.CompanyId,token))return Results.NotFound();var result=await service.ConvertAsync(id,token);return result.Outcome is QuotationOperationOutcome.Success or QuotationOperationOutcome.AlreadyConverted?Results.Ok(new{result.Booking!.Id,result.Booking.BookingReference,AlreadyConverted=result.Outcome==QuotationOperationOutcome.AlreadyConverted}):Results.BadRequest(new{message=result.Error});}
}
