using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using LondonVIP.Api.Security;
using LondonVIP.Infrastructure.Data;
using LondonVIP.Infrastructure.Security;
using LondonVIP.Shared.Growth;
using LondonVIP.Shared.Models;
using LondonVIP.Shared.Security;
using LondonVIP.Shared.Tenancy;
using Microsoft.EntityFrameworkCore;

namespace LondonVIP.Api;

public static class GrowthEndpoints
{
    public static IEndpointRouteBuilder MapGrowthEndpoints(this IEndpointRouteBuilder endpoints)
    {
        var read = endpoints.MapGroup("/api/growth").RequireAuthorization(SecurityPolicies.CrmRead).RequireRateLimiting("operations");
        read.MapGet("/dashboard", Dashboard); read.MapGet("/promotions", Promotions); read.MapGet("/referrals", Referrals); read.MapGet("/loyalty/{customerId:guid}", Loyalty);
        read.MapGet("/campaigns", Campaigns); read.MapGet("/newsletters", Newsletters); read.MapGet("/content", Content); read.MapGet("/blog", Blog);
        read.MapGet("/seo/redirects", Redirects); read.MapGet("/social", Social); read.MapGet("/media", Media); read.MapGet("/leads", Leads);
        read.MapGet("/providers",(ISocialOperationsService s,CancellationToken t)=>s.StatusAsync(t));read.MapGet("/reports",(DateTimeOffset from,DateTimeOffset to,IAnalyticsService s,CancellationToken t)=>s.ReportAsync(from,to,t));
        var write = endpoints.MapGroup("/api/growth").RequireAuthorization(SecurityPolicies.CrmWrite).RequireRateLimiting("operations");
        write.MapPost("/promotions", CreatePromotion); write.MapPost("/promotions/validate", ValidatePromotion); write.MapPut("/promotions/{id:guid}", UpdatePromotion);
        write.MapPost("/referrals", CreateReferral); write.MapPost("/referrals/{id:guid}/qualify/{customerId:guid}", QualifyReferral);
        write.MapPost("/loyalty/points", ChangePoints); write.MapPost("/campaigns", CreateCampaign); write.MapPost("/content", CreateContent); write.MapPost("/blog", CreateBlog);
        write.MapPost("/social", CreateSocial); write.MapPost("/media", CreateMedia); write.MapPost("/seo/redirects", CreateRedirect);
        write.MapPost("/providers/{provider}/oauth/start",(MarketingChannel provider,string redirectUri,ISocialOperationsService s,CancellationToken t)=>s.BeginOAuthAsync(provider,redirectUri,t));
        write.MapPost("/providers/{provider}/oauth/callback",(MarketingChannel provider,OAuthCallbackRequest r,ISocialOperationsService s,CancellationToken t)=>s.CompleteOAuthAsync(provider,r,t));
        write.MapDelete("/providers/connections/{id:guid}",async(Guid id,ISocialOperationsService s,CancellationToken t)=>await s.DisconnectAsync(id,t)?Results.NoContent():Results.NotFound());
        write.MapPost("/social/{id:guid}/publish",(Guid id,bool immediate,ISocialOperationsService s,CancellationToken t)=>s.QueueAsync(id,immediate,t));write.MapPost("/social/process",(ISocialOperationsService s,CancellationToken t)=>s.ProcessDueAsync(t));
        write.MapPost("/ai/generate",(AiMarketingRequest r,IAiMarketingService s,CancellationToken t)=>s.GenerateAsync(r,t));
        write.MapPost("/campaigns/{id:guid}/{action}",async(Guid id,string action,ICampaignEngine s,CancellationToken t)=>{try{return await s.CommandAsync(id,action,t)?Results.Ok():Results.NotFound();}catch(InvalidOperationException ex){return Results.BadRequest(new{ex.Message});}});write.MapPost("/campaigns/process",(ICampaignEngine s,CancellationToken t)=>s.ProcessDueAsync(t));
        write.MapDelete("/{resource}/{id:guid}",DeleteGrowth);write.MapPost("/{resource}/bulk",BulkGrowth);
        endpoints.MapPost("/api/growth/newsletters/subscribe", Subscribe).AllowAnonymous().RequireRateLimiting("public-quotes");
        endpoints.MapPost("/api/growth/newsletters/confirm",ConfirmNewsletter).AllowAnonymous().RequireRateLimiting("public-quotes");
        endpoints.MapPost("/api/growth/newsletters/resend",ResendNewsletter).AllowAnonymous().RequireRateLimiting("public-quotes");
        endpoints.MapPost("/api/growth/analytics/track",TrackAnalytics).AllowAnonymous().RequireRateLimiting("public-quotes");
        endpoints.MapPost("/api/growth/webhooks/{companySlug}/{provider}",SocialWebhook).AllowAnonymous().RequireRateLimiting("public-quotes");
        endpoints.MapPost("/api/growth/leads", CaptureLead).AllowAnonymous().RequireRateLimiting("public-quotes");
        return endpoints;
    }

    private static async Task<GrowthDashboardDto> Dashboard(LondonVIPDbContext db, ICompanyContext c, CancellationToken t)
    {
        var now=DateTimeOffset.UtcNow; return new(await db.Promotions.CountAsync(x=>x.CompanyId==c.CompanyId&&x.IsActive&&x.EffectiveFrom<=now&&(x.EffectiveTo==null||x.EffectiveTo>=now),t),
            await db.Referrals.CountAsync(x=>x.CompanyId==c.CompanyId&&x.Status==ReferralStatus.Pending,t),await db.LoyaltyAccounts.CountAsync(x=>x.CompanyId==c.CompanyId,t),
            await db.MarketingCampaigns.CountAsync(x=>x.CompanyId==c.CompanyId&&x.Status==GrowthStatus.Active,t),await db.NewsletterSubscribers.CountAsync(x=>x.CompanyId==c.CompanyId&&x.IsConfirmed&&x.UnsubscribedAt==null,t),
            await db.CmsPages.CountAsync(x=>x.CompanyId==c.CompanyId&&x.Status==ContentStatus.Published,t),await db.BlogArticles.CountAsync(x=>x.CompanyId==c.CompanyId&&x.Status==ContentStatus.Published,t),
            await db.SocialPosts.CountAsync(x=>x.CompanyId==c.CompanyId&&x.Status==GrowthStatus.Active&&x.ScheduledAt>now,t),await db.MediaAssets.CountAsync(x=>x.CompanyId==c.CompanyId,t),
            await db.LeadCaptures.CountAsync(x=>x.CompanyId==c.CompanyId,t),await db.MarketingCampaigns.Where(x=>x.CompanyId==c.CompanyId).SumAsync(x=>(decimal?)x.Revenue,t)??0,
            await db.PromotionRedemptions.Where(x=>x.CompanyId==c.CompanyId).SumAsync(x=>(decimal?)x.DiscountAmount,t)??0);
    }
    private static Task<List<object>> Promotions(LondonVIPDbContext db,ICompanyContext c,CancellationToken t)=>db.Promotions.AsNoTracking().Where(x=>x.CompanyId==c.CompanyId).OrderBy(x=>x.Code).Select(x=>(object)new{x.Id,x.Code,x.Name,x.Kind,x.Value,x.IsActive,x.EffectiveFrom,x.EffectiveTo,x.UsageLimit,Usage=x.Redemptions.Count}).ToListAsync(t);
    private static Task<List<object>> Referrals(LondonVIPDbContext db,ICompanyContext c,CancellationToken t)=>db.Referrals.AsNoTracking().Where(x=>x.CompanyId==c.CompanyId).OrderByDescending(x=>x.CreatedAt).Select(x=>(object)new{x.Id,x.Code,x.ReferrerType,x.ReferrerId,x.ReferredCustomerId,x.Status,x.RewardAmount,x.CreatedAt}).ToListAsync(t);
    private static Task<LoyaltySummaryDto?> Loyalty(Guid customerId,ILoyaltyService s,CancellationToken t)=>s.GetAsync(customerId,t);
    private static Task<List<object>> Campaigns(LondonVIPDbContext db,ICompanyContext c,CancellationToken t)=>db.MarketingCampaigns.AsNoTracking().Where(x=>x.CompanyId==c.CompanyId).OrderByDescending(x=>x.CreatedAt).Select(x=>(object)new{x.Id,x.Name,x.Channel,x.Status,x.ScheduledAt,x.SentCount,x.DeliveredCount,x.OpenCount,x.ClickCount,x.ConversionCount,x.Cost,x.Revenue}).ToListAsync(t);
    private static Task<List<object>> Newsletters(LondonVIPDbContext db,ICompanyContext c,CancellationToken t)=>db.NewsletterSubscribers.AsNoTracking().Where(x=>x.CompanyId==c.CompanyId).OrderByDescending(x=>x.SubscribedAt).Select(x=>(object)new{x.Id,x.Email,x.Name,x.Lists,x.Segments,x.IsConfirmed,x.SubscribedAt,x.UnsubscribedAt}).ToListAsync(t);
    private static Task<List<object>> Content(LondonVIPDbContext db,ICompanyContext c,CancellationToken t)=>db.CmsPages.AsNoTracking().Where(x=>x.CompanyId==c.CompanyId).OrderBy(x=>x.Slug).Select(x=>(object)new{x.Id,x.Slug,x.Title,x.PageType,x.Status,x.PublishAt,x.UpdatedAt}).ToListAsync(t);
    private static Task<List<object>> Blog(LondonVIPDbContext db,ICompanyContext c,CancellationToken t)=>db.BlogArticles.AsNoTracking().Where(x=>x.CompanyId==c.CompanyId).OrderByDescending(x=>x.PublishAt).Select(x=>(object)new{x.Id,x.Slug,x.Title,x.Author,x.Category,x.Tags,x.Status,x.PublishAt}).ToListAsync(t);
    private static Task<List<object>> Redirects(LondonVIPDbContext db,ICompanyContext c,CancellationToken t)=>db.SeoRedirects.AsNoTracking().Where(x=>x.CompanyId==c.CompanyId).Select(x=>(object)new{x.Id,x.SourcePath,x.DestinationUrl,x.StatusCode,x.IsActive}).ToListAsync(t);
    private static Task<List<object>> Social(LondonVIPDbContext db,ICompanyContext c,CancellationToken t)=>db.SocialPosts.AsNoTracking().Where(x=>x.CompanyId==c.CompanyId).OrderByDescending(x=>x.CreatedAt).Select(x=>(object)new{x.Id,x.Channel,x.AccountKey,x.Body,x.Status,x.ScheduledAt,x.PublishedAt,x.EngagementCount}).ToListAsync(t);
    private static Task<List<object>> Media(LondonVIPDbContext db,ICompanyContext c,CancellationToken t)=>db.MediaAssets.AsNoTracking().Where(x=>x.CompanyId==c.CompanyId).OrderByDescending(x=>x.CreatedAt).Select(x=>(object)new{x.Id,x.Folder,x.FileName,x.ContentType,x.SizeBytes,x.Tags,x.Version,x.CreatedAt}).ToListAsync(t);
    private static Task<List<object>> Leads(LondonVIPDbContext db,ICompanyContext c,CancellationToken t)=>db.LeadCaptures.AsNoTracking().Where(x=>x.CompanyId==c.CompanyId).OrderByDescending(x=>x.CreatedAt).Select(x=>(object)new{x.Id,x.Type,x.Source,x.Campaign,x.Name,x.Email,x.Phone,x.CrmLeadId,x.CreatedAt}).ToListAsync(t);

    private static async Task<IResult> CreatePromotion(PromotionRequest r,LondonVIPDbContext db,ICompanyContext c,IAuditService a,CancellationToken t){var errors=Validate(r);if(errors.Count>0)return Results.ValidationProblem(errors);var x=Map(r,c.CompanyId);if(await db.Promotions.AnyAsync(p=>p.CompanyId==c.CompanyId&&p.Code==x.Code,t))return Results.Conflict();db.Add(x);await db.SaveChangesAsync(t);await Audit(a,c,"PromotionCreated",x.Id,t);return Results.Created($"/api/growth/promotions/{x.Id}",new{x.Id,x.Code});}
    private static async Task<IResult> UpdatePromotion(Guid id,PromotionRequest r,LondonVIPDbContext db,ICompanyContext c,IAuditService a,CancellationToken t){var errors=Validate(r);if(errors.Count>0)return Results.ValidationProblem(errors);var x=await db.Promotions.SingleOrDefaultAsync(p=>p.Id==id&&p.CompanyId==c.CompanyId,t);if(x is null)return Results.NotFound();var n=Map(r,c.CompanyId);x.Code=n.Code;x.Name=n.Name;x.Kind=n.Kind;x.Value=n.Value;x.MaximumDiscount=n.MaximumDiscount;x.MinimumSpend=n.MinimumSpend;x.AirportId=n.AirportId;x.PickupPattern=n.PickupPattern;x.DestinationPattern=n.DestinationPattern;x.FirstBookingOnly=n.FirstBookingOnly;x.ReturningCustomersOnly=n.ReturningCustomersOnly;x.CorporateOnly=n.CorporateOnly;x.AllowStacking=n.AllowStacking;x.UsageLimit=n.UsageLimit;x.PerCustomerLimit=n.PerCustomerLimit;x.EffectiveFrom=n.EffectiveFrom;x.EffectiveTo=n.EffectiveTo;x.IsActive=n.IsActive;await db.SaveChangesAsync(t);await Audit(a,c,"PromotionUpdated",x.Id,t);return Results.Ok(new{x.Id,x.Code});}
    private static async Task<IResult> ValidatePromotion(PromotionContext r,IPromotionEngine s,CancellationToken t)=>Results.Ok(await s.ValidateAsync(r,t));
    private static async Task<IResult> CreateReferral(ReferralRequest r,IReferralService s,IAuditService a,ICompanyContext c,CancellationToken t){if(string.IsNullOrWhiteSpace(r.ReferrerType)||r.RewardAmount<0)return Results.BadRequest();var x=await s.CreateAsync(r,t);await Audit(a,c,"ReferralCreated",x.Id,t);return Results.Created($"/api/growth/referrals/{x.Id}",x);}
    private static async Task<IResult> QualifyReferral(Guid id,Guid customerId,IReferralService s,IAuditService a,ICompanyContext c,CancellationToken t){if(!await s.QualifyAsync(id,customerId,t))return Results.NotFound();await Audit(a,c,"ReferralQualified",id,t);return Results.Ok();}
    private static async Task<IResult> ChangePoints(LoyaltyChangeRequest r,ILoyaltyService s,IAuditService a,ICompanyContext c,CancellationToken t){if(r.Points==0||string.IsNullOrWhiteSpace(r.Reason))return Results.BadRequest();try{var x=await s.ChangePointsAsync(r,t);await Audit(a,c,"LoyaltyPointsChanged",r.CustomerId,t);return Results.Ok(x);}catch(InvalidOperationException e){return Results.BadRequest(new{e.Message});}}
    private static async Task<IResult> CreateCampaign(CampaignRequest r,LondonVIPDbContext db,ICompanyContext c,IAuditService a,CancellationToken t){if(string.IsNullOrWhiteSpace(r.Name)||string.IsNullOrWhiteSpace(r.AudienceDefinition)||string.IsNullOrWhiteSpace(r.TemplateName))return Results.BadRequest();var x=new MarketingCampaign{Id=Guid.NewGuid(),CompanyId=c.CompanyId,Name=r.Name.Trim(),Channel=r.Channel,AudienceDefinition=r.AudienceDefinition,TemplateName=r.TemplateName,Status=GrowthStatus.Draft,ScheduledAt=r.ScheduledAt,CreatedAt=DateTimeOffset.UtcNow};db.Add(x);await db.SaveChangesAsync(t);await Audit(a,c,"MarketingCampaignCreated",x.Id,t);return Results.Created($"/api/growth/campaigns/{x.Id}",new{x.Id});}
    private static async Task<IResult> CreateContent(ContentRequest r,LondonVIPDbContext db,ICompanyContext c,IAuditService a,CancellationToken t){if(string.IsNullOrWhiteSpace(r.Slug)||string.IsNullOrWhiteSpace(r.Title))return Results.BadRequest();var x=new CmsPage{Id=Guid.NewGuid(),CompanyId=c.CompanyId,Slug=Slug(r.Slug),Title=r.Title,PageType=r.PageType,ContentJson=r.ContentJson,MetaTitle=r.MetaTitle,MetaDescription=r.MetaDescription,CanonicalUrl=r.CanonicalUrl,Status=r.Status,PublishAt=r.PublishAt,UpdatedAt=DateTimeOffset.UtcNow};db.Add(x);await db.SaveChangesAsync(t);await Audit(a,c,"CmsPageCreated",x.Id,t);return Results.Created($"/api/growth/content/{x.Id}",new{x.Id});}
    private static async Task<IResult> CreateBlog(BlogRequest r,LondonVIPDbContext db,ICompanyContext c,IAuditService a,CancellationToken t){if(string.IsNullOrWhiteSpace(r.Slug)||string.IsNullOrWhiteSpace(r.Title)||string.IsNullOrWhiteSpace(r.Author))return Results.BadRequest();var x=new BlogArticle{Id=Guid.NewGuid(),CompanyId=c.CompanyId,Slug=Slug(r.Slug),Title=r.Title,Excerpt=r.Excerpt,Body=r.Body,Author=r.Author,Category=r.Category,Tags=r.Tags,MetaTitle=r.MetaTitle,MetaDescription=r.MetaDescription,Status=r.Status,PublishAt=r.PublishAt,UpdatedAt=DateTimeOffset.UtcNow};db.Add(x);await db.SaveChangesAsync(t);await Audit(a,c,"BlogArticleCreated",x.Id,t);return Results.Created($"/api/growth/blog/{x.Id}",new{x.Id});}
    private static async Task<IResult> CreateSocial(JsonElement r,LondonVIPDbContext db,ICompanyContext c,IAuditService a,CancellationToken t){var channel=Enum.Parse<MarketingChannel>(r.GetProperty("channel").GetString()!,true);var x=new SocialPost{Id=Guid.NewGuid(),CompanyId=c.CompanyId,Channel=channel,AccountKey=r.GetProperty("accountKey").GetString()!,Body=r.GetProperty("body").GetString()!,Status=GrowthStatus.Draft,CreatedAt=DateTimeOffset.UtcNow};db.Add(x);await db.SaveChangesAsync(t);await Audit(a,c,"SocialPostCreated",x.Id,t);return Results.Created($"/api/growth/social/{x.Id}",new{x.Id});}
    private static async Task<IResult> CreateMedia(JsonElement r,LondonVIPDbContext db,ICompanyContext c,IAuditService a,CancellationToken t){var x=new MediaAsset{Id=Guid.NewGuid(),CompanyId=c.CompanyId,Folder=r.GetProperty("folder").GetString()!,FileName=r.GetProperty("fileName").GetString()!,ContentType=r.GetProperty("contentType").GetString()!,SizeBytes=r.GetProperty("sizeBytes").GetInt64(),StoragePath=r.GetProperty("storagePath").GetString()!,Tags=r.TryGetProperty("tags",out var tags)?tags.GetString()??"":"",CreatedAt=DateTimeOffset.UtcNow};db.Add(x);await db.SaveChangesAsync(t);await Audit(a,c,"MediaAssetCreated",x.Id,t);return Results.Created($"/api/growth/media/{x.Id}",new{x.Id});}
    private static async Task<IResult> CreateRedirect(JsonElement r,LondonVIPDbContext db,ICompanyContext c,IAuditService a,CancellationToken t){var x=new SeoRedirect{Id=Guid.NewGuid(),CompanyId=c.CompanyId,SourcePath=r.GetProperty("sourcePath").GetString()!,DestinationUrl=r.GetProperty("destinationUrl").GetString()!,StatusCode=r.TryGetProperty("statusCode",out var status)?status.GetInt32():301,CreatedAt=DateTimeOffset.UtcNow};db.Add(x);await db.SaveChangesAsync(t);await Audit(a,c,"SeoRedirectCreated",x.Id,t);return Results.Created($"/api/growth/seo/redirects/{x.Id}",new{x.Id});}
    private static async Task<IResult> Subscribe(NewsletterRequest r,LondonVIPDbContext db,CancellationToken t){if(!System.Net.Mail.MailAddress.TryCreate(r.Email,out var mail))return Results.BadRequest();var companyId=await DefaultCompany(db,t);var email=mail.Address.ToUpperInvariant();var existing=await db.NewsletterSubscribers.SingleOrDefaultAsync(x=>x.CompanyId==companyId&&x.Email==email,t);if(existing?.IsConfirmed==true&&existing.UnsubscribedAt is null)return Results.Accepted();var token=Convert.ToHexString(RandomNumberGenerator.GetBytes(32));var x=existing??new NewsletterSubscriber{Id=Guid.NewGuid(),CompanyId=companyId,Email=email,SubscribedAt=DateTimeOffset.UtcNow};if(db.Entry(x).State==EntityState.Detached)db.Add(x);x.Name=r.Name;x.Lists=r.Lists??"General";x.Segments=r.Segments??"";x.ConfirmationTokenHash=Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(token)));x.ConfirmationExpiresAt=DateTimeOffset.UtcNow.AddHours(24);x.ConfirmationSendCount++;x.UnsubscribedAt=null;await db.SaveChangesAsync(t);return Results.Accepted();}
    private static async Task<IResult> ConfirmNewsletter(string token,LondonVIPDbContext db,CancellationToken t){var hash=Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(token)));var x=await db.NewsletterSubscribers.SingleOrDefaultAsync(x=>x.ConfirmationTokenHash==hash,t);if(x is null||x.ConfirmationExpiresAt<DateTimeOffset.UtcNow)return Results.BadRequest(new{Message="Confirmation token is invalid or expired."});if(!x.IsConfirmed){x.IsConfirmed=true;x.ConfirmedAt=DateTimeOffset.UtcNow;x.ConfirmationTokenHash="";await db.SaveChangesAsync(t);}return Results.Ok(new{Message="Subscription confirmed."});}
    private static async Task<IResult> ResendNewsletter(NewsletterRequest r,LondonVIPDbContext db,CancellationToken t){var companyId=await DefaultCompany(db,t);var x=await db.NewsletterSubscribers.SingleOrDefaultAsync(x=>x.CompanyId==companyId&&x.Email==r.Email.ToUpper(),t);if(x is null||x.IsConfirmed)return Results.Accepted();var token=Convert.ToHexString(RandomNumberGenerator.GetBytes(32));x.ConfirmationTokenHash=Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(token)));x.ConfirmationExpiresAt=DateTimeOffset.UtcNow.AddHours(24);x.ConfirmationSendCount++;await db.SaveChangesAsync(t);return Results.Accepted();}
    private static async Task<IResult> TrackAnalytics(AnalyticsTrackRequest r,LondonVIPDbContext db,CancellationToken t){if(string.IsNullOrWhiteSpace(r.AnonymousId)||string.IsNullOrWhiteSpace(r.SessionKey)||string.IsNullOrWhiteSpace(r.Path))return Results.BadRequest();var companyId=await DefaultCompany(db,t);static string Hash(string x)=>Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(x)));var key=Hash(r.SessionKey);var session=await db.AnalyticsSessions.SingleOrDefaultAsync(x=>x.CompanyId==companyId&&x.SessionKeyHash==key,t)??new AnalyticsSession{Id=Guid.NewGuid(),CompanyId=companyId,AnonymousIdHash=Hash(r.AnonymousId),SessionKeyHash=key,StartedAt=DateTimeOffset.UtcNow};if(db.Entry(session).State==EntityState.Detached)db.Add(session);session.Source=r.Source;session.Medium=r.Medium;session.Campaign=r.Campaign;session.ReferrerHost=r.ReferrerHost;session.LastSeenAt=DateTimeOffset.UtcNow;session.Events.Add(new AnalyticsEvent{Id=Guid.NewGuid(),CompanyId=companyId,Type=r.Type,Path=r.Path,Goal=r.Goal,Value=r.Value,QuotationId=r.QuotationId,BookingId=r.BookingId,OccurredAt=DateTimeOffset.UtcNow});await db.SaveChangesAsync(t);return Results.Accepted();}
    private static async Task<IResult> SocialWebhook(string companySlug,MarketingChannel provider,HttpRequest request,LondonVIPDbContext db,ISocialProviderRegistry registry,CancellationToken t){var companyId=await db.Companies.Where(x=>x.Slug==companySlug&&x.IsActive).Select(x=>(Guid?)x.Id).SingleOrDefaultAsync(t);if(companyId is null)return Results.NotFound();using var reader=new StreamReader(request.Body);var payload=await reader.ReadToEndAsync(t);var signature=request.Headers["X-Hub-Signature-256"].FirstOrDefault()??request.Headers["X-Signature"].FirstOrDefault();var adapter=registry.Find(provider);if(adapter is null||!await adapter.ValidateWebhookAsync(payload,signature,t))return Results.Unauthorized();var delivery=request.Headers["X-Delivery-Id"].FirstOrDefault()??Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(payload)));if(await db.IntegrationWebhookDeliveries.AnyAsync(x=>x.CompanyId==companyId&&x.ProviderKey==provider.ToString()&&x.DeliveryId==delivery,t))return Results.Ok(new{Duplicate=true});var now=DateTimeOffset.UtcNow;db.IntegrationWebhookDeliveries.Add(new(){Id=Guid.NewGuid(),CompanyId=companyId.Value,ProviderKey=provider.ToString(),EventType="SocialInbound",Direction=LondonVIP.Shared.Integrations.WebhookDirection.Incoming,Status=LondonVIP.Shared.Integrations.WebhookDeliveryState.Delivered,DeliveryId=delivery,Payload=payload,Signature=signature,AttemptCount=1,CreatedAt=now,UpdatedAt=now,CompletedAt=now,CorrelationId=request.HttpContext.TraceIdentifier});await db.SaveChangesAsync(t);return Results.Accepted();}
    private static async Task<IResult> CaptureLead(LeadCaptureRequest r,LondonVIPDbContext db,CancellationToken t){if(string.IsNullOrWhiteSpace(r.Type)||string.IsNullOrWhiteSpace(r.Source)||(string.IsNullOrWhiteSpace(r.Email)&&string.IsNullOrWhiteSpace(r.Phone)))return Results.BadRequest();var companyId=await DefaultCompany(db,t);var lead=new CrmLead{Id=Guid.NewGuid(),CompanyId=companyId,Reference=$"LEAD-{DateTime.UtcNow:yyyyMMdd}-{Guid.NewGuid():N}"[..22],FirstName=r.Name?.Split(' ',2)[0]??"Website",LastName=r.Name?.Split(' ',2).ElementAtOrDefault(1)??"Enquiry",Email=r.Email,Phone=r.Phone,Source=r.Source,Status=CrmLeadStatus.New,Priority=CrmPriority.Normal,CreatedAt=DateTimeOffset.UtcNow,UpdatedAt=DateTimeOffset.UtcNow};db.Add(lead);db.Add(new LeadCapture{Id=Guid.NewGuid(),CompanyId=companyId,Type=r.Type,Source=r.Source,Campaign=r.Campaign,Name=r.Name,Email=r.Email,Phone=r.Phone,PayloadJson=JsonSerializer.Serialize(new{r.Message}),CrmLeadId=lead.Id,CreatedAt=DateTimeOffset.UtcNow});await db.SaveChangesAsync(t);return Results.Accepted();}
    private static Promotion Map(PromotionRequest r,Guid companyId)=>new(){Id=Guid.NewGuid(),CompanyId=companyId,Code=r.Code.Trim().ToUpperInvariant(),Name=r.Name.Trim(),Kind=r.Kind,Value=r.Value,MaximumDiscount=r.MaximumDiscount,MinimumSpend=r.MinimumSpend,AirportId=r.AirportId,PickupPattern=r.PickupPattern,DestinationPattern=r.DestinationPattern,FirstBookingOnly=r.FirstBookingOnly,ReturningCustomersOnly=r.ReturningCustomersOnly,CorporateOnly=r.CorporateOnly,AllowStacking=r.AllowStacking,UsageLimit=r.UsageLimit,PerCustomerLimit=r.PerCustomerLimit,EffectiveFrom=r.EffectiveFrom,EffectiveTo=r.EffectiveTo,IsActive=r.IsActive,CreatedAt=DateTimeOffset.UtcNow};
    private static Dictionary<string,string[]> Validate(PromotionRequest r){var e=new Dictionary<string,string[]>();if(string.IsNullOrWhiteSpace(r.Code)||r.Code.Length>50)e["code"]=["A code of up to 50 characters is required."];if(string.IsNullOrWhiteSpace(r.Name)||r.Name.Length>200)e["name"]=["A name of up to 200 characters is required."];if(r.Value<=0||(r.Kind==DiscountKind.Percentage&&r.Value>100))e["value"]=["Discount value is invalid."];if(r.EffectiveTo<r.EffectiveFrom)e["effectiveTo"]=["Expiry must follow the start date."];if(r.UsageLimit<1||r.PerCustomerLimit<1)e["limits"]=["Usage limits must be positive."];return e;}
    private static string Slug(string value)=>value.Trim().ToLowerInvariant().Replace(' ','-');
    private static Task<Guid> DefaultCompany(LondonVIPDbContext db,CancellationToken t)=>db.Companies.Where(x=>x.IsActive&&x.Slug=="london-vip-cars").Select(x=>x.Id).SingleAsync(t);
    private static async Task<IResult> DeleteGrowth(string resource,Guid id,LondonVIPDbContext db,ICompanyContext c,IAuditService a,CancellationToken t){var count=resource.ToLowerInvariant() switch{"promotions"=>await db.Promotions.Where(x=>x.CompanyId==c.CompanyId&&x.Id==id&&!x.Redemptions.Any()).ExecuteDeleteAsync(t),"referrals"=>await db.Referrals.Where(x=>x.CompanyId==c.CompanyId&&x.Id==id&&x.Status==ReferralStatus.Pending).ExecuteDeleteAsync(t),"campaigns"=>await db.MarketingCampaigns.Where(x=>x.CompanyId==c.CompanyId&&x.Id==id&&!x.Deliveries.Any()).ExecuteDeleteAsync(t),"content"=>await db.CmsPages.Where(x=>x.CompanyId==c.CompanyId&&x.Id==id).ExecuteDeleteAsync(t),"blog"=>await db.BlogArticles.Where(x=>x.CompanyId==c.CompanyId&&x.Id==id).ExecuteDeleteAsync(t),"social"=>await db.SocialPosts.Where(x=>x.CompanyId==c.CompanyId&&x.Id==id&&x.PublishStatus!=PublishStatus.Published).ExecuteDeleteAsync(t),"media"=>await db.MediaAssets.Where(x=>x.CompanyId==c.CompanyId&&x.Id==id).ExecuteDeleteAsync(t),"seo"=>await db.SeoRedirects.Where(x=>x.CompanyId==c.CompanyId&&x.Id==id).ExecuteDeleteAsync(t),_=>0};if(count==0)return Results.NotFound();await Audit(a,c,"GrowthEntityDeleted",id,t);return Results.NoContent();}
    private static async Task<IResult> BulkGrowth(string resource,BulkGrowthRequest r,LondonVIPDbContext db,ICompanyContext c,IAuditService a,CancellationToken t){if(r.Ids.Count==0||r.Ids.Count>500)return Results.BadRequest();var archive=r.Action.Equals("archive",StringComparison.OrdinalIgnoreCase);var restore=r.Action.Equals("restore",StringComparison.OrdinalIgnoreCase);if(!archive&&!restore)return Results.BadRequest();var count=resource.ToLowerInvariant() switch{"content"=>await db.CmsPages.Where(x=>x.CompanyId==c.CompanyId&&r.Ids.Contains(x.Id)).ExecuteUpdateAsync(x=>x.SetProperty(y=>y.Status,archive?ContentStatus.Archived:ContentStatus.Draft),t),"blog"=>await db.BlogArticles.Where(x=>x.CompanyId==c.CompanyId&&r.Ids.Contains(x.Id)).ExecuteUpdateAsync(x=>x.SetProperty(y=>y.Status,archive?ContentStatus.Archived:ContentStatus.Draft),t),"campaigns"=>await db.MarketingCampaigns.Where(x=>x.CompanyId==c.CompanyId&&r.Ids.Contains(x.Id)).ExecuteUpdateAsync(x=>x.SetProperty(y=>y.Status,archive?GrowthStatus.Completed:GrowthStatus.Draft),t),"social"=>await db.SocialPosts.Where(x=>x.CompanyId==c.CompanyId&&r.Ids.Contains(x.Id)).ExecuteUpdateAsync(x=>x.SetProperty(y=>y.PublishStatus,archive?PublishStatus.Archived:PublishStatus.Draft),t),"media"=>await db.MediaAssets.Where(x=>x.CompanyId==c.CompanyId&&r.Ids.Contains(x.Id)).ExecuteUpdateAsync(x=>x.SetProperty(y=>y.IsArchived,archive),t),_=>0};await Audit(a,c,"GrowthBulkOperation",Guid.Empty,t);return Results.Ok(new{Updated=count});}
    private static Task Audit(IAuditService a,ICompanyContext c,string type,Guid id,CancellationToken t)=>a.WriteAsync(type,"Growth","Success",SecurityEventSeverity.Information,$"{type} completed.","Growth",id.ToString(),c.CompanyId,t);
}
