using LondonVIP.Infrastructure.Data;
using LondonVIP.Infrastructure.Security;
using LondonVIP.Shared.Drivers;
using LondonVIP.Shared.Models;
using LondonVIP.Shared.Security;
using LondonVIP.Shared.Tenancy;
using LondonVIP.Shared.Vehicles;
using Microsoft.EntityFrameworkCore;

namespace LondonVIP.Api;

public static class VehicleEndpoints
{
    public static IEndpointRouteBuilder MapVehicleEndpoints(this IEndpointRouteBuilder endpoints)
    {
        var group=endpoints.MapGroup("/api/vehicles").RequireRateLimiting("operations");
        group.MapGet("",ListAsync).RequireAuthorization(SecurityPolicies.DriverFleetRead); group.MapGet("/{id:guid}",DetailAsync).RequireAuthorization(SecurityPolicies.DriverFleetRead);
        group.MapPost("",CreateAsync).RequireAuthorization(SecurityPolicies.DriverFleetWrite); group.MapPut("/{id:guid}",UpdateAsync).RequireAuthorization(SecurityPolicies.DriverFleetWrite); group.MapPatch("/{id:guid}/status",StatusAsync).RequireAuthorization(SecurityPolicies.DriverFleetWrite); return endpoints;
    }
    private static async Task<IResult> ListAsync(string? search,VehicleType? vehicleType,bool? active,bool? assigned,LondonVIPDbContext db,ICompanyContext company,CancellationToken token)
    {
        var q=db.Vehicles.AsNoTracking().Where(x=>x.CompanyId==company.CompanyId); if(!string.IsNullOrWhiteSpace(search)){var t=search.Trim();q=q.Where(x=>x.RegistrationNumber.Contains(t)||x.Make.Contains(t)||x.Model.Contains(t));} if(vehicleType.HasValue)q=q.Where(x=>x.VehicleType==vehicleType);if(active.HasValue)q=q.Where(x=>x.IsActive==active);
        var vehicles=await q.OrderBy(x=>x.RegistrationNumber).ToListAsync(token);var drivers=await db.Drivers.AsNoTracking().Where(x=>x.CompanyId==company.CompanyId&&x.VehicleId!=null).ToDictionaryAsync(x=>x.VehicleId!.Value,token);
        var result=vehicles.Select(x=>ToList(x,drivers.GetValueOrDefault(x.Id))).Where(x=>!assigned.HasValue||(x.AssignedDriverId.HasValue==assigned.Value));return Results.Ok(result);
    }
    private static async Task<IResult> DetailAsync(Guid id,LondonVIPDbContext db,ICompanyContext company,IAuditService audit,CancellationToken token){var v=await db.Vehicles.AsNoTracking().SingleOrDefaultAsync(x=>x.Id==id&&x.CompanyId==company.CompanyId,token);if(v is null){await Cross(db,audit,id,company.CompanyId,token);return Results.NotFound();}var d=await db.Drivers.AsNoTracking().SingleOrDefaultAsync(x=>x.CompanyId==company.CompanyId&&x.VehicleId==id,token);return Results.Ok(ToDetail(v,d));}
    private static async Task<IResult> CreateAsync(VehicleCreateDto r,LondonVIPDbContext db,ICompanyContext company,IAuditService audit,CancellationToken token){var e=await Validate(r,null,db,company.CompanyId,token);if(e.Count>0)return Results.ValidationProblem(e);var now=DateTimeOffset.UtcNow;var v=new Vehicle{Id=Guid.NewGuid(),CompanyId=company.CompanyId,CreatedAt=now,UpdatedAt=now};Apply(v,r);db.Vehicles.Add(v);await db.SaveChangesAsync(token);await audit.WriteAsync("VehicleCreated","Fleet","Succeeded",SecurityEventSeverity.Information,"Vehicle record created.","Vehicle",v.Id.ToString(),company.CompanyId,token);return Results.Created($"/api/vehicles/{v.Id}",ToDetail(v,null));}
    private static async Task<IResult> UpdateAsync(Guid id,VehicleUpdateDto r,LondonVIPDbContext db,ICompanyContext company,IAuditService audit,CancellationToken token){var v=await db.Vehicles.SingleOrDefaultAsync(x=>x.Id==id&&x.CompanyId==company.CompanyId,token);if(v is null){await Cross(db,audit,id,company.CompanyId,token);return Results.NotFound();}var e=await Validate(r,id,db,company.CompanyId,token);if(e.Count>0)return Results.ValidationProblem(e);Apply(v,r);v.UpdatedAt=DateTimeOffset.UtcNow;await db.SaveChangesAsync(token);await audit.WriteAsync("VehicleUpdated","Fleet","Succeeded",SecurityEventSeverity.Information,"Vehicle record updated.","Vehicle",id.ToString(),company.CompanyId,token);return Results.Ok(ToDetail(v,null));}
    private static async Task<IResult> StatusAsync(Guid id,VehicleStatusUpdateDto r,LondonVIPDbContext db,ICompanyContext company,IAuditService audit,CancellationToken token){var v=await db.Vehicles.SingleOrDefaultAsync(x=>x.Id==id&&x.CompanyId==company.CompanyId,token);if(v is null){await Cross(db,audit,id,company.CompanyId,token);return Results.NotFound();}if(!r.IsActive&&await db.Drivers.AnyAsync(x=>x.CompanyId==company.CompanyId&&x.VehicleId==id&&x.IsActive,token))return Results.Conflict(new{message="Unassign this vehicle from its active driver before deactivation."});v.IsActive=r.IsActive;v.UpdatedAt=DateTimeOffset.UtcNow;await db.SaveChangesAsync(token);await audit.WriteAsync(r.IsActive?"VehicleActivated":"VehicleDeactivated","Fleet","Succeeded",SecurityEventSeverity.Information,"Vehicle active state changed.","Vehicle",id.ToString(),company.CompanyId,token);return Results.Ok(new{v.Id,v.IsActive});}
    private static async Task<Dictionary<string,string[]>> Validate(VehicleCreateDto r,Guid? id,LondonVIPDbContext db,Guid companyId,CancellationToken token){var e=VehicleValidator.Validate(r);var n=VehicleValidator.NormalizeRegistration(r.RegistrationNumber);var all=await db.Vehicles.Where(x=>x.CompanyId==companyId&&x.Id!=id).Select(x=>x.RegistrationNumber).ToListAsync(token);if(all.Any(x=>VehicleValidator.NormalizeRegistration(x)==n))e["registrationNumber"]=["A vehicle with this registration already exists for the current company."];return e;}
    private static void Apply(Vehicle v,VehicleCreateDto r){v.RegistrationNumber=r.RegistrationNumber.Trim().ToUpperInvariant();v.Make=r.Make.Trim();v.Model=r.Model.Trim();v.VehicleType=r.VehicleType;v.PassengerCapacity=r.PassengerCapacity;v.LuggageCapacity=r.LuggageCapacity;v.IsActive=r.IsActive;v.Colour=Trim(r.Colour);v.Year=r.Year;v.Notes=Trim(r.Notes);v.MOTExpiry=r.MOTExpiry;v.InsuranceExpiry=r.InsuranceExpiry;v.PrivateHireLicenceExpiry=r.PrivateHireLicenceExpiry;}
    private static VehicleListItemDto ToList(Vehicle v,Driver? d)=>new(){Id=v.Id,RegistrationNumber=v.RegistrationNumber,Make=v.Make,Model=v.Model,VehicleType=v.VehicleType,PassengerCapacity=v.PassengerCapacity,LuggageCapacity=v.LuggageCapacity,IsActive=v.IsActive,AssignedDriverId=d?.Id,AssignedDriverName=d is null?null:$"{d.FirstName} {d.LastName}",ComplianceState=ComplianceCalculator.Calculate([v.MOTExpiry,v.InsuranceExpiry,v.PrivateHireLicenceExpiry]),UpdatedAt=v.UpdatedAt};
    private static VehicleDetailDto ToDetail(Vehicle v,Driver? d)=>new(){Id=v.Id,RegistrationNumber=v.RegistrationNumber,Make=v.Make,Model=v.Model,VehicleType=v.VehicleType,PassengerCapacity=v.PassengerCapacity,LuggageCapacity=v.LuggageCapacity,IsActive=v.IsActive,AssignedDriverId=d?.Id,AssignedDriverName=d is null?null:$"{d.FirstName} {d.LastName}",ComplianceState=ComplianceCalculator.Calculate([v.MOTExpiry,v.InsuranceExpiry,v.PrivateHireLicenceExpiry]),UpdatedAt=v.UpdatedAt,CreatedAt=v.CreatedAt,Colour=v.Colour,Year=v.Year,Notes=v.Notes,MOTExpiry=v.MOTExpiry,InsuranceExpiry=v.InsuranceExpiry,PrivateHireLicenceExpiry=v.PrivateHireLicenceExpiry};
    private static string? Trim(string? v)=>string.IsNullOrWhiteSpace(v)?null:v.Trim();private static async Task Cross(LondonVIPDbContext db,IAuditService audit,Guid id,Guid companyId,CancellationToken token){if(await db.Vehicles.AnyAsync(x=>x.Id==id&&x.CompanyId!=companyId,token))await audit.WriteAsync("CrossTenantAccessAttempt","Authorization","Denied",SecurityEventSeverity.High,"Cross-tenant vehicle access was blocked.","Vehicle",id.ToString(),companyId,token);}
}
