using System.Net;
using System.Net.Http.Json;
using LondonVIP.Infrastructure.Data;
using LondonVIP.Infrastructure.Tenancy;
using LondonVIP.Shared.Bookings;
using LondonVIP.Shared.CorporateAccounts;
using LondonVIP.Shared.Models;
using LondonVIP.Shared.Security;
using LondonVIP.Tests.Infrastructure;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.EntityFrameworkCore;

namespace LondonVIP.Tests;

public class CorporateAccountEndpointTests
{
    [Fact] public async Task AdminCreatesListsReadsUpdatesAndAuditsAccount()
    {await using var h=await TestApiHost.StartAsync();var a=await Create(h,"ACC-001");Assert.Contains((await h.Client.GetFromJsonAsync<List<CorporateAccountListItemDto>>("/api/accounts"))!,x=>x.Id==a.Id);Assert.Equal(a.Id,(await h.Client.GetFromJsonAsync<CorporateAccountDetailDto>($"/api/accounts/{a.Id}"))!.Id);var u=Valid("ACC-001");u.AccountName="Updated Account";Assert.Equal(HttpStatusCode.OK,(await h.Client.PutAsJsonAsync($"/api/accounts/{a.Id}",u)).StatusCode);await using var s=h.App.Services.CreateAsyncScope();var db=s.ServiceProvider.GetRequiredService<LondonVIPDbContext>();Assert.Contains(db.SecurityAuditEvents,x=>x.EventType=="CorporateAccountCreated");Assert.Contains(db.SecurityAuditEvents,x=>x.EventType=="CorporateAccountUpdated");}
    [Fact] public async Task ValidationDuplicateAndClientBalanceInjectionAreSafe()
    {await using var h=await TestApiHost.StartAsync();Assert.Equal(HttpStatusCode.BadRequest,(await h.Client.PostAsJsonAsync("/api/accounts",new CorporateAccountCreateDto())).StatusCode);var a=await Create(h,"ACC-001");Assert.Equal(HttpStatusCode.BadRequest,(await h.Client.PostAsJsonAsync("/api/accounts",Valid("acc001"))).StatusCode);Assert.Equal(0m,a.CurrentBalance);}
    [Fact] public async Task AccountStatusAndTenantIsolationAreEnforcedAndAudited()
    {await using var h=await TestApiHost.StartAsync();var a=await Create(h,"ACC-001");using var hold=await Patch(h,$"/api/accounts/{a.Id}/status",new CorporateAccountStatusDto{IsActive=true,IsOnHold=true});Assert.Equal(HttpStatusCode.OK,hold.StatusCode);var other=await Other(h);Assert.Equal(HttpStatusCode.NotFound,(await h.Client.GetAsync($"/api/accounts/{other.Id}")).StatusCode);await using var s=h.App.Services.CreateAsyncScope();var db=s.ServiceProvider.GetRequiredService<LondonVIPDbContext>();Assert.Contains(db.SecurityAuditEvents,x=>x.EventType=="CorporateAccountPlacedOnHold");Assert.Contains(db.SecurityAuditEvents,x=>x.EventType=="CrossTenantAccessAttempt");}
    [Theory][InlineData(SecurityRoles.Dispatcher,HttpStatusCode.OK,HttpStatusCode.Forbidden)][InlineData(SecurityRoles.Finance,HttpStatusCode.OK,HttpStatusCode.Forbidden)][InlineData(SecurityRoles.Driver,HttpStatusCode.Forbidden,HttpStatusCode.Forbidden)] public async Task AccountAuthorizationUsesPolicies(string role,HttpStatusCode read,HttpStatusCode create)
    {await using var h=await TestApiHost.StartAsync();Assert.Equal(read,(await Send(h,HttpMethod.Get,"/api/accounts",role)).StatusCode);Assert.Equal(create,(await Send(h,HttpMethod.Post,"/api/accounts",role,Valid("ROLE1"))).StatusCode);}
    [Fact] public async Task SummaryAndStatementUseOnlyRealAccountBookings()
    {await using var h=await TestApiHost.StartAsync();var a=await Create(h,"ACC-001");var customer=await Customer(h);var booking=await Booking(h,customer.Id,a.Id,"PO-1");var summary=await h.Client.GetFromJsonAsync<CorporateAccountSummaryDto>("/api/accounts/summary");var statement=await h.Client.GetFromJsonAsync<CorporateAccountStatementDto>($"/api/accounts/{a.Id}/statement");Assert.Equal(1,summary!.CorporateBookings);Assert.Single(statement!.Transactions);Assert.Equal(booking.Id,statement.Transactions.Single().BookingId);Assert.Equal(0m,statement.CurrentBalance);}
    [Fact] public async Task CorporateBookingRequiresValidActiveUnheldAccountAndPurchaseOrder()
    {await using var h=await TestApiHost.StartAsync();var customer=await Customer(h);var po=await Create(h,"PO-001",true);var missing=BookingRequest(customer.Id,po.Id,null);Assert.Equal(HttpStatusCode.BadRequest,(await h.Client.PostAsJsonAsync("/api/bookings",missing)).StatusCode);var valid=BookingRequest(customer.Id,po.Id,"PO-42");Assert.Equal(HttpStatusCode.Created,(await h.Client.PostAsJsonAsync("/api/bookings",valid)).StatusCode);var held=await Create(h,"HOLD-1");(await Patch(h,$"/api/accounts/{held.Id}/status",new CorporateAccountStatusDto{IsActive=true,IsOnHold=true})).EnsureSuccessStatusCode();Assert.Equal(HttpStatusCode.BadRequest,(await h.Client.PostAsJsonAsync("/api/bookings",BookingRequest(customer.Id,held.Id,"PO"))).StatusCode);Assert.Equal(HttpStatusCode.Created,(await h.Client.PostAsJsonAsync("/api/bookings",BookingRequest(customer.Id,null,null))).StatusCode);}
    private static CorporateAccountUpdateDto Valid(string number)=>new(){AccountNumber=number,AccountName="Acme Travel",PrimaryContactName="Alex Contact",Email="accounts@example.test",Phone="07123456789",AddressLine1="1 Street",TownCity="London",Postcode="SW1A 1AA",Country="United Kingdom",BillingTerms=BillingTerms.ThirtyDays,IsActive=true};
    private static async Task<CorporateAccountDetailDto>Create(TestApiHost h,string number,bool po=false){var x=Valid(number);x.PurchaseOrderRequired=po;using var r=await h.Client.PostAsJsonAsync("/api/accounts",x);r.EnsureSuccessStatusCode();return(await r.Content.ReadFromJsonAsync<CorporateAccountDetailDto>())!;}
    private static async Task<Customer>Customer(TestApiHost h){var x=new Customer{Id=Guid.NewGuid(),CompanyId=LondonVipCompany.Id,FirstName="Customer",LastName="One",Email=$"c{Guid.NewGuid():N}@test.test",Phone="07123456789",IsActive=true,CreatedAt=DateTimeOffset.UtcNow,UpdatedAt=DateTimeOffset.UtcNow};await using var s=h.App.Services.CreateAsyncScope();var db=s.ServiceProvider.GetRequiredService<LondonVIPDbContext>();db.Customers.Add(x);await db.SaveChangesAsync();return x;}
    private static BookingCreateDto BookingRequest(Guid customerId,Guid? accountId,string? po)=>new(){CustomerId=customerId,CorporateAccountId=accountId,PurchaseOrderReference=po,PickupAddress="Pickup",Destination="Destination",PickupDateTime=DateTimeOffset.UtcNow.AddHours(2),PassengerCount=1,LuggageCount=0,VehicleType=VehicleType.Saloon,BaseFare=20m,TotalFare=20m,PaymentStatus="Pending"};
    private static async Task<Booking>Booking(TestApiHost h,Guid customerId,Guid accountId,string po){using var r=await h.Client.PostAsJsonAsync("/api/bookings",BookingRequest(customerId,accountId,po));r.EnsureSuccessStatusCode();var d=(await r.Content.ReadFromJsonAsync<BookingDetailDto>())!;await using var s=h.App.Services.CreateAsyncScope();return await s.ServiceProvider.GetRequiredService<LondonVIPDbContext>().Bookings.SingleAsync(x=>x.Id==d.Id);}
    private static async Task<CorporateAccount>Other(TestApiHost h){var id=Guid.NewGuid();var now=DateTimeOffset.UtcNow;var c=new Company{Id=id,TradingName="Other",LegalName="Other",Slug=$"other-{id:N}",Email="",Phone="",WebsiteUrl="",AddressLine1="",AddressLine2="",City="London",Postcode="",Country="UK",TimeZone="Europe/London",CurrencyCode="GBP",IsActive=true,CreatedAt=now,UpdatedAt=now};var a=new CorporateAccount{Id=Guid.NewGuid(),CompanyId=id,AccountNumber="OTHER",AccountName="Other",PrimaryContactName="Other",Email="other@test.test",Phone="07123456789",AddressLine1="x",TownCity="London",Postcode="x",Country="UK",CreatedAt=now,UpdatedAt=now};await using var s=h.App.Services.CreateAsyncScope();var db=s.ServiceProvider.GetRequiredService<LondonVIPDbContext>();db.Add(c);db.Add(a);await db.SaveChangesAsync();return a;}
    private static Task<HttpResponseMessage>Patch<T>(TestApiHost h,string u,T b)=>h.Client.SendAsync(new HttpRequestMessage(HttpMethod.Patch,u){Content=JsonContent.Create(b)});private static Task<HttpResponseMessage>Send<T>(TestApiHost h,HttpMethod m,string u,string role,T? b=default){var r=new HttpRequestMessage(m,u);r.Headers.Add("X-Test-Role",role);if(b is not null)r.Content=JsonContent.Create(b);return h.Client.SendAsync(r);}private static Task<HttpResponseMessage>Send(TestApiHost h,HttpMethod m,string u,string role)=>Send<object>(h,m,u,role);
}
