using System.Net;
using System.Net.Http.Json;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using LondonVIP.Infrastructure.Data;
using LondonVIP.Infrastructure.Tenancy;
using LondonVIP.Shared.Growth;
using LondonVIP.Shared.Models;
using LondonVIP.Tests.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace LondonVIP.Tests;

public sealed class GrowthCompletionEndpointTests
{
 [Fact] public async Task UnconfiguredProvidersAreDisabledAndReturnClearResponses(){await using var host=await TestApiHost.StartAsync();var providers=await host.Client.GetFromJsonAsync<List<ProviderConfigurationStatus>>("/api/growth/providers");Assert.NotNull(providers);Assert.Equal(7,providers.Count);Assert.All(providers,x=>{Assert.False(x.Configured);Assert.Contains("Not Configured",x.Status);});using var post=await host.Client.PostAsJsonAsync("/api/growth/social",new{channel="Facebook",accountKey="page",body="Hello"});Assert.Equal(HttpStatusCode.Created,post.StatusCode);var value=await post.Content.ReadFromJsonAsync<JsonElement>();using var publish=await host.Client.PostAsync($"/api/growth/social/{value.GetProperty("id").GetGuid()}/publish?immediate=true",null);var result=await publish.Content.ReadFromJsonAsync<ProviderOperationResult>();Assert.NotNull(result);Assert.False(result.Success);Assert.True(result.NotConfigured);Assert.Equal("Provider Not Configured",result.Message);using var ai=await host.Client.PostAsJsonAsync("/api/growth/ai/generate",new AiMarketingRequest("SocialCaption","Airport transfers","Professional",null,null));var aiResult=await ai.Content.ReadFromJsonAsync<AiMarketingResult>();Assert.True(aiResult!.NotConfigured);}
 [Fact] public async Task AnalyticsArePrivacyHashedTenantScopedAndReported(){await using var host=await TestApiHost.StartAsync();var request=new AnalyticsTrackRequest("visitor-raw","session-raw",AnalyticsEventType.QuoteStarted,"/book","google","cpc","airport",null,null,null,null,null);using var message=new HttpRequestMessage(HttpMethod.Post,"/api/growth/analytics/track"){Content=JsonContent.Create(request)};message.Headers.Add("X-Test-Anonymous","true");Assert.Equal(HttpStatusCode.Accepted,(await host.Client.SendAsync(message)).StatusCode);await using(var scope=host.App.Services.CreateAsyncScope()){var db=scope.ServiceProvider.GetRequiredService<LondonVIPDbContext>();var session=Assert.Single(await db.AnalyticsSessions.ToListAsync());Assert.NotEqual("visitor-raw",session.AnonymousIdHash);Assert.NotEqual("session-raw",session.SessionKeyHash);Assert.Equal(LondonVipCompany.Id,session.CompanyId);}var now=DateTimeOffset.UtcNow;var report=await host.Client.GetFromJsonAsync<GrowthReportDto>($"/api/growth/reports?from={Uri.EscapeDataString(now.AddHours(-1).ToString("O"))}&to={Uri.EscapeDataString(now.AddHours(1).ToString("O"))}");Assert.NotNull(report);Assert.Equal(0,report.QuoteConversionRate);}
 [Fact] public async Task DoubleOptInRejectsExpiredTokensAndAcceptsValidTokensIdempotently(){await using var host=await TestApiHost.StartAsync();var valid="VALID-TOKEN";var expired="EXPIRED-TOKEN";await using(var scope=host.App.Services.CreateAsyncScope()){var db=scope.ServiceProvider.GetRequiredService<LondonVIPDbContext>();db.NewsletterSubscribers.AddRange(Subscriber("valid@example.test",valid,DateTimeOffset.UtcNow.AddHours(1)),Subscriber("expired@example.test",expired,DateTimeOffset.UtcNow.AddMinutes(-1)));await db.SaveChangesAsync();}using var bad=new HttpRequestMessage(HttpMethod.Post,$"/api/growth/newsletters/confirm?token={expired}");bad.Headers.Add("X-Test-Anonymous","true");Assert.Equal(HttpStatusCode.BadRequest,(await host.Client.SendAsync(bad)).StatusCode);using var good=new HttpRequestMessage(HttpMethod.Post,$"/api/growth/newsletters/confirm?token={valid}");good.Headers.Add("X-Test-Anonymous","true");Assert.Equal(HttpStatusCode.OK,(await host.Client.SendAsync(good)).StatusCode);using var again=new HttpRequestMessage(HttpMethod.Post,$"/api/growth/newsletters/confirm?token={valid}");again.Headers.Add("X-Test-Anonymous","true");Assert.Equal(HttpStatusCode.BadRequest,(await host.Client.SendAsync(again)).StatusCode);}
 [Fact] public async Task CampaignLifecycleBuildsDeliveryQueueOnlyForConfirmedSubscribers(){await using var host=await TestApiHost.StartAsync();await using(var scope=host.App.Services.CreateAsyncScope()){var db=scope.ServiceProvider.GetRequiredService<LondonVIPDbContext>();db.NewsletterSubscribers.Add(Subscriber("confirmed@example.test","x",DateTimeOffset.UtcNow.AddHours(1),true));db.NewsletterSubscribers.Add(Subscriber("pending@example.test","y",DateTimeOffset.UtcNow.AddHours(1)));await db.SaveChangesAsync();}using var created=await host.Client.PostAsJsonAsync("/api/growth/campaigns",new CampaignRequest("Airport news",MarketingChannel.Email,"newsletter","airport-template",DateTimeOffset.UtcNow.AddMinutes(-1)));var json=await created.Content.ReadFromJsonAsync<JsonElement>();var id=json.GetProperty("id").GetGuid();Assert.Equal(HttpStatusCode.OK,(await host.Client.PostAsync($"/api/growth/campaigns/{id}/schedule",null)).StatusCode);var queued=await (await host.Client.PostAsync("/api/growth/campaigns/process",null)).Content.ReadFromJsonAsync<int>();Assert.Equal(1,queued);await using var resultScope=host.App.Services.CreateAsyncScope();Assert.Single(await resultScope.ServiceProvider.GetRequiredService<LondonVIPDbContext>().CampaignDeliveries.ToListAsync());}
 [Fact] public async Task SocialWebhookRejectsUnsignedRequests(){await using var host=await TestApiHost.StartAsync();using var request=new HttpRequestMessage(HttpMethod.Post,"/api/growth/webhooks/london-vip-cars/Facebook"){Content=new StringContent("{}")};request.Headers.Add("X-Test-Anonymous","true");Assert.Equal(HttpStatusCode.Unauthorized,(await host.Client.SendAsync(request)).StatusCode);}
 static NewsletterSubscriber Subscriber(string email,string token,DateTimeOffset expires,bool confirmed=false)=>new(){Id=Guid.NewGuid(),CompanyId=LondonVipCompany.Id,Email=email.ToUpperInvariant(),Lists="General",Segments="",IsConfirmed=confirmed,ConfirmationTokenHash=Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(token))),ConfirmationExpiresAt=expires,SubscribedAt=DateTimeOffset.UtcNow};
}
