using System.Net;
using System.Net.Http.Json;
using LondonVIP.Infrastructure.Data;
using LondonVIP.Infrastructure.Tenancy;
using LondonVIP.Shared.Models;
using LondonVIP.Shared.Workflows;
using LondonVIP.Tests.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace LondonVIP.Tests;

public sealed class WorkflowEndpointTests
{
    [Fact] public async Task BusinessEventPublishingCreatesDurableWorkflowAndExecutionCompletes() { await using var host = await TestApiHost.StartAsync(); Guid jobId; await using (var scope = host.App.Services.CreateAsyncScope()) { var publisher = scope.ServiceProvider.GetRequiredService<IBusinessEventPublisher>(); await publisher.PublishAsync(new(BusinessEventTypes.BookingCreated, "Booking", Guid.NewGuid(), "{}", "event-1")); var db = scope.ServiceProvider.GetRequiredService<LondonVIPDbContext>(); Assert.Single(db.BusinessEvents); Assert.Equal(2, await db.WorkflowJobs.CountAsync()); jobId = await db.WorkflowJobs.Select(x => x.Id).FirstAsync(); } Assert.Equal(HttpStatusCode.OK, (await host.Client.PostAsync($"/api/workflows/jobs/{jobId}/run", null)).StatusCode); await using (var scope = host.App.Services.CreateAsyncScope()) { var db = scope.ServiceProvider.GetRequiredService<LondonVIPDbContext>(); Assert.Equal(WorkflowJobStatus.Completed, await db.WorkflowJobs.Where(x => x.Id == jobId).Select(x => x.Status).SingleAsync()); Assert.Contains(db.SecurityAuditEvents, x => x.EventType == "WorkflowRun"); } }
    [Fact] public async Task ReminderGenerationIsIdempotentAndTenantScoped() { await using var host = await TestApiHost.StartAsync(); await SeedBookingAsync(host, LondonVipCompany.Id); await SeedBookingAsync(host, Guid.NewGuid()); var first = await host.Client.PostAsJsonAsync("/api/workflows/reminders/generate", new { }); Assert.Equal(HttpStatusCode.OK, first.StatusCode); await host.Client.PostAsJsonAsync("/api/workflows/reminders/generate", new { }); await using var scope = host.App.Services.CreateAsyncScope(); var db = scope.ServiceProvider.GetRequiredService<LondonVIPDbContext>(); Assert.Single(db.WorkflowJobs.Where(x => x.CompanyId == LondonVipCompany.Id)); Assert.DoesNotContain(db.WorkflowJobs, x => x.CompanyId != LondonVipCompany.Id); }
    [Fact] public async Task RetryCancelFilteringAndAuthorizationWork() { await using var host = await TestApiHost.StartAsync(); Guid id; await using (var scope = host.App.Services.CreateAsyncScope()) { var jobs = scope.ServiceProvider.GetRequiredService<IBackgroundJobService>(); id = (await jobs.ScheduleAsync(new("Test Retry", "{}", DateTimeOffset.UtcNow, CorrelationId: "retry-1"))).Id; } Assert.Equal(HttpStatusCode.OK, (await host.Client.PostAsync($"/api/workflows/jobs/{id}/cancel", null)).StatusCode); var page = await host.Client.GetFromJsonAsync<WorkflowPageDto<WorkflowJobDto>>("/api/workflows/jobs?status=5&search=Test"); Assert.Single(page!.Items); using var request = new HttpRequestMessage(HttpMethod.Get, "/api/workflows/dashboard"); request.Headers.Add("X-Test-Anonymous", "true"); Assert.Equal(HttpStatusCode.Unauthorized, (await host.Client.SendAsync(request)).StatusCode); }
    [Fact] public async Task EmptyDashboardAndRuleEvaluationAreSafe() { await using var host = await TestApiHost.StartAsync(); var dashboard = await host.Client.GetFromJsonAsync<WorkflowDashboardDto>("/api/workflows/dashboard"); Assert.NotNull(dashboard); Assert.Equal(0, dashboard.JobsWaiting); await using var scope = host.App.Services.CreateAsyncScope(); var db = scope.ServiceProvider.GetRequiredService<LondonVIPDbContext>(); db.WorkflowRules.Add(new() { Id = Guid.NewGuid(), CompanyId = LondonVipCompany.Id, Name = "High value", EventType = BusinessEventTypes.BookingCreated, ConditionField = "TotalFare", Operator = "GreaterThan", ComparisonValue = "200", Action = "RequireDispatcherApproval", Priority = 10, CreatedAt = DateTimeOffset.UtcNow, UpdatedAt = DateTimeOffset.UtcNow }); await db.SaveChangesAsync(); var result = await scope.ServiceProvider.GetRequiredService<IRuleEngine>().EvaluateAsync(BusinessEventTypes.BookingCreated, new(new Dictionary<string, string> { { "TotalFare", "250" } })); Assert.True(result.Matched); Assert.Equal("RequireDispatcherApproval", result.Action); }
    private static async Task SeedBookingAsync(TestApiHost host, Guid companyId) { var now = DateTimeOffset.UtcNow; await using var scope = host.App.Services.CreateAsyncScope(); var db = scope.ServiceProvider.GetRequiredService<LondonVIPDbContext>(); if (companyId != LondonVipCompany.Id) db.Companies.Add(new() { Id = companyId, TradingName = "Other", LegalName = "Other", Slug = $"other-{companyId:N}", CurrencyCode = "GBP", TimeZone = "Europe/London", IsActive = true, CreatedAt = now, UpdatedAt = now }); var customer = new Customer { Id = Guid.NewGuid(), CompanyId = companyId, FirstName = "Workflow", LastName = "Test", Email = $"{Guid.NewGuid():N}@test.local", Phone = "1", IsActive = true, CreatedAt = now, UpdatedAt = now }; db.Customers.Add(customer); db.Bookings.Add(new() { Id = Guid.NewGuid(), CompanyId = companyId, CustomerId = customer.Id, BookingReference = $"WF-{Guid.NewGuid():N}"[..20], PickupAddress = "A", Destination = "B", PickupDateTime = now.AddHours(8), PassengerCount = 1, VehicleType = VehicleType.Saloon, Status = BookingStatus.Confirmed, PaymentStatus = "Pending", CreatedAt = now, UpdatedAt = now }); await db.SaveChangesAsync(); }
}
